---
title: "Homework 1"
subtitle: "BSTA 550"
description: "Due: Thursday October 5, 2023"
date-modified: "09/11/2023"
date: "10/5/2023"
categories: [""]
format: 
  html: 
    link-external-newwindow: true
    toc: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

## Directions

[Please turn in this homework on Sakai.](https://sakai.ohsu.edu/portal/site/BSTA-550-1-12619-F23/tool/085b18e7-8118-4a51-ace5-0255aa46136e?panel=Main)

Complete all of the problems listed below. Only turn in the ones listed in the "Turn In" column. Please submit problems in the order they are listed.

*You must show all of your work to receive credit.*

::: center
| Chapter |      Turn In       |              Extra Problems              |
|:-------:|:------------------:|:----------------------------------------:|
|    1    |                    |              \# 3, 7, 9, 11              |
|    2    | NTB \# 1, TB \# 30 |          \# 1, 4, 8, 16, 19, 23          |
|  22\*   | TB \# 42, NTB \# 2 | \# 3, 5, 7, 25, 27, 30, 31, 39-41, 43-48 |
:::

\* Please note the following for Chapter 22:

-   See the table on pg. 277, which summarizes some key combinatorics concepts.

-   Problems 39-48 are a set that build on one another and more advanced than the other problems. It'll be much easier to do #42 after doing 39-41.

-   I *highly* recommend reading Chapter 23, which is a series of case studies in counting: poker hands and Yahtzee.

## Non-textbook problems (NTB)

1.  Suppose the following are the percentage of US adults with the following conditions:

    -   $A$: Hypertension 33%

    -   $B$: Diabetes 9%

    -   $C$: Metabolic syndrome 24%

    -   $A$ or $B$: 39%

    -   $A$ or $C$: 45%

    -   $B$ or $C$: 28%

    -   $A$ or $B$ or $C$: 48%

    a.  Make a Venn diagram of the 3 conditions labeling the percentage (or probability) for *ALL* of the 8 "sections". *Hint: Start from the last condition and work your way up!*
    b.  For each of the following (1. - 7. below), ($i$) write out the event using unions, intersections, and/or complements of the events $A$, $B$, and $C$ (this is NOT finding the probability, that's in $ii$); ($ii$) find the probability of the event; and ($iii$) write a sentence explaining what the probability is of in terms of the context of the problem.
        1.  $\mathbb{P}$(event at least one of the 3)

        2.  $\mathbb{P}$(event none)

        3.  $\mathbb{P}$(event $A$ only)

        4.  $\mathbb{P}$(event exactly one)

        5.  $\mathbb{P}$(event $A$ and $B$)

        6.  $\mathbb{P}$(event $A$ and $B$ but not $C$)

        7.  $\mathbb{P}$(event all 3)

2.  The German word for probability theory is $$W\ A\ H\ R\ S\ C\ H\ E\ I\ N\ L\ I\ C\ H\ K\ E\ I\ T\ S\ T\ H\ E\ O\ R\ I\ E$$ If the letters in this word are arranged at random,

    a.  what is the probability that none of the H's will be adjacent?
    b.  what is the probability that not all of the H's will be adjacent?

## Some select answers

Selected answers (or hints) not provided at the end the book:

-   Chapter 2

    -   \# 4: 0.35

    -   \# 8: 0.03125

    -   \# 16: 0.48

    -   \# 30: (a) 0.189     (b) 0.811     (c) 0.189

-   Chapter 22

    -   \# 30: (a) 2,835     (b) 405     (c) 10,780     (d) 7,980

    -   \# 40: 0.6666667

    -   \# 42: 0.002116402 (This is the answer when $n=5$. Your answer needs to be in terms of $n$.)

    -   \# 44: 0.3

    -   \# 46: 0.3333333

    -   \# 48: 0.007936508 (This is the answer when $n=5$. Your answer needs to be in terms of $n$.)
