---
title: "Homework 7"
subtitle: "BSTA 550"
description: "Due: Friday November 30, 2023"
date-modified: "09/11/2023"
date: "11/30/2023"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

Complete all of the problems listed below. Only turn in the ones listed in the "Turn In" column. Please submit problems in the order they are listed.

*You must show all of your work to receive credit. Don't forget to define every r.v. you use!* *In particular, **if a similar problem was done in class or an example in the book, make sure to still show every step in the solution and not just cite the examples' results**.*

::: center
| Chapter |                     Turn In                     |        Extra Problems        |
|:----------------:|:-------------------------:|:-------------------------:|
|   28    |                    TB \# 18                     |         TB \# 1, 10          |
| 29[^1]  |              TB \# 26, NTB \# 1, 3              | TB \# 10, 14, 23, 11, 13, 32 |
|   30    |                                                 |        TB \# 4, 7-12         |
|   31    |                    TB \# 18                     |       TB \# 13, 14, 17       |
|   32    |                     TB \# 8                     |    TB \# 3, 5, 10[^2], 15    |
|   33    |                    NTB \# 4                     |        TB \# 3, 9, 10        |
|   35    |               TB \# 10, NTB \# 5                |        TB \# 6, 9, 24        |
|   43    | TB \# 9[^3], 10[^4], 11, 12[^5], NTB \# 6, 7, 8 |     TB \# 1-4, NTB \# 9      |
|   36    |                TB \# 12[^6], 14                 |   TB \# 4, 11, 13, 15, 16    |
|   37    |                  TB \# 24, 30                   |    TB \# 2, 4, 13, 20, 29    |
:::

[^1]: I recommend doing the Chapter 29 Extra Problems in the order listed.

[^2]: Assume $X$ and $Y$ are independent.

[^3]: Include in your answer an explanation as to why we need the condition that $t<\lambda$.

[^4]: Do parts (a)-(c) below for #10 and #12:

    -   Answer the question using the mgf $M_X(t)$ as instructed in the book.

    -   Answer the question using $R_X(t)$ (as defined in class, and NTB \# 6below).

    -   Which method did you prefer? Why?

[^5]: Do parts (a)-(c) below for #10 and #12:

    -   Answer the question using the mgf $M_X(t)$ as instructed in the book.

    -   Answer the question using $R_X(t)$ (as defined in class, and NTB \# 6 below).

    -   Which method did you prefer? Why?

[^6]: Assume the distances between the cars are independent.

## Non-textbook problems (NTB)

1.  Let $f_X(x)=\lambda e^{-\lambda x}$ for $x>0$, where $\lambda>0$.

    a.  Show $Var[X]=\frac{1}{\lambda^2}$. You may use the result from class for $\mathbb{E}[X]$ without first proving it.

2.  A shipping company handles containers in three different sizes: (1) 27 $ft^3$ (3 x 3 x 3), (2) 125 $ft^3$, and (3) 512 $ft^3$. Let $X_i$ ($i = 1, 2, 3$) denote the number of type $i$ containers shipped during a given week. Suppose that $\mu_1 =200,\sigma_1=10,\mu_2 =250,\sigma_2=12,\mu_3 =100,\sigma_3=8$.

    a.  Assuming that $X_1,X_2,X_3$ are independent, calculate the expected value and variance of the total volume shipped.

    b.  Would your calculations necessarily be correct if the $X_i$'s were not independent? Explain.

3.  Suppose your waiting time for a bus in the morning is uniformly distributed on \[0, 8\] (minutes), whereas waiting time in the evening is uniformly distributed on \[0, 10\] (minutes) independent of morning waiting time. *Make sure to FIRST set up an equation for calculating the total waiting time in each question before calculating the mean and variance of the total waiting time.* *You may use results from class for the expected value and variance of uniform r.v.'s without proving them.*

    a.  If you take the bus each morning and evening for a week (7 days), what is your total expected waiting time?

    b.  What is the variance of your total waiting time?

    c.  What are the expected value and variance of the difference between morning and evening waiting times on a given day?

    d.  What are the expected value and variance of the difference between total morning waiting time and total evening waiting time for a particular week?

4.  Suppose that voters arrive at a polling station at the rate of 120 per hour.For each of the following parts, [give the name and parameter(s) of the distribution]{.underline} to be used to model the event and [set up the expression]{.underline} to find the specified probability.*You do not need to compute the probability.*

    a.  The probability that the next voter will arrive in less than 30 seconds.

    b.  The probability that 200 voters will arrive within two hours of each other.

    c.  The probability that the $50^{th}$ voter will arrive in between 15 and 30 minutes.

5.  The automatic opening device of a military cargo parachute has been designed to open when the parachute is 200 m above the ground. Suppose opening altitude actually has a normal distribution with mean value 200 m and standard deviation 30 m. Equipment damage will occur if the parachute opens at an altitude of less than 100 m. What is the probability that there is equipment damage to the payload of at least one of the five independentIy dropped parachutes?

6.  Let $R_X(t)=\ln(M_X(t))$. Show that Var$(X)=R''_X(0)$.

7.  The mgf for a Gamma distribution is $M_X(t)=\frac{1}{(1-t/\lambda)^r}$. Use the mgf of an Exponential distribution (from #43.9), to show that the sum of $n$ i.i.d. Exponential($\lambda)$ random variables has a Gamma($r,\lambda$) distribution.

8.  Use the mgf of a Poisson distribution to find the mgf of the following distributions. If the mgf is that of a common named distribution, then name the distribution and state its parameter(s).

    a.  The distribution of $\sum_{i=1}^nX_i$, if $X_i\sim$Poisson$(\lambda_i)$ and are independent.

    b.  The distribution of $\sum_{i=1}^3X_i$, if $X_i\sim$Poisson$(\lambda)$ and are independent (i.i.d. in this case).

    c.  The distribution of $3X$, if $X\sim$Poisson$(\lambda)$.

    d.  Why are the answers to (b) and (c) different?

9.  Using mgf's, show that the sum of $n$ i.i.d. Chi Square random variables with one degree of freedom ($\chi^2_{(1)}$) r.v.'s has a Chi Square with $n$ degrees of freedom ($\chi^2_{(n)}$) distribution.

    *Hint:* First, look up the pdf of a $\chi^2_{(n)}$. This is a special case of the Gamma distribution with what parameters? Based on that and the information from \# 7 above, you can determine what the mgf of a $\chi^2_{(n)}$ is, which will help you determine whether the mgf of the sum of $n$ i.i.d. $\chi^2_{(1)}$ r.v.'s has a $\chi^2_{(n)}$ distribution.

## Some select answers

Selected answers (or hints) not provided at the end the book:

-   Chapter 28

    -   \# 10: (a) 8/9     (b) 14/3     

    -   \# 18: 4/5

-   Chapter 29

    -   \# 10: (a) 26/81     (b) 74/9

    -   \# 14: (a) 67/3     (b) 1/14     (c) 25/12     (d) $\sqrt{25/12}$

    -   \# 26: 250

    -   \# 32: See notes (or book) for the proof from the discrete random variables case. The proof doesn't depend on what type of random variable (discrete vs. continuous) is being used.

    -   NTB \# 3: (a) 63     (b) 287/3     (c) -1, 41/3     (d) -7, 287/3

-   Chapter 30

    -   \# 4: $f_x(x)=1/2$ for $2\leq x\leq 4$

    -   \# 8: (a) T     (b) T     (c) F

    -   \# 10: (a) F     (b) T

    -   \# 12: (a) T     (b) T     (c) F     (d) T

-   Chapter 31

    -   \# 14: (a) 0.25     (b) 0.02887     (c) 0.063     (d) 0.0145     (e) 0.01625     (f) 0.0055     (f) 6.195    (g) 0.00433     (h) 61.95     (i) 0.0433

    -   \# 17: 2.25

    -   \# 18: 7/15

-   Chapter 32

    -   \# 8: 0.2526

    -   \# 5: 0.8047

    -   \# 10: 0.4323

-   Chapter 33

    -   #10: (a) $f_x(x)=\frac{x}{9}e^{-x/3}$ for $x> 0$     (b) 0.4963

-   Chapter 35

    -   \# 6: (a) 0     (b) -1.13     (c) $\pm 0.32$

    -   \# 10: (a) 0.0475     (b) 0.0475     (c) 0.2283     (d) 68.97 to 81.03     (e) 48 to 102     (f) 68.97

    -   \# 24: (a) 0.2119     (b) 0.0011

    -   NTB \# 5:   0.002

-   Chapter 43

    -   NTB \# \_\_: (a) Poisson$(\sum_{i=1}^n \lambda_i)$     (b) Poisson$(3\lambda)$      (c) $M_{3X}(t)=e{\lambda(e^{3t}-1)}$ This is not an mgf of a common probability distribution.      (d) In (b) we are adding independent r.v.'s $X_i$, while in (c) we are adding dependent r.v.'s ($3X=X+X+X$; $X$ is dependent with itself).

-   Chapter 36

    -   \# 4: 0.0044

    -   \# 12: (a) 0.9525     (b) 0.7939     (c) 0.7939

    -   \# 14: 0.5911

    -   \# 16: (a) $R=8.225\sigma+25\mu$     (b) $R=16.45\sigma+100\mu$     (c) $R=164.5\sigma+10,000\mu$     (d) $R=1.645\sqrt{n}\sigma+n\mu$

-   Chapter 37

    -   \# 2: 0.8869

    -   \# 4: 0.0023

    -   \# 20: 0.3936

    -   \# 24: 0.4562

    -   \# 30: (b) 0.0022     (c) $478.696\approx 479$
