---
title: "Week 5"
description: "Multiple Linear Regression"
date: "2/5/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #213c96;
  background-color: #fff;
  padding: 10px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #213c96;
  padding: 10px;
}
```

::: callout-important
## Room Locations for the week

-   On Monday, 2/5,        we will be in **RLSB 3A001**
    -   When you look out from RLSB 3A003 A, across the atrium on the same floor-ish
-   On Wednesday, 2/7,  we will be in **RLSB 3A003 A**
:::

### topics {.hidden}

interpreting model parameters

matrix representation

parameter estimation (OLS)

properties of estimators

sums of squares - hypothesis testing is overall topic - sums of squares - F test - nested models? - covariate subset test - single covariate test

## Resources

Below is a table with links to resources. Icons in [orange]{style="color:#E25D3B;"} mean there is an available file link.

| Lesson | Topic                                      |                                Slides                                 |                                  Annotated Slides                                  |                           Recording                           |
|---------------|---------------|:-------------:|:-------------:|:-------------:|
|        | A word on Lab 1 and Quiz 1                 |                                                                       |                                                                                    |                                                               |
| 8      | Introduction to Multiple Linear Regression | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |
| 9      | MLR: Inference                             | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |

## On the Horizon

-   Lab 2 due 2/8
-   Homework 3 due 2/15

## Class Exit Tickets

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQzNRMlJSM1NGOTJRUVExQ0hKWFlYMDFDNC4u)]{style="color:#f8f5f0;"} Monday (2/5)

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMjFSMEVQTktEWEtGNk01M0dDNFE4U1pIWi4u)]{style="color:#f8f5f0;"} Wednesday (2/7)

## Announcements

### Monday 2/5

-   Adding a page for coefficient interpretations under resources

### Wednesday 2/7

-   Let's check in on Lab 2

## Muddiest Points

```{r}
#| echo: false

g=3
```
