---
title: "Week 8"
description: "Interactions continued"
date: "2/26/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #213c96;
  background-color: #fff;
  padding: 10px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #213c96;
  padding: 10px;
}
```

## Resources

+--------+------------------------+--------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lesson | Topic                  | Slides                                                                                                 | Annotated Slides                                                                                                              | Recording                                                                                                                                                                                                                                                                                                                                                                                |
+========+========================+:======================================================================================================:+:=============================================================================================================================:+:========================================================================================================================================================================================================================================================================================================================================================================================:+
| 11.1   | Interactions           | [[{{< iconify ri slideshow-fill size=30px >}}](/slides/11_Interactions.qmd)]{style="color:#f8f5f0;"}   | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/slides_annotated/11_Interactions.pdf)]{style="color:#f8f5f0;"}   | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F11%5FInteractions%5F1%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"}     |
|        |                        |                                                                                                        |                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                                          |
|        |                        |                                                                                                        |                                                                                                                               | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F11%5FInteractions%5F2%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"}     |
|        |                        |                                                                                                        |                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                                          |
|        |                        |                                                                                                        |                                                                                                                               | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F11%5FInteractions%5F3%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"}     |
+--------+------------------------+--------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11.2   | Interactions continued | [[{{< iconify ri slideshow-fill size=30px >}}](/slides/11_Interactions_2.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/slides_annotated/11_Interactions_2.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F11%2E2%5FInteractions%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"}     |
|        |                        |                                                                                                        |                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                                          |
|        |                        |                                                                                                        |                                                                                                                               | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F11%2E2%5FInteractions%5F2%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"} |
+--------+------------------------+--------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## On the Horizon

-   Lab 3 due 3/3 at 11pm

-   HW 5 (last homework!!) due 3/7

## Announcements

### Monday 2/26

-   Wednesday class: finish interactions + office hours for lab

-   Midterm feedback is still open! Please complete it by the end of this week!!

### Wednesday 2/28

## Class Exit Tickets

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUREZLTkxLUUlBNk4wODRKRkNCQk1HVzRKNi4u)]{style="color:#f8f5f0;"} Monday (2/26)

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQU9ZNzY0NEs4TEVVRFZVU1FHMTJGSEFXOC4u)]{style="color:#f8f5f0;"} Wednesday (2/28)

## Muddiest Points

This will be filled in with your Exit Ticket responses.

```{r}
#| echo: false

g=3
```

### 1. Understanding when you can and cannot use a t-test

We cannot use a t-test when we are testing more than one coefficient. "Testing more than one coefficient" might be testing an interaction involving a multi-level variable, testing the main effect of a multi-level variable, or testing a group of variables at the same time.

### There was a drawing about fans being EMM and the parallel lines being confounding. Could you explain that?

### When does centering change the slope not the intercept?

### Deciding between confounder and effect modifier. I have always been confused about these topics.

### I'm still unsure about the number of interactions and how that is determined for multi-level covariates.

### For income level as an effect modifier for World Region on Life Expectancy, when we talk about the intercept when everything is 0, what does that mean when world region is 0?

### Getting a little mixed up on swapping terminology between effect modifier and interaction, these two mean the same things and ARE NOT the same as a confounder (i.e. confounder and effect modifiers are mutually exclusive)?

### I still don't really understand how you determine if something is a confounder or not. Is it that if a variable affects the main effect but the interaction isn't significant then it's a confounder? i.e. if in R you compare Y\~X1 to Y\~X1+X2 and find a 10+% change in the effect, but an ANOVA comparing Y\~X1+X2 to Y\~X1\*X2 is not significant then X2 is a confounder? This came up on HW4 as well -- can something be a confounder if the main effect is insignificant?

### Testing for a confounder: I thought the difference between a confounder & effect modifier was that B_1 doesn't change with a confounder. Why is it that we're testing for a \>10% change in B_1 when introducing a confounding variable? Shouldn't we be testing whether B_2 adds significantly to B_0? That is, a confounder shifts the coefficient for our variable of interest, B_1, significantly?

### Can you explain the third criterion/thing you would look at when deciding whether to include a variable as a confounder when not all coefficients change \>10%?
