---
title: "Week 10"
description: "Model Diagnostics"
date: "3/11/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #213c96;
  background-color: #fff;
  padding: 10px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #213c96;
  padding: 10px;
}
```

## Resources

+---------+----------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Chapter | Topic                            | Slides                                                                                                       | Annotated Slides                                                                                                                     | Recording                                                                                                                                                                                                                                                                                                                                                                                      |
+=========+==================================+:============================================================================================================:+:====================================================================================================================================:+:==============================================================================================================================================================================================================================================================================================================================================================================================:+
|         | Lab 3 Feedback                   | [[{{< iconify ri slideshow-fill size=30px >}}](/slides/Lab_3_feedback.qmd)]{style="color:#49A3D1;"}          | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                                                   | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2FLab%5F3%5Ffeedback%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"}              |
+---------+----------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13      | Purposeful Model Selection       | [[{{< iconify ri slideshow-fill size=30px >}}](/slides/13_Purposeful_Selection.qmd)]{style="color:#49A3D1;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/slides_annotated/13_Purposeful_selection_.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F13%5FPurposeful%5Fselection%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"}     |
|         |                                  |                                                                                                              |                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                |
|         |                                  |                                                                                                              |                                                                                                                                      | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F13%5FPurposeful%5Fselection%5F2%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"} |
+---------+----------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14      | Model Evaluation and Diagnostics | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                        | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                                                   | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"}                                                                                                                                                                                                                                                                                                                                  |
+---------+----------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15      | Multicollinearity                | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                        | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                                                   | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"}                                                                                                                                                                                                                                                                                                                                  |
+---------+----------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## On the Horizon

## Announcements

### Monday 3/11

-   Correction in Model selection slides: larger adjusted R-squared is better!!
-   My office hours will be changed from 11:30am - 1pm **to 11am - 12:30pm**
    -   Office hours on 3/14 are 11am - 12:30pm

### Wednesday 3/13

-   Lab 3 feedback

    -   Sorry for using "Other" instead of "A different identity" which was exactly what I was saying NOT to do

    -   I should have looked more closely at the codebook before making those slides

## Class Exit Tickets

[{{< iconify healthicons health-worker-form-negative size=30px >}}]{style="color:#f8f5f0;"} Monday (3/11)

[{{< iconify healthicons health-worker-form-negative size=30px >}}]{style="color:#f8f5f0;"} Wednesday (3/13)

## Muddiest Points

This will be filled in with your Exit Ticket responses.

```{r}
#| echo: false

g=3
```
