---
title: "Week 4"
description: "SLR: Diagnostics"
date: "1/29/2024"
date-modified: "1/17/2024"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #213c96;
  background-color: #fff;
  padding: 10px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #213c96;
  padding: 10px;
}
```

::: callout-important
## Room Locations for the week

-   On Monday, 1/29,        we will be in **RLSB 3A003 B**
-   On Wednesday, 2/1,  we will be in **RLSB 3A003 A**
:::

### Topics: {.hidden}

-   SLR vs MLR

-   interpreting model parameters

-   matrix representation

-   parameter estimation (OLS)

-   properties of estimators

-   sums of squares

## Resources

Below is a table with links to resources. Icons in [orange]{style="color:#E25D3B;"} mean there is an available file link.

+-------------+--------------------------+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lesson      | Topic                    | Slides                                                                                                     | Annotated Slides                                                                                                                 | Recording                                                                                                                                                                                                                                                                                                                                                                                 |
+=============+==========================+:==========================================================================================================:+:================================================================================================================================:+:=========================================================================================================================================================================================================================================================================================================================================================================================:+
| 6           | SLR: Model Diagnostics 1 | [[{{< iconify ri slideshow-fill size=30px >}}](/slides/06_SLR_Diagnostics.qmd)]{style="color:#f8f5f0;"}    | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/slides_annotated/06_SLR_Dignostics_1.pdf)]{style="color:#f8f5f0;"}  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F06%5FSLR%5FDiagnostics%5F1%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"} |
+-------------+--------------------------+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7           | SLR: Model Diagnostics 2 | [[{{< iconify ri slideshow-fill size=30px >}}](/slides/07_SLR_Diagnostics_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/slides_annotated/07_SLR_Diagnostics_2.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F07%5FSLR%5FDiagnostics%5F2%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"} |
+-------------+--------------------------+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## On the Horizon

-   [Homework 2 due 2/1](/homework/HW2.qmd)
-   Lab 2 due 2/8

## Class Exit Tickets

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUN1Y2VVNPQk5ONkFUSzI1TjcwNVM3R1JDUS4u)]{style="color:#f8f5f0;"} Monday (1/29)

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURTIwRVlSSVgzSDJPWlNYTDlBR0dYTTIwSC4u)]{style="color:#f8f5f0;"} Wednesday (1/31)

## Announcements

### Monday 1/29

Quiz - no announcements

### Wednesday 1/31

-   Vote in Exit ticket: Emailing me questions privately vs. posting on Slack

    -   I am proposing a new class policy to anonymously post any emailed questions on Slack

    -   I know it can be scary to pose a question to the whole class

    -   Even questions about logistics can be answered by anyone and endorsed by me

        -   Will help get answers faster

    -   Sometimes I see your email, but don't have time carved out for my emails until later in the day or the next day

-   Lab 1 IS ALMOST GRADED!!

-   Lab 2 IS POSTED!!

## Muddiest Points

```{r}
#| echo: false

g=3
```

Equality of the residuals - what’s the bias refer in a residual plot? Is that suggesting a non linear relationship between two variables

I'm still a little confused about what the values on the axes of the QQ plot mean, specifically what the "quantiles" mean, how they might vary for different datasets, and why normality would result in a straight line.

What is a QQ plot

I’m still a little confused on how to determine if a dataset has a normal distribution. I think I’m struggling with making the delineation because I’m not super confident with statistics and it feels like a more subjective decision.

+--------------------------------------------------------------------+
| \                                                                  |
| the small nuances in interpreting the normality through a QQ plot. |
+--------------------------------------------------------------------+

1\. Is there a threshold value to reference when utilizing residuals for determining normality? Is the threshold "0" or near zero itself? (Like when normal dist=mean of zero). In my last biostats class, we said we could assume this if it was "near zero". For example, when plotted qq on slide 26, it nearly crosses "0,0" but isn't precisely crossing 0,0. Then, if a plot DOES cross 0,0, but is irregular in some other way (like the t dist ex) is this no longer normal? I wasn't sure if you were explicitly suggesting it was or was not normal... I had been taught that t dist is a type of normal distribution, so I was a bit confused.

Explain formula for internally standardized residuals. 2. How do we determine WHAT the source of the issue is for an outlier... i.e. "outlier detection". Is it just highly situational most times? 3. Leverage (h sub i) what is the significance of it? What does it "tell us" as values change?

"cubic or square transformations must include original X, don't do this for Y"

The transformations of the X and Y started to feel really abstract and kinda confusing

the relationship between what we're learning about models and how we'll actually apply that knowledge to a figure in a report, for example

I understand the reasoning for transforming to make the data to fit the LINE assumptions, but if it makes it hard to interpret, why do we do it?

#### Hi and Hat metrics and not knowing the magnitude or reason for it was confusing.

<https://online.stat.psu.edu/stat501/lesson/11/11.2>

#### what are some other real life examples of influential points besides human error. Can they appear more organically

I'm a little confused in the section about the power ladder -- we're supposed to be looking at the skew of the distribution of the residuals, but the examples shown were of different distributions (x alone, y alone, and x vs y). What should we be looking at to determine what transform, if any, to use?

I'm not super clear on why transformations are even ok to do if they fundamentally change the shape of the data. You had a good sentence right at the end (second to last slide?) -- "for every change in x, there's a (...) change in longevity squared" or something like that? I think it'd be helpful to repeat or elaborate on that.

I'm still not very clear on how to identify outliers vs high leveraged data points by looking at a plot alone.

#### What is the reasoning behind why we usually want to transform the independent variable instead of the dependent?

This is more about interpretations in multiple linear models. We can have a model with multiple variables as covariates (so multiple X's on the right side of the equation). If we transform Y, then all the interpretations with every covariate changes. If we can fit model assumptions better with a transformation to one X, then we only change one interpretation!

+-------------------------------------------------------------------------+
| \                                                                       |
| In the Tukey's power ladder, is log(x) mean log10(x) or natural log(x)? |
+-------------------------------------------------------------------------+

#### Extra materials with examples of transformations

<https://www.youtube.com/watch?v=HIcqQhn3vSM&ab_channel=jbstatistics>

<https://online.stat.psu.edu/stat501/lesson/9>
