---
title: "Week 7"
description: "Interactions continued"
date: "2/19/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #213c96;
  background-color: #fff;
  padding: 10px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #213c96;
  padding: 10px;
}
```

::: callout-important
## Room Locations for the week

-   On Monday, 2/19,        we do NOT have class (President's Day)
-   On Wednesday, 2/14,  we will be in **RLSB 3A003 A**
:::

## Resources

On Wednesday, 2/21, we will continue to look at the Interactions slides.

+--------+--------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lesson | Topic        | Slides                                                                                               | Annotated Slides                                                                                                            | Recording                                                                                                                                                                                                                                                                                                                                                                            |
+========+==============+:====================================================================================================:+:===========================================================================================================================:+:====================================================================================================================================================================================================================================================================================================================================================================================:+
| 11     | Interactions | [[{{< iconify ri slideshow-fill size=30px >}}](/slides/11_Interactions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/slides_annotated/11_Interactions.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F11%5FInteractions%5F1%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"} |
|        |              |                                                                                                      |                                                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                      |
|        |              |                                                                                                      |                                                                                                                             | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/personal/wakim_ohsu_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fwakim%5Fohsu%5Fedu%2FDocuments%2FTeaching%2FClasses%2FW2024%5FBSTA%5F512%5F612%2FStudent%5Ffiles%2FRecordings%2F11%5FInteractions%5F2%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)]{style="color:#f8f5f0;"} |
+--------+--------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## On the Horizon

-   HW 4 is due on Sunday (2/25)

-   Lab 3 is due Sunday (3/3)

## Class Exit Tickets

[[{{< iconify healthicons health-worker-form-negative size=30px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNkRFSU9CNVBYWUZIMDcxQTkzM09VWFhaRi4u)]{style="color:#f8f5f0;"} Wednesday (2/21)

## Announcements

### Wednesday 2/21

-   My office hours tomorrow are from 11am - 12pm

    -   I have a faculty meeting at 12pm

-   HW 4 is due on Sunday (2/25)

-   Lab 3 is due Sunday (3/3)

-   Next week is virtual!!

## Muddiest Points

### 1. Interactions in general

#### 1.1 Why is it not an effect modifier if p-value is 0.4? Or why is it not significant? Is it because it is not = 0?

#### 1.2 What are some reasons why we would think an effect modifier might exist in our data? or are we testing indiscriminately/ based on our own perspective of the associations in the data

#### 1.3 I'm still not entirely sure I know how to do all the steps of interaction models, but I think part of that may just be me needing to look at my previous notes.

### 2. Centering the continuous covariate

#### 2.1 How does centering help with interpretation?

I think [this blog post](https://www.theanalysisfactor.com/when-not-to-center-a-predictor-variable-in-regression/) has a nice explanation.

But for an example from our class... centering female literacy rate can help us interpret the

#### 2.2 Why do some values of $\beta$ change after centering the mean and others don't?

```{r}
#| echo: false

g=3
```
