---
title: "Chapter 10: Expected Values of Discrete RVs"
author: "Meike Niederhausen and Nicky Wakim"
date: "10/16/2023"
categories: ["Week 4"]
title-slide-attributes:
    data-background-color: "#006a4e"
format: 
  revealjs:
    theme: [default, simple_NW.scss]
    toc: true
    chalkboard: true
    slide-number: true
    show-slide-number: all
    width: 1955
    height: 1100
    footer: Chapter 10 Slides
---

## Learning Objectives

## Our good and fair friend, the 6-sided die

::: columns
::: {.column width="40%"}
::: example
::: ex-title
Example 1
:::

::: ex-cont
Suppose you roll a fair 6-sided die. What value do you expect to get?
:::
:::
:::
:::

## Our good and not-so-fair friend, the 6-sided die

::: columns
::: {.column width="40%"}
::: example
::: ex-title
Example 2
:::

::: ex-cont
Suppose the die is 6-sided, but not fair. What value do you expect to get on a roll?
:::
:::
:::
:::

## Quick remark on expected values

-   Let's think about expected values vs. actual outcomes
-   Expected values are not necessarily an actual outcome
    -   It could be that our expected value is not in the sample space ($E(X) \notin S$)

## What is an expected value?

::: definition
::: def-title
Definition: Expected value
:::

::: def-cont
The **expected value** of a discrete r.v. $X$ that takes on values $x_1, x_2, \ldots, x_n$ is $$\mathbb{E}[X] = \sum_{i=1}^n x_ip_X(x_i).$$
:::
:::

## Remarks on the expected value

-   The definition holds if the r.v. $X$ takes on countably infinitely many values $x_1, x_2, \ldots$, as well: $$\mathbb{E}[X] = \sum_{i=1}^{\infty} x_ip_X(x_i).$$

-   Another way to define the expected value of a discrete r.v. is to do so at the $\omega$ level, where the $\omega$'s are outcomes in the sample space:

    -   Suppose $\omega_1, \omega_2, \ldots, \omega_n$ are the possible outcomes of a random phenomenon. If outcome $\omega_i$ causes the r.v. X to take on value $x_i$ (meaning $X(\omega_i)=x_i$), then $$\mathbb{E}[X] = \sum_{i=1}^{\infty} x_i\mathbb{P}(\{\omega_i\}).$$

## Expected value of a Bernoulli distribution

::: columns
::: {.column width="50%"}
::: example
::: ex-title
Example 3
:::

::: ex-cont
Suppose $$X = \left\{
        \begin{array}{ll}
            1 & \quad \mathrm{with\ probability}\ p \quad\mathrm{(success)}\\
            0 & \quad \mathrm{with\ probability}\ 1-p \quad\mathrm{(failure)}
        \end{array}
    \right.$$ Find the expected value of $X$.
:::
:::
:::
:::


## Let's slightly change our random variable

::: columns
::: {.column width="40%"}
::: example
::: ex-title
Example 5
:::

::: ex-cont
*Suppose* $$X = \left\{
        \begin{array}{ll}
            1 & \quad \mathrm{with\ probability}\ p \\
            -1 & \quad \mathrm{with\ probability}\ 1-p 
        \end{array}
    \right.$$ Find the expected value of $X$.
:::
:::
:::
:::

## Bullseye! 🎯

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 5
:::

::: ex-cont
Suppose I throw darts at a dartboard until I hit the bullseye, and that my probability of hitting the bullseye is $p$. Suppose further that all of my throws are independent, and that the probability of a bullseye never changes, no matter how many times I throw a dart. How many times should I expect to have to throw the dart until I hit the bullseye?

:::
:::
:::
:::

## Ghost! 👻

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 6
:::

::: ex-cont
A ghost is trick-or-treating. It comes to a house where it is known that there are 30 candies in the bag and only one is a watermelon Jolly Rancher, which is the ghost's favorite. The ghost takes pieces of candy without replacement until it gets the watermelon Jolly Rancher. How many pieces of candy do we expect the ghost to take?
:::
:::
:::
:::

## Some remarks on last two examples

Both examples are repeated random processes. They are fundamentally different though:

-   The bullseye example is "*with replacement*" since the probability of success remains constant.

-   The ghost trick-or-treating example is *without replacement*, and thus the probability of success changes with each trial.
