---
title: "Chapter 1: Outcomes, Events, and Sample Spaces"
author: "Meike Niederhausen"
title-slide-attributes:
    data-background-color: "#006a4e"
date: "09/25/2023"
categories: ["Week 1", "Day 1"]
format: 
  revealjs:
    theme: [default, simple_NW.scss]
    toc: true
    toc-depth: 1
    toc-title: Class Overview
    chalkboard: true
    slide-number: true
    show-slide-number: all
    width: 1600
    height: 1100
    footer: Chapter 1 Slides
---

# Tossing One Coin (Outcomes, Events, and Sample Space)

## Coin Toss Example: 1 coin (1/3)

**Suppose you toss one coin.**

-   What are the possible outcomes?

     

-   What is the sample space?

     

-   What are the possible events?

## Coin Toss Example: 1 coin (2/3)

**Suppose you toss one coin.**

-   What are the possible outcomes?

    -   Heads ($H$)

    -   Tails ($T$)

    **Note:** When something happens at random, such as a coin toss, there are several possible outcomes, and *exactly one* of the outcomes will occur.

## Coin Toss Example: 1 coin (3/3)

::: columns
::: {.column width="35%"}
::: definition
::: def-title
Definition: Sample Space
:::

::: def-cont
The **sample space** $S$ is the set of *all* possible outcomes.
:::
:::

::: definition
::: def-title
Definition: Event
:::

::: def-cont
An **event** is a collection of *some* possible outcomes.
:::
:::
:::

::: {.column width="65%"}
-   What is the sample space?

    -   $S = \{H, T\}$

-   What are the possible events?

    -   $\{H\}$

    -   $\{T\}$

    -   $\{H, T\}$

    -   $\emptyset$

     

    When thinking about events, think about outcomes that you might be asking the probability of.
:::
:::

# Tossing Two Coins (Outcomes, Events, and Sample Space)

## Coin Toss Example: 2 coins

**Suppose you toss two coins.**

-   What is the sample space? *Assume the coins are distinguishable*

    -   $S =$ $$S = \{HH, TT, HT, TH\}$$

-   What are some possible events?

    -   $A$ = exactly one $H$ = $\{HT, TH\}$

    -   $B$ = at least one $H$ = $\{HH, HT, TH\}$

    -   

    -   

## More info on events and sample spaces

-   We usually use capital letters from the beginning of the alphabet to denote events. However, other letters might be chosen to be more descriptive.

-   We use the notation $|S|$ to denote the **size** of the sample space.

-   The total number of possible events is $2^{|S|}$, which is the total number of possible subsets of $S$. We will prove this later in the course.

-   The **empty set**, denoted by $\emptyset$, is the set containing no outcomes.

## Example: Keep sampling until...

**Suppose you keep sampling people until you have someone with high blood pressure (BP). What is the sample space?**

-   Let $H =$ denote someone with high BP.

-   Let $H^C =$ denote someone with not high blood pressure, such as low or regular BP.

-   Then, $S =$

$$S = \{H, (H, H^C), (H, H, H^C), (H, H, H, H^C), \ldots$$

# Set Theory

## Set Theory (1/2)

::: columns
::: column
::: definition
::: def-title
Definition: Union
:::

::: def-cont
The **union** of events $A$ and $B$, denoted by $A \cup B$, contains all outcomes that are in $A$ *or* $B$.
:::
:::

::: definition
::: def-title
Definition: Intersection
:::

::: def-cont
The **intersection** of events $A$ and $B$, denoted by $A \cap B$, contains all outcomes that are both in $A$ *and* $B$.
:::
:::
:::

::: column
Venn diagrams
:::
:::

## Set Theory (2/2)

::: columns
::: column
::: definition
::: def-title
Definition: Complement
:::

::: def-cont
The **complement** of event $A$, denoted by $A^C$ or $A'$, contains all outcomes in the sample space $S$ that are *not* in $A$ .
:::
:::

::: definition
::: def-title
Definition: Mutually Exclusive
:::

::: def-cont
Events $A$ and $B$ are **mutually exclusive**, or disjoint, if they have no outcomes in common. In this case $A \cap B = \emptyset$, where $\emptyset$ is the empty set.
:::
:::
:::

::: column
Venn diagrams
:::
:::

## BP example variation (1/3)

-   Suppose you have $n$ subjects in a study.

-   Let $H_i$ be the event that person $i$ has high BP, for $i=1\ldots n$.

Use set theory notation to denote the following events:

1.  Event subject $i$ does not have high BP

2.  Event all $n$ subjects have high BP

3.  Event at least one subject has high BP

4.  Event all of them do not have high BP

5.  Event at least one subject does not have high BP

## BP example variation (2/3)

-   Suppose you have $n$ subjects in a study.

-   Let $H_i$ be the event that person $i$ has high BP, for $i=1\ldots n$.

Use set theory notation to denote the following events:

1.  Event subject $i$ does not have high BP

    $$H_i^C$$

2.  Event all $n$ subjects have high BP

    $$H_1 \textrm{ and } H_2 \textrm{ and } \ldots = \bigcap\limits_{i=1}^{n}H_i$$

3.  Event at least one subject has high BP

    $$H_1 \textrm{ or } H_2 \textrm{ or } \ldots = \bigcup\limits_{i=1}^{n}H_i$$

## BP example variation (3/3)

4.  Event all of them do not have high BP

    $H_1^C$ and $H_2^C$ and\... $$\bigcap\limits_{i=1}^{n}H_i^C = \Big(\bigcup\limits_{i=1}^{n}H_i\Big)^C$$ = complement of at least one person having high BP

5.  Event at least one subject does not have high BP

    $H_1^C$ or $H_2^C$ or\... $$\bigcup\limits_{i=1}^{n}H_i^C = \Big(\bigcap\limits_{i=1}^{n}H_i\Big)^C$$ = complement of all having high BP

## De Morgan's Laws

::: theorem
::: thm-title
Theorem: De Morgan's 1st Law
:::

::: thm-cont
For a collection of events (sets) $A_1, A_2, A_3, \ldots$

$$\bigcap\limits_{i=1}^{n}A_i^C = \Big(\bigcup\limits_{i=1}^{n}A_i\Big)^C$$
:::
:::

"all not A = $($at least one event A$)^C$"

::: theorem
::: thm-title
Theorem: De Morgan's 2nd Law
:::

::: thm-cont
For a collection of events (sets) $A_1, A_2, A_3, \ldots$

$$\bigcup\limits_{i=1}^{n}A_i^C = \Big(\bigcap\limits_{i=1}^{n}A_i\Big)^C$$
:::
:::

"at least one event not A = $($all A$)^C$"

## Remarks on De Morgan's Laws

-   These laws also hold for infinite collections of events.

-   Draw Venn diagrams to convince yourself that these are true!

-   These laws are *very* useful when calculating probabilities.

    -   This is because calculating the probability of the intersection of events is often much easier than the union of events.

    -   This is not obvious right now, but we will see in the coming chapters why.
