---
title: "Chapter 22: Counting"
author: "Meike Niederhausen"
date: "09/27/2023"
categories: ["Day 2"]
format: 
  revealjs:
    theme: [default, simple_NW.scss]
    toc: true
    chalkboard: true
    slide-number: true
    show-slide-number: all
    width: 1600
    height: 1100
    footer: Chapter 22 Slides
---

# Basic Counting Examples

## Basic Counting Examples (1/3)

::: example
::: ex-title
Example 1
:::

::: ex-cont
Suppose we have 10 (distinguishable) subjects for study.

1.  How many possible ways are there to order them?

2.  How many ways to order them if we can reuse the same subject and

    -   need 10 total?

    -   need 6 total?

3.  How many ways to order them if without replacements and only need 6?

4.  How many ways to choose 6 subjects without replacement if the order doesn't matter?
:::
:::

## Basic Counting Examples (2/3)

Suppose we have 10 (distinguishable) subjects for study.

::: example
::: ex-title
Example 1.1
:::

::: ex-cont
How many possible ways are there to order them?
:::
:::

$10!$


::: example
::: ex-title
Example 1.2
:::

::: ex-cont
How many ways to order them if we can reuse the same subject and

-   need 10 total?

-   need 6 total?
:::
:::

1.  need 10 total?

    -   $10^{10}$

2.  need 6 total?

    -   $10^6$


## Basic Counting Examples (3/3)

Suppose we have 10 (distinguishable) subjects for study.

::: example
::: ex-title
Example 1.3
:::

::: ex-cont
How many ways to order them if without replacements and only need 6?
:::
:::

$$\frac{10!}{4!}=151,200$$


::: example
::: ex-title
Example 1.4
:::

::: ex-cont
How many ways to choose 6 subjects without replacement if the order doesn't matter?
:::
:::

$$\frac{\frac{10!}{4!}}{6!} = \frac{10!}{4!6!}=210$$

There are $6!$ ways to order the 6 subjects.

# Permutations and Combinations

## Permutations and Combinations

::: definition
::: def-title
Definition: Permutations
:::

::: def-cont
**Permutations** are the number of ways to arrange in order $r$ distinct objects when there are $n$ total.

$$nPr = \frac{n!}{(n-r)!}$$
:::
:::

::: definition
::: def-title
Definition: Combinations
:::

::: def-cont
**Combinations** are the number of ways to choose (order doesn't matter) $r$ objects from $n$ without replacement.

$$nCr = \textrm{"n choose r"} = \binom{n}{r} = \frac{n!}{r!(n-r)!}$$
:::
:::

## Some combinations properties

-   $$\binom{n}{r} = \binom{n}{n-r}$$

-   $$\binom{n}{1} = n$$

-   $$\binom{n}{0} = 1$$

# More Examples: order matters vs. not

## More examples: order matters vs. not (1/2)

::: example
::: ex-title
Example 2
:::

::: ex-cont
Suppose we draw 2 cards from a standard deck without replacement. What is the probability that both are spades when

1.  order matters?

2.  order doesn't matter?
:::
:::

## More examples: order matters vs. not (2/2)

Suppose we draw 2 cards from a standard deck without replacement. What is the probability that both are spades when

1.  order matters?

    -   $$\frac{13P2}{52P2} = \frac{\frac{13!}{11!}}{\frac{52!}{50!}} = \frac{13\cdot12}{52\cdot51}$$

2.  order doesn't matter?

    -   $$\frac{\binom{13}{2}}{\binom{52}{2}} = \frac{\frac{13!}{2!11!}}{\frac{52!}{2!50!}} = \frac{13\cdot12}{52\cdot51}$$

## Table of different cases

See table on pg. 277 of textbook

-   $n$ = total number of objects

-   $r$ = number objects needed

    |                          | with replacement   | without replacement                        |
    |-------------------:|------------------------|:---------------------------|
    |        **order matters** | $n^r$              | $nPr = \frac{n!}{(n-r)!}$                  |
    | **order doesn't matter** | $\binom{n+r-1}{r}$ | $nCr = \binom{n}{r} = \frac{n!}{r!(n-r)!}$ |
