---
title: "Chapter 2: Probability"
author: "Meike Niederhausen"
date: "09/25/2023"
categories: ["Day 1"]
format: 
  revealjs:
    theme: [default, simple_NW.scss]
    toc: true
    chalkboard: true
    slide-number: true
    show-slide-number: all
    width: 1600
    height: 1100
    footer: Chapter 2 Slides
---

## Overview

## What do you know about probabilities?

# Probabilities of equally likely events

## Probabilities of equally likely events (1/2)

::: example
::: ex-title
Example 1
:::

::: ex-cont
Suppose you have a regular well-shuffled deck of cards. What's the probability of drawing:

1.  any heart

2.  the queen of hearts

3.  any queen

**Solution:**

1.  any heart = 13/52 = 1/4

2.  the queen of hearts = 1/52

3.  any queen = 4/52 = 1/13
:::
:::

## Probabilities of equally likely events (2/2)

If $S$ is a finite sample space, with equally likely outcomes, then

$$\mathbb{P}(A) = \frac{|A|}{|S|}.$$

## A probability is a function...

$\mathbb{P}(A)$ is a function with

-   input: event $A$ from the sample space $S$, ($A \subseteq S$)

-   output: a number between 0 and 1 (inclusive)

$$\mathbb{P}(A): S \rightarrow [0,1]$$

A function that follows some specific rules though!

See Probability Axioms on next slide.

# Probability Axioms

## Probability Axioms

::: axiom
::: axiom-title
Axiom 1
:::

::: axiom-cont
For every event $A$, $0\leq\mathbb{P}(A)\leq 1$.
:::
:::

::: axiom
::: axiom-title
Axiom 2
:::

::: axiom-cont
For the sample space $S$, $\mathbb{P}(S)=1$.
:::
:::

::: axiom
::: axiom-title
Axiom 3
:::

::: axiom-cont
If $A_1, A_2, A_3, \ldots$, is a collection of **disjoint** events, then $$\mathbb{P}\Big( \bigcup \limits_{i=1}^{\infty}A_i\Big) =  \sum_{i=1}^{\infty}\mathbb{P}(A_i).$$
:::
:::

# Some probability properties

## Some probability properties

Using the Axioms, we can prove all other probability properties!

::: columns
::: column
::: proposition
::: prop-title
Proposition 1
:::

::: prop-cont
For any event $A$, $\mathbb{P}(A)= 1 - \mathbb{P}(A^C)$
:::
:::

::: proposition
::: prop-title
Proposition 2
:::

::: prop-cont
$\mathbb{P}(\emptyset)=0$
:::
:::

::: proposition
::: prop-title
Proposition 3
:::

::: prop-cont
If $A \subseteq B$, then $\mathbb{P}(A) \leq \mathbb{P}(B)$
:::
:::
:::

::: column
::: proposition
::: prop-title
Proposition 4
:::

::: prop-cont
$\mathbb{P}(A \cup B) = \mathbb{P}(A) + \mathbb{P}(B) - \mathbb{P}(A \cap B)$
:::
:::

::: proposition
::: prop-title
Proposition 5
:::

::: prop-cont
$\mathbb{P}(A \cup B \cup C) = \mathbb{P}(A) + \mathbb{P}(B) + \\ \mathbb{P}(C) - \mathbb{P}(A \cap B) - \mathbb{P}(A \cap C) - \\ \mathbb{P}(B \cap C) + \mathbb{P}(A \cap B \cap C)$
:::
:::
:::
:::

## Proposition 1 Proof

::: proposition
::: prop-title
Proposition 1
:::

::: prop-cont
For any event $A$, $\mathbb{P}(A)= 1 - \mathbb{P}(A^C)$
:::
:::

::: proof1
::: proof-title
Proposition 1 Proof
:::

::: proof-cont
Since $A$ and $A^C$ are disjoint, we know from Axiom 3 that $\mathbb{P}(A \cup A^C) = \mathbb{P}(A) + \mathbb{P}(A^C)$.

However, $S = A \cup A^C$, and by Axiom 2, $\mathbb{P}(S) = 1$, implying $\mathbb{P}(A \cup A^C) = \mathbb{P}(S) = 1$.

Thus, $\mathbb{P}(A) + \mathbb{P}(A^C) = 1$, or $\mathbb{P}(A) = 1 - \mathbb{P}(A^C)$
:::
:::

## Proposition 2 Proof

::: proposition
::: prop-title
Proposition 2
:::

::: prop-cont
$\mathbb{P}(\emptyset)=0$
:::
:::

::: proof1
::: proof-title
Proposition 2 Proof (different from book)
:::

::: proof-cont
We know $\emptyset = S^C$.

Thus by Prop 1,

$$\mathbb{P}(\emptyset) = \mathbb{P}(S^C) = 1- \mathbb{P}(S) = 1-1 =0
.$$
:::
:::

## Proposition 3 Proof

::: proposition
::: prop-title
Proposition 3
:::

::: prop-cont
If $A \subseteq B$, then $\mathbb{P}(A) \leq \mathbb{P}(B)$
:::
:::

::: proof1
::: proof-title
Proposition 3 Proof
:::

::: proof-cont
Create a partition! Make a Venn diagram.

$$%\left(
\begin{array}{ccl}
B &=& A \cup (B \cap A^C) \\
\mathbb{P}(B) &=& \mathbb{P}(A) + \mathbb{P}(B \cap A^C) \\
\mathbb{P}(B)  & \geq &   \mathbb{P}(A),
\end{array}
%\right)$$ since $\mathbb{P}(B \cap A^C) \geq 0$.
:::
:::

# Partitions

## Partitions

::: definition
::: def-title
Definition: Partition
:::

::: def-cont
A set of events $\{A_i\}_{i=1}^{n}$ create a **partition** of $A$, if

-   the $A_i$'s are disjoint (mutually exclusive) and

-   $\bigcup \limits_{i=1}^n A_i = A$
:::
:::

::: example
::: ex-title
Example 2
:::

::: ex-cont
-   If $A \subset B$, then $\{A, B \cap A^C\}$ is a partition of $B$.

-   If $S = \bigcup \limits_{i=1}^n A_i$, then the $A_i$'s are a partition of the sample space.
:::
:::

Creating partitions is sometimes used to help calculate probabilities, since by Axiom 3 we can add the probabilities of disjoint events.

# Venn Diagram Probabilities

## Venn Diagram Probabilities

::: columns
::: example
::: ex-title
Example 3
:::

::: ex-cont
If a subject has an

-   80% chance of taking their medication *this* week,

-   70% chance of taking their medication *next* week, and

-   10% chance of *not* taking their medication *either* week,

then find the probability of them taking their medication exactly one of the two weeks.
:::
:::

*Hint: Draw a Venn diagram labelling each of the parts to find the probability.*

Answer: $\mathbb{P}(A \cap B) = 0.6$.
:::
