# Chapter 36: Sums of Independent Normal Random Variables {#chapter-36-sums-of-independent-normal-random-variables .unnumbered}

::: theorem
**Theorem 1**. *  Let $X\sim N(\mu, \sigma^2)$, and let $Y=aX+b$, where
$a$ and $b$ are constants. Then $$\hspace{-12cm} Y \sim$$*
:::

::: proof
*Proof.* ◻
:::

------------------------------------------------------------------------

::: theorem
**Theorem 2**. *  Let $X_i \sim N(\mu_i, \sigma_i^2)$ be independent
normal rv's, for $i=1,2,\ldots,n$. Then
$$\hspace{-12cm} \sum_{i=1}^n X_i \sim$$*
:::

::: proof
*Proof.* ◻
:::

------------------------------------------------------------------------

**Special Cases**

1.  Let $X_i \sim N(\mu, \sigma^2)$ be iid normal rv's, for
    $i=1,2,\ldots,n$. Then $$\hspace{-12cm} \sum_{i=1}^n X_i \sim$$

2.  Let $X_i \sim N(\mu, \sigma^2)$ be iid normal rv's, for
    $i=1,2,\ldots,n$. Then
    $$\hspace{-12cm} \bar{X}=\frac{\sum_{i=1}^n X_i}{n} \sim$$

3.  Let $X\sim N(\mu_X,\sigma_X^2)$, and $Y\sim N(\mu_Y,\sigma_Y^2)$.
    Then $$\hspace{-12cm} X-Y \sim$$

    ::: proof
    *Proof.* ◻
    :::

::: example
**Example 3**. *  Glaucoma is an eye disease that is manifested by high
intraocular pressure (IOP). The distribution of IOP in the general
population is approximately normal with mean 16 mmHg and standard
deviation 3 mmHg.*

1.  *Suppose a patient has 40 IOP readings. What is the probability that
    their average reading is greater than 20.32 mmHg, assuming their
    eyes are healthy?*

2.  *Repeat the previous question for a patient with 10 IOP readings.*
:::
