---
title: "Week 2"
description: "Independent Events; Conditional Probability; and Bayes' Theorem"
date: "09/25/2023"
date-modified: "08/22/2023"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #006a4e;
  background-color: #fff;
  padding: 10px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #006a4e;
  padding: 10px;
}
```

## Resources

Below is a table with links to resources. Icons in [orange]{style="color:#E25D3B;"} mean there is an available file link.

| Chapter | Topic                   |                                                      Slides                                                      |                                  Annotated Slides                                  |                           Recording                           |
|---------------|---------------|:-------------:|:-------------:|:-------------:|
| 3       | Independent Events      |    [[{{< iconify ri slideshow-fill size=30px >}}](../slides/3_IndependentEvents.qmd)]{style="color:#49A3D1;"}    | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |
| 4       | Conditional Probability | [[{{< iconify ri slideshow-fill size=30px >}}](../slides/4_Conditional_Probability.qmd)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |
| 6       | Bayes' Theorem          |       [[{{< iconify ri slideshow-fill size=30px >}}](/slides/5_Bayes_Theorem.qmd)]{style="color:#f8f5f0;"}       | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |

For the slides, once they are opened, if you would like to print or save them as a PDF, the best way to do this is:

1.  Click on the icon with three horizontal bars on the bottom left of the browser.

2.  Click on "Tools" with the gear icon at the top of the sidebar.

3.  Click on "PDF Export Mode."

4.  From there, you can print or save the PDF as you would normally from your internet browser.

## On the Horizon

[Homework 1 due 10/5](../homework/HW1.qmd)

## Class Exit Tickets

|                  |                                                                                             |
|------------------|------------------------------------------------------|
| Monday (10/2)    | [{{< iconify healthicons health-worker-form-negative size=30px >}}]{style="color:#f8f5f0;"} |
| Wednesday (10/4) | [{{< iconify healthicons health-worker-form-negative size=30px >}}]{style="color:#f8f5f0;"} |

: {tbl-colwidths="\[30,70\]"}

## Additional Information

## Statistician of the Week:

```{r}
#| echo: false
g=3
```

## Muddiest Points

This will be filled in with your Exit Ticket responses.

## Clearest Points

This will be filled in with your Exit Ticket responses.
