{
  "hash": "5791b56fbc05118ea1a5392d9136fdc0",
  "result": {
    "markdown": "---\ntitle: \"SLR: Inference and Prediction\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#213c96\"\ndate: \"01/17/2023\"\ncategories: [\"Week 1\"]\nformat: \n  revealjs:\n    theme: [default, simple_NW.scss]\n    toc: true\n    toc-depth: 1\n    toc-title: Class Overview\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: SLR 1\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm <- read_csv(\"data/lifeexp_femlit_2011.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit regression model:\nmodel1 <- lm(life_expectancy_years_2011 ~ female_literacy_rate_2011,\n             data = gapm)\n\n# some output, but not complete\nmodel1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = life_expectancy_years_2011 ~ female_literacy_rate_2011, \n    data = gapm)\n\nCoefficients:\n              (Intercept)  female_literacy_rate_2011  \n                  50.9279                     0.2322  \n```\n:::\n:::\n\n\n## vfknmbv\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = life_expectancy_years_2011 ~ female_literacy_rate_2011, \n    data = gapm)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-22.299  -2.670   1.145   4.114   9.498 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               50.92790    2.66041  19.143  < 2e-16 ***\nfemale_literacy_rate_2011  0.23220    0.03148   7.377  1.5e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.142 on 78 degrees of freedom\n  (108 observations deleted due to missingness)\nMultiple R-squared:  0.4109,\tAdjusted R-squared:  0.4034 \nF-statistic: 54.41 on 1 and 78 DF,  p-value: 1.501e-10\n```\n:::\n\n```{.r .cell-code}\n# Regression table:\n# library(broom)  # for tidy() command\n# library(gt)  # for gt() command\ntidy(model1) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"gsmhmrbeac\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gsmhmrbeac table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gsmhmrbeac thead, #gsmhmrbeac tbody, #gsmhmrbeac tfoot, #gsmhmrbeac tr, #gsmhmrbeac td, #gsmhmrbeac th {\n  border-style: none;\n}\n\n#gsmhmrbeac p {\n  margin: 0;\n  padding: 0;\n}\n\n#gsmhmrbeac .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gsmhmrbeac .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gsmhmrbeac .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gsmhmrbeac .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gsmhmrbeac .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gsmhmrbeac .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gsmhmrbeac .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gsmhmrbeac .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gsmhmrbeac .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gsmhmrbeac .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gsmhmrbeac .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gsmhmrbeac .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gsmhmrbeac .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gsmhmrbeac .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gsmhmrbeac .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsmhmrbeac .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gsmhmrbeac .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gsmhmrbeac .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gsmhmrbeac .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsmhmrbeac .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gsmhmrbeac .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsmhmrbeac .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gsmhmrbeac .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsmhmrbeac .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gsmhmrbeac .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsmhmrbeac .gt_left {\n  text-align: left;\n}\n\n#gsmhmrbeac .gt_center {\n  text-align: center;\n}\n\n#gsmhmrbeac .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gsmhmrbeac .gt_font_normal {\n  font-weight: normal;\n}\n\n#gsmhmrbeac .gt_font_bold {\n  font-weight: bold;\n}\n\n#gsmhmrbeac .gt_font_italic {\n  font-style: italic;\n}\n\n#gsmhmrbeac .gt_super {\n  font-size: 65%;\n}\n\n#gsmhmrbeac .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gsmhmrbeac .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gsmhmrbeac .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gsmhmrbeac .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gsmhmrbeac .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gsmhmrbeac .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gsmhmrbeac .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n# Learning Objectives\n\n1.  Estimate the variance?\n1.  Inference for population [**slope**]{style=\"color:green\"} $\\beta_1$\n2.  CI for mean response $\\mu_{Y|x^*}$\n3.  Prediction interval for predicting **individual** observations\n\n## Topics\n\nDay 3: slide 13-end\n\n-   Inference for slope and intercept\n\n    -   CI’s and hypothesis tests\n\n-   Inference for mean value of y at specific values of x\n\n    -   Confidence bands of best-fit line\n\n-   Inference for the estimated variance???\n\n-   Prediction intervals for individual predictions\n\n    -   Prediction bands\n\n\n# Regression inference\n\n1.  Inference for population [**slope**]{style=\"color:green\"} $\\beta_1$\n2.  CI for mean response $\\mu_{Y|x^*}$\n3.  Prediction interval for predicting **individual** observations\n\n## $\\widehat\\sigma^2$: Needed ingredient for inference\n\n* Recall that the *variance* of the errors (residuals) is estimated by $\\widehat{\\sigma}^2$:\n\n$$\\widehat{\\sigma}^2 = S_{y|x}^2= \\frac{1}{n-2}\\sum_{i=1}^n (y_i - \\widehat{y}_i)^2 =\\frac{1}{n-2}SSE = MSE$$\n* The *standard deviation* $\\widehat{\\sigma}$ is given in the R output as the `Residual standard error`, \n    * $4^{th}$ line from the bottom in the `summary()` output of the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = life_expectancy_years_2011 ~ female_literacy_rate_2011, \n    data = gapm)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-22.299  -2.670   1.145   4.114   9.498 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               50.92790    2.66041  19.143  < 2e-16 ***\nfemale_literacy_rate_2011  0.23220    0.03148   7.377  1.5e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.142 on 78 degrees of freedom\n  (108 observations deleted due to missingness)\nMultiple R-squared:  0.4109,\tAdjusted R-squared:  0.4034 \nF-statistic: 54.41 on 1 and 78 DF,  p-value: 1.501e-10\n```\n:::\n\n```{.r .cell-code}\n# number of observations (pairs of data) used to run the model\nnobs(model1) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n:::\n\n\n* Using the `Residual standard error`, we can calculate the SSE:\n\n$$\\widehat{\\sigma}^2 = \\frac{1}{n-2}SSE\\\\\n6.142^2 = \\frac{1}{80-2}SSE\\\\\nSSE = 78 \\cdot 6.142^2 = 2942.484792 $$\n\n* 2942.484792 is the smallest sums of squares of all possible regression lines through the data. \n\n## Inference for population [**slope**]{style=\"color:green\"} $\\beta_1$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit regression model:\nmodel1 <- lm(life_expectancy_years_2011 ~ female_literacy_rate_2011,\n                 data = gapm)\n# Get regression table:\ntidy(model1, conf.int = TRUE) %>% gt() # conf.int = TRUE part is new! \n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"krwvjilmxn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#krwvjilmxn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#krwvjilmxn thead, #krwvjilmxn tbody, #krwvjilmxn tfoot, #krwvjilmxn tr, #krwvjilmxn td, #krwvjilmxn th {\n  border-style: none;\n}\n\n#krwvjilmxn p {\n  margin: 0;\n  padding: 0;\n}\n\n#krwvjilmxn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#krwvjilmxn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#krwvjilmxn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#krwvjilmxn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#krwvjilmxn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#krwvjilmxn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#krwvjilmxn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#krwvjilmxn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#krwvjilmxn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#krwvjilmxn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#krwvjilmxn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#krwvjilmxn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#krwvjilmxn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#krwvjilmxn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#krwvjilmxn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#krwvjilmxn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#krwvjilmxn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#krwvjilmxn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#krwvjilmxn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#krwvjilmxn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#krwvjilmxn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#krwvjilmxn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#krwvjilmxn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#krwvjilmxn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#krwvjilmxn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#krwvjilmxn .gt_left {\n  text-align: left;\n}\n\n#krwvjilmxn .gt_center {\n  text-align: center;\n}\n\n#krwvjilmxn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#krwvjilmxn .gt_font_normal {\n  font-weight: normal;\n}\n\n#krwvjilmxn .gt_font_bold {\n  font-weight: bold;\n}\n\n#krwvjilmxn .gt_font_italic {\n  font-style: italic;\n}\n\n#krwvjilmxn .gt_super {\n  font-size: 65%;\n}\n\n#krwvjilmxn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#krwvjilmxn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#krwvjilmxn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#krwvjilmxn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#krwvjilmxn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#krwvjilmxn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#krwvjilmxn .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">45.6314348</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">56.2243615</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.1695284</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.2948619</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n```{=tex}\n\\begin{align}\n\\widehat{y} =& b_0 + b_1 \\cdot x\\\\\n\\widehat{\\text{life expectancy}} =& 50.9 + 0.232 \\cdot \\text{female literacy rate}\n\\end{align}\n```\n\n-   What are $H_0$ and $H_A$?\n-   How do we calculate the standard error, statistic, *p*-value, and\n    CI?\n\n::: callout-note\n-   We can also test & calculate CI for the population intercept\n-   This will be covered in BSTA 512\n:::\n\n## Inference for the population [**slope**]{style=\"color:green\"}: CI and hypothesis test\n\n::: columns\n::: {.column width=\"50%\"}\n**Population model**\\\n*line + random \"noise\"*\n\n$$Y = \\beta_0 + \\beta_1 \\cdot X + \\varepsilon$$ with\n$\\varepsilon \\sim N(0,\\sigma)$\\\n$\\sigma$ is the variability (SD) of the residuals\n\n<br>\n\n**Sample best-fit (least-squares) line:**\n\n$$\\widehat{y} = b_0 + b_1 \\cdot x $$\n\nNote: Some sources use $\\widehat{\\beta}$ instead of $b$.\n:::\n\n::: {.column width=\"50%\"}\n-   Construct a **95% confidence interval** for the **population slope**\n    $\\beta_1$\n\n<br>\n\n-   Conduct the **hypothesis test**\n\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n```\n\n<br>\n\n*Note: R reports p-values for 2-sided tests*\n:::\n:::\n\n## CI for population [**slope**]{style=\"color:green\"} $\\beta_1$\n\nRecall the general CI formula:\n\n$$\\textrm{Point Estimate} \\pm t^*\\cdot SE_{\\textrm{Point Estimate}}$$\n\nFor the CI of the coefficient $b_1$ this translates to\n\n$$b_1 \\pm t^*\\cdot SE_{b_1}$$ where $t^*$ is the critical value from a\n$t$-distribution with $df = n -2$.\n\n<br>\n\n*How is* $\\text{SE}_{b_1}$ *calculated?* See next slide.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  term                  estimate std.error statistic  p.value conf.low conf.high\n  <chr>                    <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)             50.9      2.66       19.1  3.33e-31   45.6      56.2  \n2 female_literacy_rate…    0.232    0.0315      7.38 1.50e-10    0.170     0.295\n```\n:::\n:::\n\n\n## Standard error of fitted slope $b_1$\n\n::: columns\n::: {.column width=\"50%\"}\n$$\\text{SE}_{b_1} = \\frac{s_{\\textrm{residuals}}}{s_x\\sqrt{n-1}}$$\n:::\n\n::: {.column width=\"50%\"}\n$\\text{SE}_{b_1}$ is the **variability** of the statistic $b_1$\n:::\n:::\n\n::: {style=\"font-size: 90%;\"}\n::: columns\n::: {.column width=\"32%\"}\n-   $s_{\\textrm{residuals}}^2$ is the sd of the residuals\n:::\n\n::: {.column width=\"1%\"}\n:::\n\n::: {.column width=\"32%\"}\n-   $s_x$ is the sample sd of the explanatory variable $x$\n:::\n\n::: {.column width=\"1%\"}\n:::\n\n::: {.column width=\"32%\"}\n-   $n$ is the sample size, or the number of (complete) pairs of points\n:::\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.411         0.403  6.14      54.4 1.50e-10     1  -258.  521.  529.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n:::\n\n```{.r .cell-code}\n# standard deviation of the residuals (Residual standard error in summary() output)\n(s_resid <- glance(model1)$sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.142157\n```\n:::\n\n```{.r .cell-code}\n# standard deviation of x's\n(s_x <- sd(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n```{.r .cell-code}\n# number of pairs of complete observations\n(n <- nobs(model1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\n(se_b1 <- s_resid/(s_x * sqrt(n-1))) # compare to SE in regression output\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n\n## Calculate CI for population [**slope**]{style=\"color:green\"} $\\beta_1$\n\n::: columns\n::: {.column width=\"50%\"}\n$$b_1 \\pm t^*\\cdot SE_{b_1}$$\n:::\n\n::: {.column width=\"50%\"}\nwhere $t^*$ is the $t$-distribution critical value with $df = n -2$.\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = TRUE) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ahpkwjxies\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ahpkwjxies table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ahpkwjxies thead, #ahpkwjxies tbody, #ahpkwjxies tfoot, #ahpkwjxies tr, #ahpkwjxies td, #ahpkwjxies th {\n  border-style: none;\n}\n\n#ahpkwjxies p {\n  margin: 0;\n  padding: 0;\n}\n\n#ahpkwjxies .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ahpkwjxies .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ahpkwjxies .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ahpkwjxies .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ahpkwjxies .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ahpkwjxies .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ahpkwjxies .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ahpkwjxies .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ahpkwjxies .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ahpkwjxies .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ahpkwjxies .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ahpkwjxies .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ahpkwjxies .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ahpkwjxies .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ahpkwjxies .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahpkwjxies .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ahpkwjxies .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ahpkwjxies .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ahpkwjxies .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahpkwjxies .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ahpkwjxies .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahpkwjxies .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ahpkwjxies .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahpkwjxies .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ahpkwjxies .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahpkwjxies .gt_left {\n  text-align: left;\n}\n\n#ahpkwjxies .gt_center {\n  text-align: center;\n}\n\n#ahpkwjxies .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ahpkwjxies .gt_font_normal {\n  font-weight: normal;\n}\n\n#ahpkwjxies .gt_font_bold {\n  font-weight: bold;\n}\n\n#ahpkwjxies .gt_font_italic {\n  font-style: italic;\n}\n\n#ahpkwjxies .gt_super {\n  font-size: 65%;\n}\n\n#ahpkwjxies .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ahpkwjxies .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ahpkwjxies .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ahpkwjxies .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ahpkwjxies .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ahpkwjxies .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ahpkwjxies .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">45.6314348</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">56.2243615</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.1695284</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.2948619</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nSave regression output for the row with the slope's information:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_b1 <-tidy(model1) %>% filter(term == \"female_literacy_rate_2011\")\nmodel1_b1 %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"dupraahhhg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dupraahhhg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dupraahhhg thead, #dupraahhhg tbody, #dupraahhhg tfoot, #dupraahhhg tr, #dupraahhhg td, #dupraahhhg th {\n  border-style: none;\n}\n\n#dupraahhhg p {\n  margin: 0;\n  padding: 0;\n}\n\n#dupraahhhg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dupraahhhg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dupraahhhg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dupraahhhg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dupraahhhg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dupraahhhg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dupraahhhg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dupraahhhg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dupraahhhg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dupraahhhg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dupraahhhg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dupraahhhg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dupraahhhg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dupraahhhg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dupraahhhg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dupraahhhg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dupraahhhg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dupraahhhg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dupraahhhg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dupraahhhg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dupraahhhg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dupraahhhg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dupraahhhg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dupraahhhg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dupraahhhg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dupraahhhg .gt_left {\n  text-align: left;\n}\n\n#dupraahhhg .gt_center {\n  text-align: center;\n}\n\n#dupraahhhg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dupraahhhg .gt_font_normal {\n  font-weight: normal;\n}\n\n#dupraahhhg .gt_font_bold {\n  font-weight: bold;\n}\n\n#dupraahhhg .gt_font_italic {\n  font-style: italic;\n}\n\n#dupraahhhg .gt_super {\n  font-size: 65%;\n}\n\n#dupraahhhg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dupraahhhg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dupraahhhg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dupraahhhg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dupraahhhg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dupraahhhg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dupraahhhg .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n::: columns\n::: {.column width=\"50%\"}\nSave values needed for CI:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb1 <- model1_b1$estimate\nSE_b1 <- model1_b1$std.error\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnobs(model1) # sample size n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\n(tstar <- qt(.975, df = 80-2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.990847\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\nCompare CI bounds below with the ones in the regression table above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(CI_LB <- b1 - tstar*SE_b1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1695284\n```\n:::\n\n```{.r .cell-code}\n(CI_UB <- b1 + tstar*SE_b1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2948619\n```\n:::\n:::\n\n:::\n:::\n\n## Hypothesis test for population [**slope**]{style=\"color:green\"} $\\beta_1$\n\n::: columns\n::: {.column width=\"40%\"}\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n```\n\n:::\n\n::: {.column width=\"60%\"}\nThe **test statistic** for $b_1$ is\n\n$$t = \\frac{ b_1 - \\beta_1}{ \\text{SE}_{b_1}} = \\frac{ b_1}{ \\text{SE}_{b_1}}$$\n\nwhen we assume $H_0: \\beta_1 = 0$ is true.\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = TRUE) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"hickpbdgrg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hickpbdgrg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hickpbdgrg thead, #hickpbdgrg tbody, #hickpbdgrg tfoot, #hickpbdgrg tr, #hickpbdgrg td, #hickpbdgrg th {\n  border-style: none;\n}\n\n#hickpbdgrg p {\n  margin: 0;\n  padding: 0;\n}\n\n#hickpbdgrg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hickpbdgrg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hickpbdgrg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hickpbdgrg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hickpbdgrg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hickpbdgrg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hickpbdgrg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hickpbdgrg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hickpbdgrg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hickpbdgrg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hickpbdgrg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hickpbdgrg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hickpbdgrg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hickpbdgrg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hickpbdgrg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hickpbdgrg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hickpbdgrg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hickpbdgrg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hickpbdgrg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hickpbdgrg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hickpbdgrg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hickpbdgrg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hickpbdgrg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hickpbdgrg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hickpbdgrg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hickpbdgrg .gt_left {\n  text-align: left;\n}\n\n#hickpbdgrg .gt_center {\n  text-align: center;\n}\n\n#hickpbdgrg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hickpbdgrg .gt_font_normal {\n  font-weight: normal;\n}\n\n#hickpbdgrg .gt_font_bold {\n  font-weight: bold;\n}\n\n#hickpbdgrg .gt_font_italic {\n  font-style: italic;\n}\n\n#hickpbdgrg .gt_super {\n  font-size: 65%;\n}\n\n#hickpbdgrg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hickpbdgrg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hickpbdgrg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hickpbdgrg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hickpbdgrg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hickpbdgrg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hickpbdgrg .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">45.6314348</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">56.2243615</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.1695284</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.2948619</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nCalculate the test statistic using the values in the regression table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# recall model1_b1 is regression table restricted to b1 row\n(TestStat <- model1_b1$estimate / model1_b1$std.error)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.376557\n```\n:::\n:::\n\n\nCompare this test statistic value to the one from the regression table\nabove\n\n## $p$-value for testing population [**slope**]{style=\"color:green\"} $\\beta_1$\n\n-   As usual, the $p$-value is the *probability of obtaining a test\n    statistic* **just as extreme or more extreme** *than the observed\n    test statistic assuming the null hypothesis* $H_0$ *is true.*\n\n-   To calculate the $p$-value, we need to know the probability\n    distribution of the test statistic (the *null distribution*)\n    assuming $H_0$ is true.\n\n-   Statistical theory tells us that the test statistic $t$ can be\n    modeled by a [$t$-distribution]{style=\"color:green\"} with\n    [$df = n-2$]{style=\"color:green\"}.\n\n-   Recall that this is a 2-sided test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(pv = 2*pt(TestStat, df=80-2, lower.tail=F))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.501286e-10\n```\n:::\n:::\n\n\nCompare the $p$-value to the one from the regression table below\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = TRUE) %>% gt()  # compare p-value calculated above to p-value in table\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"kpadaboizb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kpadaboizb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kpadaboizb thead, #kpadaboizb tbody, #kpadaboizb tfoot, #kpadaboizb tr, #kpadaboizb td, #kpadaboizb th {\n  border-style: none;\n}\n\n#kpadaboizb p {\n  margin: 0;\n  padding: 0;\n}\n\n#kpadaboizb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kpadaboizb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kpadaboizb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kpadaboizb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kpadaboizb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kpadaboizb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kpadaboizb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kpadaboizb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kpadaboizb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kpadaboizb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kpadaboizb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kpadaboizb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kpadaboizb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kpadaboizb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kpadaboizb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpadaboizb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kpadaboizb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kpadaboizb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kpadaboizb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpadaboizb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kpadaboizb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpadaboizb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kpadaboizb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpadaboizb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kpadaboizb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kpadaboizb .gt_left {\n  text-align: left;\n}\n\n#kpadaboizb .gt_center {\n  text-align: center;\n}\n\n#kpadaboizb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kpadaboizb .gt_font_normal {\n  font-weight: normal;\n}\n\n#kpadaboizb .gt_font_bold {\n  font-weight: bold;\n}\n\n#kpadaboizb .gt_font_italic {\n  font-style: italic;\n}\n\n#kpadaboizb .gt_super {\n  font-size: 65%;\n}\n\n#kpadaboizb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kpadaboizb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kpadaboizb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kpadaboizb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kpadaboizb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kpadaboizb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kpadaboizb .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">45.6314348</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">56.2243615</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.1695284</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.2948619</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n# Prediction (& inference)\n\n1.  Prediction for mean response\n2.  Prediction for new individual observation\n\n## Prediction with regression line\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"iscvghbcjq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iscvghbcjq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iscvghbcjq thead, #iscvghbcjq tbody, #iscvghbcjq tfoot, #iscvghbcjq tr, #iscvghbcjq td, #iscvghbcjq th {\n  border-style: none;\n}\n\n#iscvghbcjq p {\n  margin: 0;\n  padding: 0;\n}\n\n#iscvghbcjq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iscvghbcjq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iscvghbcjq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iscvghbcjq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iscvghbcjq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iscvghbcjq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iscvghbcjq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iscvghbcjq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iscvghbcjq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iscvghbcjq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iscvghbcjq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iscvghbcjq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iscvghbcjq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iscvghbcjq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iscvghbcjq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iscvghbcjq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iscvghbcjq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iscvghbcjq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iscvghbcjq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iscvghbcjq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iscvghbcjq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iscvghbcjq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iscvghbcjq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iscvghbcjq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iscvghbcjq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iscvghbcjq .gt_left {\n  text-align: left;\n}\n\n#iscvghbcjq .gt_center {\n  text-align: center;\n}\n\n#iscvghbcjq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iscvghbcjq .gt_font_normal {\n  font-weight: normal;\n}\n\n#iscvghbcjq .gt_font_bold {\n  font-weight: bold;\n}\n\n#iscvghbcjq .gt_font_italic {\n  font-style: italic;\n}\n\n#iscvghbcjq .gt_super {\n  font-size: 65%;\n}\n\n#iscvghbcjq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iscvghbcjq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iscvghbcjq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iscvghbcjq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iscvghbcjq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iscvghbcjq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iscvghbcjq .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n$$\\widehat{\\textrm{life expectancy}} = 50.9 + 0.232 \\cdot \\textrm{female literacy rate} $$\n\nWhat is the predicted life expectancy for a country with female literacy\nrate 60%?\n\n$$\\widehat{\\textrm{life expectancy}} = 50.9 + 0.232 \\cdot 60 = 64.82$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(y_60 <- 50.9 + 0.232*60)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 64.82\n```\n:::\n:::\n\n\n<br>\n\n-   How do we interpret the predicted value?\n-   How variable is it?\n\n## Prediction with regression line\n\n::: columns\n::: {.column width=\"50%\"}\nRecall the population model:\n\n*line + random \"noise\"*\n\n$$Y = \\beta_0 + \\beta_1 \\cdot X + \\varepsilon$$ with\n$\\varepsilon \\sim N(0,\\sigma)$\\\n$\\sigma$ is the variability (SD) of the residuals\n\n<br>\n\n-   When we take the expected value, at a given value $x^*$, we have\n    that the predicted response is the average expected response at\n    $x^*$:\n\n$$\\widehat{E[Y|x^*]} = b_0 + b_1 x^*$$\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-20-1.png){width=768}\n:::\n:::\n\n:::\n:::\n\n-   These are the points on the regression line.\n-   The mean responses has variability, and we can calculate a CI for\n    it, for every value of $x^*$.\n\n## CI for mean response $\\mu_{Y|x^*}$\n\n$$\\widehat{E[Y|x^*]} \\pm t_{n-2}^* \\cdot SE_{\\widehat{E[Y|x^*]}}$$\n\n-   $SE_{\\widehat{E[Y|x^*]}}$ is calculated using\n\n$$SE_{\\widehat{E[Y|x^*]}} = s_{residuals} \\sqrt{\\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}$$\n\n-   $\\widehat{E[Y|x^*]}$ is the predicted value at the specified point\n    $x^*$ of the explanatory variable\n-   $s_{\\textrm{residuals}}^2$ is the sd of the residuals\n-   $n$ is the sample size, or the number of (complete) pairs of points\n-   $\\bar{x}$ is the sample mean of the explanatory variable $x$\n-   $s_x$ is the sample sd of the explanatory variable $x$\n\n<br>\n\n-   Recall that $t_{n-2}^*$ is calculated using `qt()` and depends on\n    the confidence level.\n\n## Example: CI for mean response $\\mu_{Y|x^*}$\n\n**Find the 95% CI for the mean life expectancy when the female literacy\nrate is 60.**\n\n::: {style=\"font-size: 80%;\"}\n\n```{=tex}\n\\begin{align}\n\\widehat{E[Y|x^*]} &\\pm t_{n-2}^* \\cdot SE_{\\widehat{E[Y|x^*]}}\\\\\n64.8596 &\\pm 1.990847 \\cdot s_{residuals} \\sqrt{\\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}\\\\\n64.8596 &\\pm 1.990847 \\cdot 6.142157 \\sqrt{\\frac{1}{80} + \\frac{(60 - 81.65375)^2}{(80-1)21.95371^2}}\\\\\n64.8596 &\\pm 1.990847 \\cdot 0.9675541\\\\\n64.8596 &\\pm 1.926252\\\\\n(62.93335 &, 66.78586)\n\\end{align}\n```\n\n:::\n\n::: {style=\"font-size: 90%;\"}\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n(Y60 <- 50.9278981 + 0.2321951 * 60)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 64.8596\n```\n:::\n\n```{.r .cell-code}\n(tstar <- qt(.975, df = 78))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.990847\n```\n:::\n\n```{.r .cell-code}\n(s_resid <- glance(model1)$sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.142157\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n(n <- nobs(model1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\n(mx <- mean(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n```{.r .cell-code}\n(s_x <- sd(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(SE_Yx <- s_resid *sqrt(1/n + (60 - mx)^2/((n-1)*s_x^2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n\n::: columns\n::: {.column width=\"32%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n(MOE_Yx <- SE_Yx*tstar)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"1%\"}\n:::\n\n::: {.column width=\"32%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nY60 - MOE_Yx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"1%\"}\n:::\n\n::: {.column width=\"32%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nY60 + MOE_Yx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n:::\n:::\n:::\n\n## Example: Using R for CI for mean response $\\mu_{Y|x^*}$\n\n**Find the 95% CI's for the mean life expectancy when the female\nliteracy rate is 40, 60, and 80.**\n\n-   Use the base R `predict()` function\n-   Requires specification of a `newdata` \"value\"\n    -   The `newdata` value is $x^*$\n    -   This has to be in the format of a data frame though\n    -   with column name identical to the predictor variable in the\n        model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdata <- data.frame(female_literacy_rate_2011 = c(40, 60, 80)) \nnewdata\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  female_literacy_rate_2011\n1                        40\n2                        60\n3                        80\n```\n:::\n:::\n\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(model1, \n        newdata=newdata, \n        interval=\"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       fit      lwr      upr\n1 60.21570 57.26905 63.16236\n2 64.85961 62.93335 66.78586\n3 69.50351 68.13244 70.87457\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n### Interpretation\n\nWe are 95% confident that the **average** life expectancy for a country\nwith a 60% female literacy rate will be between 62.9 and 66.8 years.\n:::\n:::\n\n## Confidence bands for mean response $\\mu_{Y|x^*}$\n\n-   Often we plot the CI for many values of X, creating **confidence\n    bands**\n-   The confidence bands are what ggplot creates when we set `se = TRUE`\n    within `geom_smooth`\n-   For what values of x are the confidence bands (intervals) narrowest?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gapm,\n       aes(x=female_literacy_rate_2011, \n           y=life_expectancy_years_2011)) +\n  geom_point()+\n  geom_smooth(method = lm, se=TRUE)+\n  ggtitle(\"Life expectancy vs. female literacy rate\") \n```\n\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-29-1.png){width=960}\n:::\n:::\n\n\n## Width of confidence bands for mean response $\\mu_{Y|x^*}$\n\n-   For what values of $x^*$ are the confidence bands (intervals)\n    narrowest? widest?\n\n\n```{=tex}\n\\begin{align}\n\\widehat{E[Y|x^*]} &\\pm t_{n-2}^* \\cdot SE_{\\widehat{E[Y|x^*]}}\\\\\n\\widehat{E[Y|x^*]} &\\pm t_{n-2}^* \\cdot s_{residuals} \\sqrt{\\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}\n\\end{align}\n```\n\n::: {.cell}\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-30-1.png){width=960}\n:::\n:::\n\n\n## Prediction interval for predicting **individual** observations\n\n-   We do not call this interval a CI since $Y$ is a random variable\n    instead of a parameter\n-   The form is similar to a CI though:\n\n$$\\widehat{Y|x^*} \\pm t_{n-2}^* \\cdot s_{residuals} \\sqrt{1 + \\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}$$\n\n-   Note that the only difference to the CI for a mean value of y is the\n    additional `1+` under the square root.\n    -   Thus the width is wider!\n\n## Example: Prediction interval\n\n**Find the 95% prediction interval for the life expectancy when the\nfemale literacy rate is 60.**\n\n\n```{=tex}\n\\begin{align}\n\\widehat{Y|x^*} &\\pm t_{n-2}^* \\cdot s_{residuals} \\sqrt{1 + \\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}\\\\\n64.8596 &\\pm 1.990847 \\cdot 6.142157 \\sqrt{1+\\frac{1}{80} + \\frac{(60 - 81.65375)^2}{(80-1)21.95371^2}}\\\\\n(52.48072 &, 77.23849)\n\\end{align}\n```\n\n::: {style=\"font-size: 90%;\"}\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n(Y60 <- 50.9278981 + 0.2321951 * 60)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 64.8596\n```\n:::\n\n```{.r .cell-code}\n(tstar <- qt(.975, df = 78))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.990847\n```\n:::\n\n```{.r .cell-code}\n(s_resid <- glance(model1)$sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.142157\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n(n <- nobs(model1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\n(mx <- mean(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n```{.r .cell-code}\n(s_x <- sd(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(SE_Ypred <- s_resid *sqrt(1 + 1/n + (60 - mx)^2/((n-1)*s_x^2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n\n::: columns\n::: {.column width=\"36%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n(MOE_Ypred <- SE_Ypred*tstar)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"1%\"}\n:::\n\n::: {.column width=\"30%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nY60 - MOE_Ypred\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"1%\"}\n:::\n\n::: {.column width=\"30%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nY60 + MOE_Ypred\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n:::\n:::\n:::\n\n## Example: Using R for prediction interval\n\n**Find the 95% prediction intervals for the life expectancy when the\nfemale literacy rate is 40, 60, and 80.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdata  # previously defined for CI's\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  female_literacy_rate_2011\n1                        40\n2                        60\n3                        80\n```\n:::\n\n```{.r .cell-code}\npredict(model1, \n        newdata=newdata, \n        interval=\"prediction\")  # prediction instead of \"confidence\"\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       fit      lwr      upr\n1 60.21570 47.63758 72.79382\n2 64.85961 52.48072 77.23849\n3 69.50351 57.19879 81.80823\n```\n:::\n:::\n\n\n<br>\n\n### Interpretation\n\nWe are 95% confident that a new selected country with a 60% female\nliteracy rate will have a life expectancy between 52.5 and 77.2 years.\n\n## Prediction bands vs. confidence bands (1/2)\n\nCreate a scatterplot with the regression line, 95% confidence bands, and\n95% prediction bands.\n\n-   First create a data frame with the original data points (both x and\n    y values), their respective predicted values, andtheir respective\n    prediction intervals\n-   Can do this with `augment()` from the `broom` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_pred_bands <- augment(model1, interval = \"prediction\")\n\n# take a look at new object:\nnames(model1_pred_bands) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \".rownames\"                  \"life_expectancy_years_2011\"\n [3] \"female_literacy_rate_2011\"  \".fitted\"                   \n [5] \".lower\"                     \".upper\"                    \n [7] \".resid\"                     \".hat\"                      \n [9] \".sigma\"                     \".cooksd\"                   \n[11] \".std.resid\"                \n```\n:::\n\n```{.r .cell-code}\n# glimpse of select variables of interest:\nmodel1_pred_bands %>% \n  select(life_expectancy_years_2011, female_literacy_rate_2011, \n         .fitted:.upper) %>% \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 80\nColumns: 5\n$ life_expectancy_years_2011 <dbl> 56.7, 76.7, 60.9, 76.9, 76.0, 73.8, 71.0, 7…\n$ female_literacy_rate_2011  <dbl> 13.0, 95.7, 58.6, 99.4, 97.9, 99.5, 53.4, 9…\n$ .fitted                    <dbl> 53.94643, 73.14897, 64.53453, 74.00809, 73.…\n$ .lower                     <dbl> 40.91166, 60.81324, 52.14572, 61.65365, 61.…\n$ .upper                     <dbl> 66.98121, 85.48470, 76.92334, 86.36253, 86.…\n```\n:::\n:::\n\n\n## Prediction bands vs. confidence bands (2/2)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(model1_pred_bands) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \".rownames\"                  \"life_expectancy_years_2011\"\n [3] \"female_literacy_rate_2011\"  \".fitted\"                   \n [5] \".lower\"                     \".upper\"                    \n [7] \".resid\"                     \".hat\"                      \n [9] \".sigma\"                     \".cooksd\"                   \n[11] \".std.resid\"                \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(model1_pred_bands, \n       aes(x=female_literacy_rate_2011, y=life_expectancy_years_2011)) +\n  geom_point() +\n  geom_ribbon(aes(ymin = .lower, ymax = .upper), # prediction bands\n              alpha = 0.2, fill = \"red\") +\n  geom_smooth(method=lm) +  # confidence bands\n  labs(title = \"SLR with Confidence & Prediction Bands\") \n```\n\n::: {.cell-output-display}\n![](04_SLR_Inf_Pred_files/figure-revealjs/unnamed-chunk-40-1.png){width=960}\n:::\n:::\n\n\n# Caution...\n\n## Corrrelation doesn't imply causation`*`!\n\n-   This might seem obvious, but make sure to not write your analysis\n    results in a way that implies causation if the study design doesn't\n    warrant it (such as an observational study).\n\n-   Beware of spurious correlations:\n    <http://www.tylervigen.com/spurious-correlations>\n\n![](/img_slides/spurious_corr_2.png)\n\n-   `*`Caveat: there is a whole field of statistics/epidemiology on\n    causal inference. <https://ftp.cs.ucla.edu/pub/stat_ser/r350.pdf>\n\n## What's next?\n\n<br> <br>\n\n![](/img_slides/flowchart_only_continuous.jpg){fig-align=\"center\"}\n",
    "supporting": [
      "04_SLR_Inf_Pred_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}