---
title: "Lab 2"
subtitle: "BSTA 512/612"
description: "Due: Thursday February 8, 2024"
date-modified: "1/17/2024"
date: "2/8/2024"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
    self-contained: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

## Directions

Please turn in your `.html` file [on Sakai.](https://sakai.ohsu.edu/portal/site/BSTA-512-1-AB-W24/tool/961ec5ef-d7f9-4518-be16-25f7af3d6be4?panel=Main) Please let me know if you greatly prefer to submit a physical copy. We can work out another way for you to turn in homework.

The rest of this lab's instructions are embedded into the lab activities.

### Purpose

The main purpose of this lab is to introduce our dataset, codebook, and variables. We will continue to think about the context of our research question, but our main focus is to become familiar with the data.

### Grading

This lab is graded out of 12 points. Nicky will use the following rubric to assign grades.

#### Rubric

|            | 4 points                                                                                                                                                                                                        | 3 points                                                                                                                                                                                       | 2 points                                                                                                                                                                                                   | 1 point                                                                                                                                 | 0 points                                                                                                |
|------------|------------|------------|------------|------------|------------|
| Answers    | Answers demonstrate completion and understanding of the needed activity\*. Answers are thoughtful and can be easily integrated into the final report.                                                           | Answers demonstrate completion and understanding of the needed activity\*. Answers are thoughtful, but lack the clarity needed to easily integrate into the final report.                      | Answers demonstrate completion and minimal understanding of the needed activity\*. Answers are fairly thoughtful, but lack connection to the research.                                                     | Answers demonstrate completion of needed activities\*, although evidently rushed through. Answers seem rushed and with minimal thought. | It is evident that the needed activities\* were not completed. Answers seem rushed and without thought. |
| Formatting | Lab submitted on Sakai with `.html` file. Answers are written in complete sentences with no major grammatical nor spelling errors. With little editing, the answer can be incorporated into the project report. | Lab submitted on Sakai with `.html` file. Answers are written in complete sentences with grammatical or spelling errors. With editing, the answer can be incorporated into the project report. | Lab submitted on Sakai with `.html` file. Answers are written in complete sentences with major grammatical or spelling errors. With major editing, the answer can be incorporated into the project report. | Lab submitted on Sakai with `.html` file. Answers are bulletted or do not use complete sentences.                                       | Lab *not* submitted on Sakai with `.html` file.                                                         |
| Code       |                                                                                                                                                                                                                 |                                                                                                                                                                                                |                                                                                                                                                                                                            |                                                                                                                                         |                                                                                                         |
| Reasoning  |                                                                                                                                                                                                                 |                                                                                                                                                                                                |                                                                                                                                                                                                            |                                                                                                                                         |                                                                                                         |

## Lab activities

### 1. Access and download the data

### 2. Load the data in R

### 3. Data wrangling

#### 3.1 Restrict your analysis to 1 outcome and 10 possible covariates/predictors

#### 3.1 Manipulating variables that are coded as numeric variables

#### 3.2 Converting categorical variables to continuous variables

#### 3.3 Make a new dataset with only complete cases

Quickly make sure that we are not introducing bias by using complete cases

### 4. Some exploratory data analysis

#### 4.1 Univariate exploratory data analysis

#### 4.2 Bivariate exploratory data analysis

#### 4.3 Multivariate exploratory data analysis

### 5. Make a Table 1
