{
  "hash": "fd40c163a61bbb012b1d1ae8791c4562",
  "result": {
    "markdown": "---\ntitle: \"Categorical Covariates\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#213c96\"\ndate: \"02/12/2024\"\ncategories: [\"Week 6\"]\nformat: \n  revealjs:\n    theme: [default, simple_NW.scss]\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Categorical Covariates\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n---\n\n\n\n\n\n# Learning Objectives\n\n## Let's map that to our regression analysis process\n\n::: box\n![](images/arrow2.png){.absolute top=\"13.5%\" right=\"62.1%\" width=\"155\"} ![](images/arrow2.png){.absolute top=\"13.5%\" right=\"28.4%\" width=\"155\"}![](images/arrow_back4.png){.absolute top=\"7.5%\" right=\"30.5%\" width=\"820\"} ![](images/arrow_down.png){.absolute top=\"60.5%\" right=\"48%\" width=\"85\"}\n\n::: columns\n::: {.column width=\"30%\"}\n::: RAP1\n::: RAP1-title\nModel Selection\n:::\n\n::: RAP1-cont\n-   Building a model\n\n-   Selecting variables\n\n-   Prediction vs interpretation\n\n-   Comparing potential models\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP2\n::: RAP2-title\nModel Fitting\n:::\n\n::: RAP2-cont\n-   Find best fit line\n\n-   Using OLS in this class\n\n-   Parameter estimation\n\n-   Categorical covariates\n\n-   Interactions\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP3\n::: RAP3-title\nModel Evaluation\n:::\n\n::: RAP3-cont\n-   Evaluation of model fit\n-   Testing model assumptions\n-   Residuals\n-   Transformations\n-   Influential points\n-   Multicollinearity\n:::\n:::\n:::\n:::\n:::\n\n::: RAP4\n::: RAP4-title\nModel Use (Inference)\n:::\n\n::: RAP4-cont\n::: columns\n::: {.column width=\"50%\"}\n-   Inference for coefficients\n-   Hypothesis testing for coefficients\n:::\n\n::: {.column width=\"50%\"}\n-   Inference for expected $Y$ given $X$\n:::\n:::\n:::\n:::\n\n## Another way of thinking about SSY, SSR, and SSE\n\n## Topics\n\n-   How to write out the regression equation\n\n-   How to calculate & interpret the coefficients\n\n-   Reference levels\n\n    -   Changing the reference level\n\n-   Running the model in R\n\n    -   Factor levels\n\n    -   Changing the reference level in R\n\n    -   Fitted values\n\n    -   Residuals\n\n-   Different ways to “code” categorical variables\n\n    -   Reference cell coding\n\n    -   Effect coding\n\n## Chapter 12 prequel\n\n-   Chapter 12 is on **dummy variables**, which I prefer to call **indicator variables**\n\n-   It covers models that have both a continuous predictor and a categorical predictor\n\n-   The book does not discuss **models with just one categorical predictor** from a regression perspective, which is what these notes cover\n\n-   For this topic we will continue to use the **2011 Gapminder data** with life expectancy as the numeric outcome, but world region (`four_regions`) as the predictor: Africa, Americas, Asia, and Europe\n\n### Suggested resources\n\n-   Modern Dive Section 5.2\n    -   https://moderndive.com/5-regression.html#model2\n    -   Note that they are using a different Gapminder dataset than we are.\n-   Vu & Harrington (text from BSTA 511)\n    -   Sections 6.3.3 & 7.5\n\n<!-- # Load data -->\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## Linear regression with one categorical explanatory variable\n\n<!-- <img src=\"img/hex_skimr.png\" width=\"40%\" height=\"78%\"> -->\n\n::: columns\n::: column\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n:::\n::: column\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n:::\n:::\n\n## Linear regression with one categorical explanatory variable\n\n::: columns\n::: columns\n-   When using a categorical explanatory variable,\n    -   we do **NOT** find a best-fit line.\n-   Instead we model the **means** of the outcome\n    -   for the different levels of the categorical variable.\n    \n:::\n\n::: column\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n:::\n:::\n\n## Regression equation (1/3)\n\n**Previously: simple linear regression**\n\n-   Outcome variable = y = numerical variable\n-   Explanatory variable = x = numerical variable\n\nThe regression (best-fit) line is: $$\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot x $$\n\n**New: what if the explanatory variable is categorical?**\n\n*Naively*, we could write: $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot x$\n\nOr, with our variables: $$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot \\textrm{world regions} $$\n\n-   But what does `world regions` mean in this equation?\n\n## Regression equation (2/3)\n\n-   Since the categorical variable has multiple levels (categories),\n    -   we need more variables in our equation to specify them.\n-   For this example, we have:\n\n$$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot Americas + \\widehat{\\beta}_2 \\cdot Asia + \\widehat{\\beta}_3 \\cdot Europe$$\n\nNote that $Africa$ is not in the equation!\n\n-   When **interpreting this equation**, the world region **variables are replaced with 0 or 1**,\n    -   depending on which world region we are interpreting the regression for\n    -   we call these variable **indicators**, or indicator functions\n        -   textbook calls them **dummy variables**\n\n$$Americas = \n\\begin{cases} \n1 & \\text{if world region =} Americas \\\\\n0         & \\text{else}\n\\end{cases}$$\n\n## Regression equation (3/3)\n\n$$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot Americas + \\widehat{\\beta}_2 \\cdot Asia + \\widehat{\\beta}_3 \\cdot Europe$$\n\n| World region | Regression equation for world region                                                                                  | Average Life Expectancy for world region              |\n|------------------|----------------------------|---------------------------|\n| Africa       | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot 0 + \\widehat{\\beta}_2 \\cdot 0 + \\widehat{\\beta}_3 \\cdot 0$ | $\\widehat{y} = \\widehat{\\beta}_0$                     |\n| Americas     | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot 1 + \\widehat{\\beta}_2 \\cdot 0 + \\widehat{\\beta}_3 \\cdot 0$ | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1$ |\n| Asia         | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot 0 + \\widehat{\\beta}_2 \\cdot 1 + \\widehat{\\beta}_3 \\cdot 0$ | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_2$ |\n| Europe       | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot 0 + \\widehat{\\beta}_2 \\cdot 0 + \\widehat{\\beta}_3 \\cdot 1$ | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_3$ |\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-6-1.png){width=480}\n:::\n:::\n\n\n\n## Interpretation of regression equation coefficients\n\n<!-- * Thus we have the following interpretations for the coefficients: -->\n\n| Coefficient         | Interpretation                                                    |\n|------------------|------------------------------------------------------|\n| $\\widehat{\\beta}_0$ | = mean life expectancy of Africa                                  |\n| $\\widehat{\\beta}_1$ | = difference in mean life expectancies of the Americas and Africa |\n| $\\widehat{\\beta}_2$ | = difference in mean life expectancies of Asia and Africa         |\n| $\\widehat{\\beta}_3$ | = difference in mean life expectancies of Europe and Africa       |\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n## (Manually) calculate coefficient values\n\n$$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot Americas + \\widehat{\\beta}_2 \\cdot Asia + \\widehat{\\beta}_3 \\cdot Europe$$\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-8-1.png){width=480}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n|four_regions | life_ave| Difference with Africa|\n|:------------|--------:|----------------------:|\n|africa       |     61.3|                    0.0|\n|americas     |     74.6|                   13.3|\n|asia         |     71.7|                   10.4|\n|europe       |     77.6|                   16.3|\n:::\n:::\n\n\n\n*See code file for code that created the table above and equation below.*\n\n\n\n::: {.cell}\n\n:::\n\n\n\n$$\\widehat{\\textrm{life expectancy}} = 61.3+ 13.3 \\cdot Americas + 10.4 \\cdot Asia + 16.3 \\cdot Europe$$\n\n## Reference levels\n\n**Why is `Africa` not one of the variables in the regression equation?**\n\n$$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot Americas + \\widehat{\\beta}_2 \\cdot Asia + \\widehat{\\beta}_3 \\cdot Europe$$\n\n-   Categorical variables have to have at least 2 levels. If they have 2 levels, we call them *binary*.\n\n-   We choose one of the levels as our **reference level** to which all other levels of the categorical variable are compared to.\n\n    -   The levels $Americas, Asia, Europe$ are compared to the level $Africa$\n\n-   The **intercept** of the regression equation is the *mean of the outcome restricted to the reference level*. (unless we use effect coding - see later slides)\n\n    -   Recall that the intercept is the mean life expectancy of Africa, which was our reference level.\n\n-   **If the categorical variable has k levels, then we need k-1 variables to model it!**\n\n## Reference levels example: Change the reference level to `Europe` (1/2)\n\nSuppose we want to compare the mean life expectancies of world regions to the $Europe$ level instead of $Africa$.\n\n-   Below is the regression equation for when $Africa$ is the reference level.\n\n$$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot Americas + \\widehat{\\beta}_2 \\cdot Asia + \\widehat{\\beta}_3 \\cdot Europe$$ \\* Update the variables to make $Europe$ the reference level:\n\n$$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot Africa + \\widehat{\\beta}_2 \\cdot Americas + \\widehat{\\beta}_3 \\cdot Asia$$\n\n## Reference levels example: Change the reference level to `europe` (2/2)\n\n-   Now update the coefficients of the regression equation using the output below.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n|four_regions | life_ave| Difference with Europe|\n|:------------|--------:|----------------------:|\n|africa       |     61.3|                  -16.3|\n|americas     |     74.6|                   -3.0|\n|asia         |     71.7|                   -5.9|\n|europe       |     77.6|                    0.0|\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n$$\\widehat{\\textrm{life expectancy}} = 77.6+ -16.3 \\cdot Africa + -3 \\cdot Americas + -5.9 \\cdot Asia$$\n\n## R: Regression table with `lm()` function\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(LifeExpectancyYrs ~ four_regions, data = gapm2)\ntidy(model1) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"bfblggyanx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bfblggyanx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bfblggyanx thead, #bfblggyanx tbody, #bfblggyanx tfoot, #bfblggyanx tr, #bfblggyanx td, #bfblggyanx th {\n  border-style: none;\n}\n\n#bfblggyanx p {\n  margin: 0;\n  padding: 0;\n}\n\n#bfblggyanx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bfblggyanx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bfblggyanx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bfblggyanx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bfblggyanx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bfblggyanx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bfblggyanx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bfblggyanx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bfblggyanx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bfblggyanx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bfblggyanx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bfblggyanx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bfblggyanx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bfblggyanx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bfblggyanx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfblggyanx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bfblggyanx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bfblggyanx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bfblggyanx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfblggyanx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bfblggyanx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfblggyanx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bfblggyanx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfblggyanx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bfblggyanx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfblggyanx .gt_left {\n  text-align: left;\n}\n\n#bfblggyanx .gt_center {\n  text-align: center;\n}\n\n#bfblggyanx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bfblggyanx .gt_font_normal {\n  font-weight: normal;\n}\n\n#bfblggyanx .gt_font_bold {\n  font-weight: bold;\n}\n\n#bfblggyanx .gt_font_italic {\n  font-style: italic;\n}\n\n#bfblggyanx .gt_super {\n  font-size: 65%;\n}\n\n#bfblggyanx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bfblggyanx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bfblggyanx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bfblggyanx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bfblggyanx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bfblggyanx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bfblggyanx .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">61.32037</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.764059</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">80.256072</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.437742e-144</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regionsamericas</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">13.31786</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.229218</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">10.834425</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.893717e-21</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regionsasia</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">10.38148</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.080543</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">9.607656</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">5.941041e-18</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regionseurope</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">16.28852</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.133283</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">14.372866</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">7.595828e-32</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n$$\\widehat{\\textrm{life expectancy}} = 77.6+ -16.3 \\cdot Americas + -3 \\cdot Asia + -5.9 \\cdot Europe$$\n\n-   Which world region did R choose as the reference level?\n\n-   How you would calculate the mean life expectancies of world regions using *only* the results from the regression table?\n\n## R: Change reference level to `europe` (1/2)\n\n-   `four_regions` data type is currently `character` - check this with `str()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(gapm2$four_regions) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n chr [1:187] \"asia\" \"europe\" \"africa\" \"europe\" \"africa\" \"americas\" ...\n```\n:::\n:::\n\n\n\n-   In order to change the reference level, we need to convert it to data type `factor`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm2 <- gapm2 %>% \n  mutate(four_regions = factor(four_regions))\nstr(gapm2$four_regions) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Factor w/ 4 levels \"africa\",\"americas\",..: 3 4 1 4 1 2 2 4 3 4 ...\n```\n:::\n\n```{.r .cell-code}\nlevels(gapm2$four_regions) # order of factor levels\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"africa\"   \"americas\" \"asia\"     \"europe\"  \n```\n:::\n:::\n\n\n\n## R: Change reference level to `europe` (2/2)\n\n-   Now change the order of the factor levels\n-   Code below uses `fct_relevel()` from the `forcats` package that gets loaded as a part of the `tidyverse`\n-   *Any levels not mentioned will be left in their existing order, after the explicitly mentioned levels.*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm2 <- gapm2 %>% \n  mutate(four_regions = \n      fct_relevel(four_regions, \"europe\"))\n\nlevels(gapm2$four_regions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"europe\"   \"africa\"   \"americas\" \"asia\"    \n```\n:::\n:::\n\n\n\n## R: Run model with `europe` as the reference level\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(gapm2$four_regions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"europe\"   \"africa\"   \"americas\" \"asia\"    \n```\n:::\n\n```{.r .cell-code}\nmodel2 <- lm(LifeExpectancyYrs ~ four_regions, data = gapm2)\ntidy(model2) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"koymakaxih\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#koymakaxih table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#koymakaxih thead, #koymakaxih tbody, #koymakaxih tfoot, #koymakaxih tr, #koymakaxih td, #koymakaxih th {\n  border-style: none;\n}\n\n#koymakaxih p {\n  margin: 0;\n  padding: 0;\n}\n\n#koymakaxih .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#koymakaxih .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#koymakaxih .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#koymakaxih .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#koymakaxih .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#koymakaxih .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#koymakaxih .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#koymakaxih .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#koymakaxih .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#koymakaxih .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#koymakaxih .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#koymakaxih .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#koymakaxih .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#koymakaxih .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#koymakaxih .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#koymakaxih .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#koymakaxih .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#koymakaxih .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#koymakaxih .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#koymakaxih .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#koymakaxih .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#koymakaxih .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#koymakaxih .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#koymakaxih .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#koymakaxih .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#koymakaxih .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#koymakaxih .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#koymakaxih .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#koymakaxih .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#koymakaxih .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#koymakaxih .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#koymakaxih .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#koymakaxih .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#koymakaxih .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#koymakaxih .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#koymakaxih .gt_left {\n  text-align: left;\n}\n\n#koymakaxih .gt_center {\n  text-align: center;\n}\n\n#koymakaxih .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#koymakaxih .gt_font_normal {\n  font-weight: normal;\n}\n\n#koymakaxih .gt_font_bold {\n  font-weight: bold;\n}\n\n#koymakaxih .gt_font_italic {\n  font-style: italic;\n}\n\n#koymakaxih .gt_super {\n  font-size: 65%;\n}\n\n#koymakaxih .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#koymakaxih .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#koymakaxih .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#koymakaxih .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#koymakaxih .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#koymakaxih .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#koymakaxih .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">77.608889</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.8369847</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">92.724387</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">9.026023e-156</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regionsafrica</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-16.288519</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.1332826</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">-14.372866</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">7.595828e-32</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regionsamericas</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-2.970654</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.2758264</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">-2.328415</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">2.098282e-02</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regionsasia</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-5.907037</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.1332826</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">-5.212325</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">5.002066e-07</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n$$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot Africa + \\widehat{\\beta}_2 \\cdot Americas + \\widehat{\\beta}_3 \\cdot Asia$$\n\n## Fitted values & residuals\n\nSimilar to as before:\n\n-   **Observed values** $y$ are the values in the dataset\n\n-   **Fitted values** $\\widehat{y}$ are the values that ~~fall on the best-fit line for a specific value of x~~ are the *means of the outcome stratified by the categorical predictor's levels*\n\n-   **Residuals** $y - \\widehat{y}$ are the differences between the two.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n## Fitted values\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression_points <- augment(model1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(regression_points, \n       aes(x = four_regions, \n           y = .fitted)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n<!-- Why are there only 4 points on the plot? Let's `jitter` it: -->\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(regression_points, \n       aes(x = four_regions, \n           y = .fitted)) +\n  geom_jitter()\n```\n\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n## Residual plots\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(regression_points, \n       aes(x=.resid)) +\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(regression_points, \n       aes(y=.resid)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n## Different ways to code categorical variables\n\n-   **Reference cell coding**\n    -   **Intercept** is the **mean** of the outcome variable for the **reference level** of the categorical variable\n    -   k-1 levels are coded as 0, 1\n\n| World region | Var: Americas | Var: Asia | Var: Europe |\n|:------------:|:-------------:|:---------:|:-----------:|\n| Africa (ref) |       0       |     0     |      0      |\n|   Americas   |       1       |     0     |      0      |\n|     Asia     |       0       |     1     |      0      |\n|    Europe    |       0       |     0     |      1      |\n\n-   **Effect coding**: categorical variables\n    -   **Intercept** is the **mean of the k levels' means** of the outcome variable\n    -   This is the same as the overall mean if each of the levels has the same sample size\n    -   k-1 levels are coded as -1, 0, 1\n\n| World region | Var: Americas | Var: Asia | Var: Europe |\n|:------------:|:-------------:|:---------:|:-----------:|\n| Africa (ref) |      -1       |    -1     |     -1      |\n|   Americas   |       1       |     0     |      0      |\n|     Asia     |       0       |     1     |      0      |\n|    Europe    |       0       |     0     |      1      |\n\n## Regression equation with effect coding\n\n$$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot Americas + \\widehat{\\beta}_2 \\cdot Asia + \\widehat{\\beta}_3 \\cdot Europe$$\n\n| World region | Regression equation for world region                                                                                           | Average Life Expectancy for world region                                                      |\n|------------------|----------------------------|---------------------------|\n| Africa       | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot (-1) + \\widehat{\\beta}_2 \\cdot (-1) + \\widehat{\\beta}_3 \\cdot (-1)$ | $\\widehat{y} = \\widehat{\\beta}_0 - \\widehat{\\beta}_1 - \\widehat{\\beta}_2 - \\widehat{\\beta}_3$ |\n| Americas     | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot 1 + \\widehat{\\beta}_2 \\cdot 0 + \\widehat{\\beta}_3 \\cdot 0$          | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1$                                         |\n| Asia         | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot 0 + \\widehat{\\beta}_2 \\cdot 1 + \\widehat{\\beta}_3 \\cdot 0$          | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_2$                                         |\n| Europe       | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot 0 + \\widehat{\\beta}_2 \\cdot 0 + \\widehat{\\beta}_3 \\cdot 1$          | $\\widehat{y} = \\widehat{\\beta}_0 + \\widehat{\\beta}_3$                                         |\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-24-1.png){width=480}\n:::\n:::\n\n\n\n## (Manually) calculate coefficient values with effect coding\n\n$$\\widehat{\\textrm{life expectancy}} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\cdot Americas + \\widehat{\\beta}_2 \\cdot Asia + \\widehat{\\beta}_3 \\cdot Europe$$\n\nThe mean of all 4 regions' mean life expectancy is 71.3 years.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-25-1.png){width=480}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n|four_regions | life_ave| Difference with mean of means|\n|:------------|--------:|-----------------------------:|\n|africa       |     61.3|                         -10.0|\n|americas     |     74.6|                           3.3|\n|asia         |     71.7|                           0.4|\n|europe       |     77.6|                           6.3|\n:::\n:::\n\n\n\n*See code file for code that created the table above & equation below.*\n\n\n\n::: {.cell}\n\n:::\n\n\n\n$$\\widehat{\\textrm{life expectancy}} = 71.3+ 3.3 \\cdot Americas + 0.4 \\cdot Asia + 6.3 \\cdot Europe$$\n\n## Example: regression equation with effect coding\n\n$$\\widehat{\\textrm{life expectancy}} = 71.3+ 3.3 \\cdot Americas + 0.4 \\cdot Asia + 6.3 \\cdot Europe$$\n\n| World region | Regression equation for world region                                                                          | Average Life Expectancy for world region                                                                               |\n|------------------|----------------------------|---------------------------|\n| Africa       | $\\widehat{y} = 71.3 + 3.3 (-1) + 0.4 (-1) + 6.3 (-1)$          | $\\widehat{y} = 71.3 - 3.3 - 0.4 - 6.3 = 61.3$ |\n| Americas     | $\\widehat{y} = 71.3 + 3.3 \\cdot 1 + 0.4 \\cdot 0 + 6.3 \\cdot 0$ | $\\widehat{y} = 71.3 + 3.3 = 74.6$                                               |\n| Asia         | $\\widehat{y} = 71.3 + 3.3 \\cdot 0 + 0.4 \\cdot 1 + 6.3 \\cdot 0$ | $\\widehat{y} = 71.3 + 0.4= 71.7$                                                |\n| Europe       | $\\widehat{y} = 71.3 + 3.3 \\cdot 0 + 0.4 \\cdot 0 + 6.3 \\cdot 1$ | $\\widehat{y} = 71.3 + 6.3= 77.6$                                                |\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_Cat_covariates_files/figure-html/unnamed-chunk-28-1.png){width=480}\n:::\n:::\n\n\n\n## Model in R with effect coding (brute force way)\n\n-   Create variables with the -1, 0, 1 values\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm2 <- gapm2 %>% \n  mutate(\n    americas_eff = case_when(\n      four_regions == \"americas\" ~ 1,\n      four_regions == \"africa\" ~ -1,\n      TRUE ~ 0  # all other cases\n    ),\n    asia_eff = case_when(\n      four_regions == \"asia\" ~ 1,\n      four_regions == \"africa\" ~ -1,\n      TRUE ~ 0  # all other cases\n    ),\n    europe_eff = case_when(\n      four_regions == \"europe\" ~ 1,\n      four_regions == \"africa\" ~ -1,\n      TRUE ~ 0  # all other cases\n    )\n  )\n```\n:::\n\n\n\n<!-- Check:  -->\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm2 %>% tabyl(americas_eff, four_regions) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"waasxbkzqn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#waasxbkzqn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#waasxbkzqn thead, #waasxbkzqn tbody, #waasxbkzqn tfoot, #waasxbkzqn tr, #waasxbkzqn td, #waasxbkzqn th {\n  border-style: none;\n}\n\n#waasxbkzqn p {\n  margin: 0;\n  padding: 0;\n}\n\n#waasxbkzqn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#waasxbkzqn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#waasxbkzqn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#waasxbkzqn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#waasxbkzqn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#waasxbkzqn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#waasxbkzqn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#waasxbkzqn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#waasxbkzqn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#waasxbkzqn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#waasxbkzqn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#waasxbkzqn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#waasxbkzqn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#waasxbkzqn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#waasxbkzqn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waasxbkzqn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#waasxbkzqn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#waasxbkzqn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#waasxbkzqn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waasxbkzqn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#waasxbkzqn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waasxbkzqn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#waasxbkzqn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waasxbkzqn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#waasxbkzqn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waasxbkzqn .gt_left {\n  text-align: left;\n}\n\n#waasxbkzqn .gt_center {\n  text-align: center;\n}\n\n#waasxbkzqn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#waasxbkzqn .gt_font_normal {\n  font-weight: normal;\n}\n\n#waasxbkzqn .gt_font_bold {\n  font-weight: bold;\n}\n\n#waasxbkzqn .gt_font_italic {\n  font-style: italic;\n}\n\n#waasxbkzqn .gt_super {\n  font-size: 65%;\n}\n\n#waasxbkzqn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#waasxbkzqn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#waasxbkzqn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#waasxbkzqn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#waasxbkzqn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#waasxbkzqn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#waasxbkzqn .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"americas_eff\">americas_eff</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"europe\">europe</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"africa\">africa</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"americas\">americas</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"asia\">asia</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"americas_eff\" class=\"gt_row gt_right\">-1</td>\n<td headers=\"europe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"africa\" class=\"gt_row gt_right\">54</td>\n<td headers=\"americas\" class=\"gt_row gt_right\">0</td>\n<td headers=\"asia\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"americas_eff\" class=\"gt_row gt_right\">0</td>\n<td headers=\"europe\" class=\"gt_row gt_right\">45</td>\n<td headers=\"africa\" class=\"gt_row gt_right\">0</td>\n<td headers=\"americas\" class=\"gt_row gt_right\">0</td>\n<td headers=\"asia\" class=\"gt_row gt_right\">54</td></tr>\n    <tr><td headers=\"americas_eff\" class=\"gt_row gt_right\">1</td>\n<td headers=\"europe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"africa\" class=\"gt_row gt_right\">0</td>\n<td headers=\"americas\" class=\"gt_row gt_right\">34</td>\n<td headers=\"asia\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n\n```{.r .cell-code}\ngapm2 %>% tabyl(asia_eff, four_regions) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"nkympahudm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nkympahudm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nkympahudm thead, #nkympahudm tbody, #nkympahudm tfoot, #nkympahudm tr, #nkympahudm td, #nkympahudm th {\n  border-style: none;\n}\n\n#nkympahudm p {\n  margin: 0;\n  padding: 0;\n}\n\n#nkympahudm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nkympahudm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nkympahudm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nkympahudm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nkympahudm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nkympahudm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nkympahudm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nkympahudm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nkympahudm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nkympahudm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nkympahudm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nkympahudm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nkympahudm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nkympahudm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nkympahudm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nkympahudm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nkympahudm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nkympahudm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nkympahudm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nkympahudm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nkympahudm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nkympahudm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nkympahudm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nkympahudm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nkympahudm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nkympahudm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nkympahudm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nkympahudm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nkympahudm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nkympahudm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nkympahudm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nkympahudm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nkympahudm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nkympahudm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nkympahudm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nkympahudm .gt_left {\n  text-align: left;\n}\n\n#nkympahudm .gt_center {\n  text-align: center;\n}\n\n#nkympahudm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nkympahudm .gt_font_normal {\n  font-weight: normal;\n}\n\n#nkympahudm .gt_font_bold {\n  font-weight: bold;\n}\n\n#nkympahudm .gt_font_italic {\n  font-style: italic;\n}\n\n#nkympahudm .gt_super {\n  font-size: 65%;\n}\n\n#nkympahudm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nkympahudm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nkympahudm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nkympahudm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nkympahudm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nkympahudm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nkympahudm .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"asia_eff\">asia_eff</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"europe\">europe</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"africa\">africa</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"americas\">americas</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"asia\">asia</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"asia_eff\" class=\"gt_row gt_right\">-1</td>\n<td headers=\"europe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"africa\" class=\"gt_row gt_right\">54</td>\n<td headers=\"americas\" class=\"gt_row gt_right\">0</td>\n<td headers=\"asia\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"asia_eff\" class=\"gt_row gt_right\">0</td>\n<td headers=\"europe\" class=\"gt_row gt_right\">45</td>\n<td headers=\"africa\" class=\"gt_row gt_right\">0</td>\n<td headers=\"americas\" class=\"gt_row gt_right\">34</td>\n<td headers=\"asia\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"asia_eff\" class=\"gt_row gt_right\">1</td>\n<td headers=\"europe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"africa\" class=\"gt_row gt_right\">0</td>\n<td headers=\"americas\" class=\"gt_row gt_right\">0</td>\n<td headers=\"asia\" class=\"gt_row gt_right\">54</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n\n```{.r .cell-code}\ngapm2 %>% tabyl(europe_eff, four_regions) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ozkqyygynt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ozkqyygynt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ozkqyygynt thead, #ozkqyygynt tbody, #ozkqyygynt tfoot, #ozkqyygynt tr, #ozkqyygynt td, #ozkqyygynt th {\n  border-style: none;\n}\n\n#ozkqyygynt p {\n  margin: 0;\n  padding: 0;\n}\n\n#ozkqyygynt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ozkqyygynt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ozkqyygynt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ozkqyygynt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ozkqyygynt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ozkqyygynt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ozkqyygynt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ozkqyygynt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ozkqyygynt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ozkqyygynt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ozkqyygynt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ozkqyygynt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ozkqyygynt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ozkqyygynt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ozkqyygynt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ozkqyygynt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ozkqyygynt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ozkqyygynt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ozkqyygynt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ozkqyygynt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ozkqyygynt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ozkqyygynt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ozkqyygynt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ozkqyygynt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ozkqyygynt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ozkqyygynt .gt_left {\n  text-align: left;\n}\n\n#ozkqyygynt .gt_center {\n  text-align: center;\n}\n\n#ozkqyygynt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ozkqyygynt .gt_font_normal {\n  font-weight: normal;\n}\n\n#ozkqyygynt .gt_font_bold {\n  font-weight: bold;\n}\n\n#ozkqyygynt .gt_font_italic {\n  font-style: italic;\n}\n\n#ozkqyygynt .gt_super {\n  font-size: 65%;\n}\n\n#ozkqyygynt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ozkqyygynt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ozkqyygynt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ozkqyygynt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ozkqyygynt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ozkqyygynt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ozkqyygynt .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"europe_eff\">europe_eff</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"europe\">europe</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"africa\">africa</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"americas\">americas</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"asia\">asia</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"europe_eff\" class=\"gt_row gt_right\">-1</td>\n<td headers=\"europe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"africa\" class=\"gt_row gt_right\">54</td>\n<td headers=\"americas\" class=\"gt_row gt_right\">0</td>\n<td headers=\"asia\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"europe_eff\" class=\"gt_row gt_right\">0</td>\n<td headers=\"europe\" class=\"gt_row gt_right\">0</td>\n<td headers=\"africa\" class=\"gt_row gt_right\">0</td>\n<td headers=\"americas\" class=\"gt_row gt_right\">34</td>\n<td headers=\"asia\" class=\"gt_row gt_right\">54</td></tr>\n    <tr><td headers=\"europe_eff\" class=\"gt_row gt_right\">1</td>\n<td headers=\"europe\" class=\"gt_row gt_right\">45</td>\n<td headers=\"africa\" class=\"gt_row gt_right\">0</td>\n<td headers=\"americas\" class=\"gt_row gt_right\">0</td>\n<td headers=\"asia\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n## Model in R with effect coding (brute force way)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- lm(LifeExpectancyYrs ~ americas_eff + asia_eff + europe_eff, \n             data = gapm2)\ntidy(model3) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"hbcysgkojr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hbcysgkojr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hbcysgkojr thead, #hbcysgkojr tbody, #hbcysgkojr tfoot, #hbcysgkojr tr, #hbcysgkojr td, #hbcysgkojr th {\n  border-style: none;\n}\n\n#hbcysgkojr p {\n  margin: 0;\n  padding: 0;\n}\n\n#hbcysgkojr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hbcysgkojr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hbcysgkojr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hbcysgkojr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hbcysgkojr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hbcysgkojr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hbcysgkojr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hbcysgkojr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hbcysgkojr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hbcysgkojr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hbcysgkojr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hbcysgkojr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hbcysgkojr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hbcysgkojr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hbcysgkojr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hbcysgkojr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hbcysgkojr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hbcysgkojr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hbcysgkojr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hbcysgkojr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hbcysgkojr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hbcysgkojr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hbcysgkojr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hbcysgkojr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hbcysgkojr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hbcysgkojr .gt_left {\n  text-align: left;\n}\n\n#hbcysgkojr .gt_center {\n  text-align: center;\n}\n\n#hbcysgkojr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hbcysgkojr .gt_font_normal {\n  font-weight: normal;\n}\n\n#hbcysgkojr .gt_font_bold {\n  font-weight: bold;\n}\n\n#hbcysgkojr .gt_font_italic {\n  font-style: italic;\n}\n\n#hbcysgkojr .gt_super {\n  font-size: 65%;\n}\n\n#hbcysgkojr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hbcysgkojr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hbcysgkojr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hbcysgkojr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hbcysgkojr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hbcysgkojr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hbcysgkojr .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">71.3173366</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.4179792</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">170.6241472</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.183922e-203</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">americas_eff</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">3.3208987</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.7989377</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.1566430</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">4.954854e-05</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">asia_eff</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.3845153</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.6830810</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.5629131</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">5.741830e-01</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">europe_eff</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">6.2915523</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.7245538</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">8.6833472</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">2.096464e-15</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n$$\\widehat{\\textrm{life expectancy}} = 71.3+ 3.3 \\cdot Americas + 0.4 \\cdot Asia + 6.3 \\cdot Europe$$\n\n-   Note that all three of the effect coded variables we created need to be specified in the model, instead of the one `four_regions` variable\n-   How you would calculate the mean life expectancies of world regions using *only* the results from the regression table?\n\n------------------------------------------------------------------------\n\n## Model in R with effect coding using contrasts\n\n-   Contrasts are used to tell R what \"coding system\" we want to use when testing hypotheses\n\n**Reference cell coding** is the default type of coding used by R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1st level is all 0's\ncontr.treatment(4)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  2 3 4\n1 0 0 0\n2 1 0 0\n3 0 1 0\n4 0 0 1\n```\n:::\n:::\n\n\n\n**Effect coding**: note that R assigns the -1 values to the *last* level instead of the first level\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 4th level is all -1's\ncontr.sum(4)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [,1] [,2] [,3]\n1    1    0    0\n2    0    1    0\n3    0    0    1\n4   -1   -1   -1\n```\n:::\n:::\n\n\n\n## Reorder levels so that Africa is last\n\n-   Doing this so that R's `lm()` output is consistent with what we calculated on previous slides when using effect coding\n-   R will assign -1 values to the *last* level of the categorical variable\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(gapm2$four_regions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"europe\"   \"africa\"   \"americas\" \"asia\"    \n```\n:::\n\n```{.r .cell-code}\ngapm2 <- gapm2 %>% \n  mutate(four_regions_africa_last = \n      fct_relevel(four_regions, \"americas\", \"asia\", \"europe\", \"africa\"))\n\nlevels(gapm2$four_regions_africa_last)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"americas\" \"asia\"     \"europe\"   \"africa\"  \n```\n:::\n\n```{.r .cell-code}\ngapm2 %>% tabyl(four_regions, four_regions_africa_last)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n four_regions americas asia europe africa\n       europe        0    0     45      0\n       africa        0    0      0     54\n     americas       34    0      0      0\n         asia        0   54      0      0\n```\n:::\n:::\n\n\n\n## Model in R with effect coding using contrasts\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- lm(LifeExpectancyYrs ~ four_regions_africa_last, \n             contrasts = list(four_regions_africa_last = contr.sum(4)), \n             data = gapm2)\ntidy(model3) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"xfrptzkxsb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xfrptzkxsb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xfrptzkxsb thead, #xfrptzkxsb tbody, #xfrptzkxsb tfoot, #xfrptzkxsb tr, #xfrptzkxsb td, #xfrptzkxsb th {\n  border-style: none;\n}\n\n#xfrptzkxsb p {\n  margin: 0;\n  padding: 0;\n}\n\n#xfrptzkxsb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xfrptzkxsb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xfrptzkxsb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xfrptzkxsb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xfrptzkxsb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xfrptzkxsb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xfrptzkxsb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xfrptzkxsb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xfrptzkxsb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xfrptzkxsb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xfrptzkxsb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xfrptzkxsb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xfrptzkxsb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xfrptzkxsb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xfrptzkxsb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xfrptzkxsb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xfrptzkxsb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xfrptzkxsb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xfrptzkxsb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xfrptzkxsb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xfrptzkxsb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xfrptzkxsb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xfrptzkxsb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xfrptzkxsb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xfrptzkxsb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xfrptzkxsb .gt_left {\n  text-align: left;\n}\n\n#xfrptzkxsb .gt_center {\n  text-align: center;\n}\n\n#xfrptzkxsb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xfrptzkxsb .gt_font_normal {\n  font-weight: normal;\n}\n\n#xfrptzkxsb .gt_font_bold {\n  font-weight: bold;\n}\n\n#xfrptzkxsb .gt_font_italic {\n  font-style: italic;\n}\n\n#xfrptzkxsb .gt_super {\n  font-size: 65%;\n}\n\n#xfrptzkxsb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xfrptzkxsb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xfrptzkxsb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xfrptzkxsb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xfrptzkxsb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xfrptzkxsb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xfrptzkxsb .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">71.3173366</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.4179792</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">170.6241472</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.183922e-203</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regions_africa_last1</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">3.3208987</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.7989377</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.1566430</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">4.954854e-05</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regions_africa_last2</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.3845153</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.6830810</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.5629131</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">5.741830e-01</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regions_africa_last3</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">6.2915523</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.7245538</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">8.6833472</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">2.096464e-15</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\nRegression equation we computed based on group means:\n\n$$\\widehat{\\textrm{life expectancy}} = 71.3+ 3.3 \\cdot Americas + 0.4 \\cdot Asia + 6.3 \\cdot Europe$$\n\n## Reference cell coding vs. effect coding\n\n-   Reference cell coding\n    -   R's default for regression\n-   Effect coding\n    -   This is what one-way ANOVA is from a regression point of view\n        -   See Section 17.4.2 of textbook\n-   Different statistical software packages have different defaults.\n    -   Important to know what the default is!!\n\nSee https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/ for more on different ways to code categorical variables in R\n",
    "supporting": [
      "10_Cat_covariates_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}