{
  "hash": "9321105568d536b4dfec90d8d96d886b",
  "result": {
    "markdown": "---\ntitle: \"SLR: Model Evaluation\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#213c96\"\ndate: \"01/24/2023\"\ncategories: [\"Week 1\"]\nformat: \n  revealjs:\n    theme: [default, simple_NW.scss]\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: SLR 3\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\n\n## Topics\n\n-   ANOVA table\n-   Explained and unexplained variation\n-   F test\n-   \n\n# Learning Objectives\n\n1.  \n\n## So far in our regression example...\n\n::: columns\n::: {.column width=\"49%\"}\n**Lesson 1 of SLR:**\n\n-   Fit regression line\n-   Calculate slope & intercept\n-   Interpret slope & intercept\n\n**Lesson 2 of SLR:**\n\n-   Estimate variance of the residuals\n-   Inference for slope & intercept: CI, p-value\n-   Confidence bands of regression line for mean value of Y\\|X\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"49%\"}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n```\nRows: 188 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): country\ndbl (2): life_expectancy_years_2011, female_literacy_rate_2011\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 108 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 108 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](05_SLR_Eval_files/figure-html/unnamed-chunk-2-1.png){width=1056}\n:::\n:::\n\n\n:::\n:::\n\n\n\n```{=tex}\n\\begin{aligned}\n\\widehat{Y} &= \\widehat\\beta_0 + \\widehat\\beta_1 \\cdot X\\\\\n\\widehat{\\text{life expectancy}} &= 50.9 + 0.232 \\cdot \\text{female literacy rate}\n\\end{aligned}\n```\n\n\n## Let's revisit the regression analysis process\n\n::: box\n![](images/arrow2.png){.absolute top=\"13.5%\" right=\"62.1%\" width=\"155\"}\n![](images/arrow2.png){.absolute top=\"13.5%\" right=\"28.4%\"\nwidth=\"155\"}![](images/arrow_back4.png){.absolute top=\"7.5%\"\nright=\"30.5%\" width=\"820\"} ![](images/arrow_down.png){.absolute\ntop=\"60.5%\" right=\"48%\" width=\"85\"}\n\n::: columns\n::: {.column width=\"30%\"}\n::: RAP1\n::: RAP1-title\nModel Selection\n:::\n\n::: RAP1-cont\n-   Building a model\n\n-   Selecting variables\n\n-   Prediction vs interpretation\n\n-   Comparing potential models\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP2\n::: RAP2-title\nModel Fitting\n:::\n\n::: RAP2-cont\n-   Find best fit line\n\n-   Using OLS in this class\n\n-   Parameter estimation\n\n-   Categorical covariates\n\n-   Interactions\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP3\n::: RAP3-title\nModel Evaluation\n:::\n\n::: RAP3-cont\n-   Evaluation of model fit\n-   Testing model assumptions\n-   Residuals\n-   Transformations\n-   Influential points\n-   Multicollinearity\n:::\n:::\n:::\n:::\n:::\n\n::: RAP4\n::: RAP4-title\nModel Use (Inference)\n:::\n\n::: RAP4-cont\n::: columns\n::: {.column width=\"50%\"}\n-   Inference for coefficients\n-   Hypothesis testing for coefficients\n:::\n\n::: {.column width=\"50%\"}\n-   Inference for expected $Y$ given $X$\n-   Prediction of new $Y$ given $X$\n:::\n:::\n:::\n:::\n\n## Quickly go over our estimates from last class???\n\nNow we are making sure our whole model is trustworthy\n\n# Learning Objectives\n\n1.  \n\n## Explained vs. Unexplained Variation\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_SLR_Eval_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n$$ \\begin{aligned}\nY_i - \\bar{Y} & = & (Y_i - \\hat{Y}_i) & + (\\hat{Y}_i- \\bar{Y})\\\\\n\\text{Total unexplained variation} & = & \\text{Variation due to regression} & + \\text{Residual variation after regression}\n\\end{aligned}$$\n\n## More of the equation\n\n::: columns\n::: {.column width=\"40%\"}\n$$Y_i - \\bar{Y} = (Y_i - \\hat{Y}_i) + (\\hat{Y}_i- \\bar{Y})$$\n\n-   $Y_i - \\bar{Y}$ = the deviation of $Y_i$ around the mean $\\bar{Y}$\n    -   (the **total** amount deviation unexplained at $X_i$ ).\n-   $Y_i - \\hat{Y}_i$ = the deviation of the observation $Y$ around the\n    fitted regression line\n    -   (the amount deviation **unexplained** by the regression at $X_i$\n        ).\n-   $\\hat{Y}_i- \\bar{Y}$ = the deviation of the fitted value $\\hat{Y}_i$\n    around the mean $\\bar{Y}$\n    -   (the amount deviation **explained** by the regression at $X_i$ )\n:::\n\n::: {.column width=\"60%\"}\n   \n\n![](05_SLR_Eval/SS.png){fig-align=\"center\"}\n:::\n:::\n\n## How is this actually calculated for our fitted model?\n\n$$ \\begin{aligned}\nY_i - \\bar{Y} & = & (Y_i - \\hat{Y}_i) & + (\\hat{Y}_i- \\bar{Y})\\\\\n\\text{Total unexplained variation} & = & \\text{Variation due to regression} & + \\text{Residual variation after regression}\n\\end{aligned}$$\n\n$$\\begin{aligned}\n\\sum_{i=1}^n (Y_i - \\bar{Y})^2 & = \\sum_{i=1}^n (\\hat{Y}_i- \\bar{Y})^2 + \\sum_{i=1}^n (Y_i - \\hat{Y}_i)^2 \\\\\nSSY & = SSR + SSE \n\\end{aligned}$$\n$$\\text{Total Sum of Squares} = \\text{Sum of Squares due to Regression} + \\text{Sum of Squares due to Error (residuals)}$$\n\n::: columns\n::: {.column width=\"7%\"}\n:::\n\n::: {.column width=\"86%\"}\nANOVA table:\n\n| Variation Source | df    | SS    | MS                      | test statistic        | p-value |\n|------------------|-------|-------|-------------------------|-----------------------|---------|\n| Regression       | $1$   | $SSR$ | $MSR = \\frac{SSR}{1}$   | $F = \\frac{MSR}{MSE}$ |         |\n| Error            | $n-2$ | $SSE$ | $MSE = \\frac{SSE}{n-2}$ |                       |         |\n| Total            | $n-1$ | $SSY$ |                         |                       |         |\n:::\n\n::: {.column width=\"7%\"}\n:::\n:::\n\n## ANOVA table in R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit regression model:\nmodel1 <- lm(life_expectancy_years_2011 ~ female_literacy_rate_2011,\n             data = gapm)\n\nanova(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nResponse: life_expectancy_years_2011\n                          Df Sum Sq Mean Sq F value    Pr(>F)    \nfemale_literacy_rate_2011  1 2052.8 2052.81  54.414 1.501e-10 ***\nResiduals                 78 2942.6   37.73                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nanova(model1) %>% tidy() %>% gt() %>%\n   tab_options(table.font.size = 40) %>%\n   fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"tcjfdnvwub\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tcjfdnvwub table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tcjfdnvwub thead, #tcjfdnvwub tbody, #tcjfdnvwub tfoot, #tcjfdnvwub tr, #tcjfdnvwub td, #tcjfdnvwub th {\n  border-style: none;\n}\n\n#tcjfdnvwub p {\n  margin: 0;\n  padding: 0;\n}\n\n#tcjfdnvwub .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tcjfdnvwub .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tcjfdnvwub .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tcjfdnvwub .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tcjfdnvwub .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tcjfdnvwub .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tcjfdnvwub .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tcjfdnvwub .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tcjfdnvwub .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tcjfdnvwub .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tcjfdnvwub .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tcjfdnvwub .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tcjfdnvwub .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tcjfdnvwub .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tcjfdnvwub .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tcjfdnvwub .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tcjfdnvwub .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tcjfdnvwub .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tcjfdnvwub .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tcjfdnvwub .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tcjfdnvwub .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tcjfdnvwub .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tcjfdnvwub .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tcjfdnvwub .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tcjfdnvwub .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tcjfdnvwub .gt_left {\n  text-align: left;\n}\n\n#tcjfdnvwub .gt_center {\n  text-align: center;\n}\n\n#tcjfdnvwub .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tcjfdnvwub .gt_font_normal {\n  font-weight: normal;\n}\n\n#tcjfdnvwub .gt_font_bold {\n  font-weight: bold;\n}\n\n#tcjfdnvwub .gt_font_italic {\n  font-style: italic;\n}\n\n#tcjfdnvwub .gt_super {\n  font-size: 65%;\n}\n\n#tcjfdnvwub .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tcjfdnvwub .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tcjfdnvwub .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tcjfdnvwub .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tcjfdnvwub .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tcjfdnvwub .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tcjfdnvwub .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"meansq\">meansq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"df\" class=\"gt_row gt_right\">1.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">2,052.812</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">2,052.812</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">54.414</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">78.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">2,942.635</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">37.726</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n## What is the F statistic testing?\n\n$$F = \\frac{MSR}{MSE}$$\n\n-   It can be shown that\n\n$$E(MSE)=\\sigma^2\\ \\text{and}\\ E(MSR) = \\sigma^2 + \\beta_1^2\\sum_{i=1}^n (X_i- \\bar{X})^2$$\n\n-   Recall that $\\sigma^2$ is the variance of the residuals\n-   Thus if\n    -   $\\beta_1 = 0$, then\n        $F \\approx \\frac{\\hat{\\sigma}^2}{\\hat{\\sigma}^2} = 1$\n    -   $\\beta_1 \\neq 0$, then\n        $F \\approx \\frac{\\hat{\\sigma}^2 + \\hat{\\beta}_1^2\\sum_{i=1}^n (X_i- \\bar{X})^2}{\\hat{\\sigma}^2} > 1$\n-   So the $F$ statistic can be used to test $\\beta_1$\n\n## F-test for the slope\n\n**Hypotheses**\n\n$$H_0: \\beta_1 = 0\\\\\nH_A: \\beta_1 \\neq 0$$\n\n**Test statistic and probability distribution**\n\n$$F = \\frac{MSR}{MSE} \\sim F_{1, n-2}$$\n\n-   The F statistic has an $F$-distribution with numerator $df = 1$ and\n    denominator $df = n-2$.\n\n**Decision**\n\n**Critical value** approach:\n\nLet $F_{1, n-2, 1-\\alpha}$ be the critical value for the $F_{1, n-2}$\ndistribution with area $\\alpha$ to the right.\n\n-   If $F > F_{1, n-2, 1-\\alpha}$, then reject $H_0$\n-   If $F \\leq F_{1, n-2, 1-\\alpha}$, then fail to reject $H_0$\n\n$p$-value approach:\n\n-   If $p$-value $< \\alpha$, then reject $H_0$\n-   If $p$-value $\\geq \\alpha$, then fail to reject $H_0$\n\n**Conclusion**\n\nIf $H_0$ is rejected, we conclude there is sufficient evidence that\nthere exists a linear relationship between $X$ and $Y$\n($\\beta_1 \\neq 0$).\n\n## F-test vs. t-test for the slope\n\nThe square of a $t$-distribution with $df = \\nu$ is an $F$-distribution\nwith $df = 1, \\nu$\n\n$$T_{\\nu}^2 \\sim F_{1,\\nu}$$\n\n## Example: F-test for the slope\n\n**Hypotheses**\n\n$$H_0: \\beta_1 = 0\\\\\nH_A: \\beta_1 \\neq 0$$\n\n**Test statistic and probability distribution**\n\n$$F = \\frac{MSR}{MSE} = \\frac{2052.81}{37.73} = 54.414 \\sim F_{1, 78}$$\n\n**Decision**\n\n**Critical value** approach:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# critical value for F 1,78 with alpha = 0.05:\nqf(.95, df1 = 1, df2 = 78)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.963472\n```\n:::\n:::\n\n\n\nSince $F = 54.414 > 3.9634721$, we reject $H_0$.\n\n$p$-value approach:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# p-value is ALWAYS the right tail for F-test\npf(54.414, df1 = 1, df2 = 78, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.501104e-10\n```\n:::\n:::\n\n\n\nSince\n$p\\text{-value} = 1.5011043\\times 10^{-10} < 0.05$,\nwe reject $H_0$.\n\n**Conclusion**\n\nThere is sufficient evidence that there exists a linear relationship\nbetween countries' female literacy rate and average life expectancy (p\n\\< 0.001).\n\n# Chapter 6: The Correlation Coefficient and Straight-line Regression Analysis\n\n## Correlation coefficient\n\nThe (Peasron) correlation coefficient $r$ of variables $X$ and $Y$ can\nbe computed using the formula:\n\n$$r = \\frac{\\sum_{i=1}^n (X_i - \\bar{X})(Y_i - \\bar{Y})}{\\Big(\\sum_{i=1}^n (X_i - \\bar{X})^2 \\sum_{i=1}^n (Y_i - \\bar{Y})^2\\Big)^{1/2}} \n= \\frac{SSXY}{\\sqrt{SSX \\cdot SSY}}$$\n\nSince (see Ch 5)\n\n$$\\widehat{\\beta}_1 = \\frac{\\sum_{i=1}^n (X_i - \\bar{X})(Y_i - \\bar{Y})}{\\sum_{i=1}^n (X_i - \\bar{X})^2}$$\nwe have the relationship\n\n$$\\widehat{\\beta}_1 = r\\frac{s_Y}{s_X},\\ \\ \\text{or},\\ \\  r = \\widehat{\\beta}_1\\frac{s_X}{s_Y}$$\n\n## Coefficient of determination: $R^2$\n\nIt can be shown that the square of the correlation coefficient $r$ is\nequal to\n\n$$R^2 = \\frac{SSR}{SSY} = \\frac{SSY - SSE}{SSY}$$\n\n-   $R^2$ is called the **coefficient of determination**.\n-   Interpretation #1\n    -   Numerator is the **reduction** in $SSY$ due to using $X$ to\n        predict $Y$\n    -   Thus the fraction is the proportionate reduction\n-   Interpretation #2\n    -   The proportion of variation in the $Y$ values explained by the\n        regression model\n-   $R^2$ measures the strength of the linear relationship between $X$\n    and $Y$:\n    -   $R^2 = \\pm 1$: Perfect relationship\n        -   Happens when $SSE = 0$, i.e. no error, all points on the\n            line\n    -   $R^2 = 0$: No relationship\n        -   Happens when $SSY = SSE$, i.e. using the line doesn't not\n            improve model fit over using $\\bar{Y}$ to model the $Y$\n            values.\n\n## R Example\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(x = gapm$life_expectancy_years_2011, \n    y = gapm$female_literacy_rate_2011)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n```{.r .cell-code}\nr <- cor(x = gapm$life_expectancy_years_2011, \n    y = gapm$female_literacy_rate_2011,\n    use =  \"complete.obs\")\nr\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6410434\n```\n:::\n\n```{.r .cell-code}\nr^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4109366\n```\n:::\n\n```{.r .cell-code}\nsummary(model1) # for R^2 value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = life_expectancy_years_2011 ~ female_literacy_rate_2011, \n    data = gapm)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-22.299  -2.670   1.145   4.114   9.498 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               50.92790    2.66041  19.143  < 2e-16 ***\nfemale_literacy_rate_2011  0.23220    0.03148   7.377  1.5e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.142 on 78 degrees of freedom\n  (108 observations deleted due to missingness)\nMultiple R-squared:  0.4109,\tAdjusted R-squared:  0.4034 \nF-statistic: 54.41 on 1 and 78 DF,  p-value: 1.501e-10\n```\n:::\n:::\n\n\n\n## Test $\\rho = 0$\n\n$\\rho$ is the population parameter for the correlation coefficient $r$\n\n**Hypotheses**\n\n$$H_0: \\rho = 0 \\ \\ \\text{vs.} \\ \\ H_A: \\rho \\neq 0$$\n\n**Test statistic and probability distribution**\n\n$$T = \\frac{r\\sqrt{n-2}}{\\sqrt{1-r^2}} \\sim t_{n-2}$$\n\n-   The t statistic has a Student's $t$-distribution with $df = n-2$.\n\n**Decision**\n\n**Critical value** approach:\n\nLet $t_{n-2, 1-\\alpha/2}$ be the critical value for the $t_{n-2}$\ndistribution with area $\\alpha/2$ in each of the tails.\n\n-   If $|T| > t_{n-2, 1-\\alpha/2}$, then reject $H_0$\n-   If $|T| \\leq t_{n-2, 1-\\alpha/2}$, then fail to reject $H_0$\n\n$p$-value approach:\n\n-   If $p$-value $< \\alpha$, then reject $H_0$\n-   If $p$-value $\\geq \\alpha$, then fail to reject $H_0$\n\n**Conclusion**\n\nIf $H_0$ is rejected, we conclude there is sufficient evidence that\nthere exists a linear correlation between $X$ and $Y$ ($\\rho \\neq 0$).\n\n### Example: Test $\\rho = 0$\n\n**Hypotheses**\n\n$$H_0: \\rho = 0 \\ \\ \\text{vs.} \\ \\ H_A: \\rho \\neq 0$$\n\n**Test statistic and probability distribution**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr # calculated previously\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6410434\n```\n:::\n\n```{.r .cell-code}\n(teststat <- r*sqrt(78)/sqrt(1-r^2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.376557\n```\n:::\n:::\n\n\n\n$$T = \\frac{r\\sqrt{n-2}}{\\sqrt{1-r^2}} = \n\\frac{0.6410434\\sqrt{80-2}}{\\sqrt{1-0.6410434^2}} = 7.3765572 \\sim t_{78}$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# critical value for t78 with alpha = 0.05:\nqt(.975, df = 78)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.990847\n```\n:::\n:::\n\n\n\nSince $t = 7.376557 > 1.9908471$, we reject $H_0$.\n\n$p$-value approach:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pt(7.376557, df = 78, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.501287e-10\n```\n:::\n:::\n\n\n\nSince\n$p\\text{-value} = 1.5012873\\times 10^{-10} < 0.05$,\nwe reject $H_0$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(x = gapm$life_expectancy_years_2011, \n         y = gapm$female_literacy_rate_2011)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  gapm$life_expectancy_years_2011 and gapm$female_literacy_rate_2011\nt = 7.3766, df = 78, p-value = 1.501e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.4903981 0.7544916\nsample estimates:\n      cor \n0.6410434 \n```\n:::\n\n```{.r .cell-code}\ncor.test(x = gapm$life_expectancy_years_2011, \n         y = gapm$female_literacy_rate_2011) %>% tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 8\n  estimate statistic  p.value parameter conf.low conf.high method    alternative\n     <dbl>     <dbl>    <dbl>     <int>    <dbl>     <dbl> <chr>     <chr>      \n1    0.641      7.38 1.50e-10        78    0.490     0.754 Pearson'… two.sided  \n```\n:::\n\n```{.r .cell-code}\ncor.test(x = gapm$life_expectancy_years_2011, \n         y = gapm$female_literacy_rate_2011) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"uveiahkxkw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uveiahkxkw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uveiahkxkw thead, #uveiahkxkw tbody, #uveiahkxkw tfoot, #uveiahkxkw tr, #uveiahkxkw td, #uveiahkxkw th {\n  border-style: none;\n}\n\n#uveiahkxkw p {\n  margin: 0;\n  padding: 0;\n}\n\n#uveiahkxkw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uveiahkxkw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uveiahkxkw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uveiahkxkw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uveiahkxkw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uveiahkxkw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uveiahkxkw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uveiahkxkw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uveiahkxkw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uveiahkxkw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uveiahkxkw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uveiahkxkw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uveiahkxkw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uveiahkxkw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uveiahkxkw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uveiahkxkw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uveiahkxkw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uveiahkxkw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uveiahkxkw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uveiahkxkw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uveiahkxkw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uveiahkxkw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uveiahkxkw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uveiahkxkw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uveiahkxkw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uveiahkxkw .gt_left {\n  text-align: left;\n}\n\n#uveiahkxkw .gt_center {\n  text-align: center;\n}\n\n#uveiahkxkw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uveiahkxkw .gt_font_normal {\n  font-weight: normal;\n}\n\n#uveiahkxkw .gt_font_bold {\n  font-weight: bold;\n}\n\n#uveiahkxkw .gt_font_italic {\n  font-style: italic;\n}\n\n#uveiahkxkw .gt_super {\n  font-size: 65%;\n}\n\n#uveiahkxkw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uveiahkxkw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uveiahkxkw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uveiahkxkw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uveiahkxkw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uveiahkxkw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uveiahkxkw .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.6410434</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">78</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.4903981</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.7544916</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Pearson's product-moment correlation</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n## CI for $\\rho$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6410434\n```\n:::\n\n```{.r .cell-code}\n(tstar <- qt(.975, 78))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.990847\n```\n:::\n\n```{.r .cell-code}\n(SErho <- sqrt((1-r^2)/sqrt(78)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2582601\n```\n:::\n\n```{.r .cell-code}\nr + tstar*SErho\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.1552\n```\n:::\n\n```{.r .cell-code}\nr - tstar*SErho\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.126887\n```\n:::\n:::\n\n\n\n$$r \\pm t^* \\cdot \\frac{\\sqrt{1-r^2}}{\\sqrt{n-2}}\\\\\n0.6410434 \\pm 1.9908471 \\cdot 0.2582601\\\\\n(0.126887, 1.1551998) \\\\\n(0.126887, 1)$$\n\n## Testing $\\rho$ for some value $\\rho_0 \\neq 0$\n\n**Hypotheses**\n\n$$H_0: \\rho = \\rho_0 \\ \\ \\text{vs.} \\ \\ H_A: \\rho \\neq \\rho_0$$\n\n**Test statistic and probability distribution**\n\n-   When $\\rho \\neq 0$, the distribution of the test statistic we used\n    before is skewed\n-   Thus we apply Fisher's Z transformation:\n    $\\frac{1}{2} \\ln \\frac{1+r}{1-r}$, with which the test statistic has\n    an approximately standard normal distribution:\n\n$$Z = \\frac{\\frac{1}{2} \\ln \\frac{1+r}{1-r} - \\frac{1}{2} \\ln \\frac{1+\\rho_0}{1-\\rho_0}}{\\frac{1}{\\sqrt{n-3}}} \\sim N(0,1)$$\n\n**Decision**\n\n**Critical value** approach:\n\nLet $z_{1-\\alpha/2}$ be the critical value for the $N(0,1)$ distribution\nwith area $\\alpha/2$ in each of the tails.\n\n-   If $|Z| > z_{1-\\alpha/2}$, then reject $H_0$\n-   If $|Z| \\leq z_{1-\\alpha/2}$, then fail to reject $H_0$\n\n$p$-value approach:\n\n-   If $p$-value $< \\alpha$, then reject $H_0$\n-   If $p$-value $\\geq \\alpha$, then fail to reject $H_0$\n\n**Conclusion**\n\nIf $H_0$ is rejected, we conclude there is sufficient evidence that the\nlinear correlation between $X$ and $Y$ is significantly different from\n$\\rho_0$.\n\n### Example\n\nTest whether the correlation is different from 0.5.\n\n**Hypotheses**\n\n$$H_0: \\rho = 0.5 \\ \\ \\text{vs.} \\ \\ H_A: \\rho \\neq 0.5$$\n\n**Test statistic and probability distribution**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr # calculated previously\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6410434\n```\n:::\n\n```{.r .cell-code}\nrho0 <- 0.5\n(fisher_r <- 0.5*log((1+r)/(1-r)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.759943\n```\n:::\n\n```{.r .cell-code}\n(fisher_rho0 <- 0.5*log((1+rho0)/(1-rho0)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5493061\n```\n:::\n\n```{.r .cell-code}\n(z_stat <- (fisher_r - fisher_rho0) * sqrt(77))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.848331\n```\n:::\n:::\n\n\n\n$$Z = \\frac{\\frac{1}{2} \\ln \\frac{1+r}{1-r} - \\frac{1}{2} \\ln \\frac{1+\\rho_0}{1-\\rho_0}}{\\frac{1}{\\sqrt{n-3}}} \\\\\n= \\frac{\\frac{1}{2} \\ln \\frac{1+0.6410434}{1-0.6410434} - \\frac{1}{2} \\ln \\frac{1+0.5}{1-0.5}}{\\frac{1}{\\sqrt{80-3}}} \\\\\n= 1.8483309$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# critical value for N(0,1) with alpha = 0.05:\nqnorm(.975)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.959964\n```\n:::\n:::\n\n\n\nSince $Z = 1.848331 < 1.959964$, we fail to reject $H_0$.\n\n$p$-value approach:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pnorm(1.848331, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.06455447\n```\n:::\n:::\n\n\n\nSince\n$p\\text{-value} = 0.0645545 > 0.05$, we\nfail to reject $H_0$.\n\n**Conclusion**\n\nThere is insufficient evidence that the linear correlation between\ncountries' female literacy rate and average life expectancy is\nsignificantly different from 0.5 (p = 0.06).\n\n## CI for $\\rho$ when $\\rho \\neq 0$\n\n-   CI bounds for the Fisher transformed correlations:\n\n$$\\frac{1}{2} \\ln \\frac{1+r}{1-r} \\pm z^* \\cdot \\frac{1}{\\sqrt{n-3}}$$\n\\* After finding CI bounds ($z$), back transform the values to $r$:\n\n$$r = \\frac{e^{2z}-1}{e^{2z}+1}$$\n\n### Example: CI for $\\rho$ when $\\rho \\neq 0$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher_r\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.759943\n```\n:::\n\n```{.r .cell-code}\n(zstar <- qnorm(.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.959964\n```\n:::\n\n```{.r .cell-code}\n(SE_fisher <- 1/sqrt(77))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1139606\n```\n:::\n\n```{.r .cell-code}\n# Fisher transformed CI bounds\n(LB_fish <- fisher_r - zstar * SE_fisher)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5365844\n```\n:::\n\n```{.r .cell-code}\n(UB_fish <- fisher_r + zstar * SE_fisher)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9833016\n```\n:::\n\n```{.r .cell-code}\n# Back transform to r values\n(LB_r <- (exp(2*LB_fish) - 1)/(exp(2*LB_fish)+1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4903981\n```\n:::\n\n```{.r .cell-code}\n(UB_r <- (exp(2*UB_fish) - 1)/(exp(2*UB_fish)+1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7544916\n```\n:::\n:::\n\n\n\n-   CI bounds for the Fisher transformed correlations:\n\n$$\\frac{1}{2} \\ln \\frac{1+r}{1-r} \\pm z^* \\cdot \\frac{1}{\\sqrt{n-3}}\\\\\n\\frac{1}{2} \\ln \\frac{1+0.6410434}{1-0.6410434} \\pm 1.959964 \\cdot \\frac{1}{\\sqrt{77}}\\\\\n0.759943 \\pm 1.959964 \\cdot 0.1139606\\\\\n(0.5365844, 0.9833016)$$ \\* After finding CI bounds ($z$), back\ntransform the values to $r$:\n\n$$LB = \\frac{e^{2z}-1}{e^{2z}+1} = \\frac{e^{20.5365844}-1}{e^{20.5365844}+1} = 0.4903981\\\\\nUB = \\frac{e^{2z}-1}{e^{2z}+1} = \\frac{e^{20.9833016}-1}{e^{20.9833016}+1} = 0.7544916$$\n\nWe are 95% confident that the linear correlation coefficient between\ncountries' female literacy rate and average life expectancy is within\n(0.49, 0.75).\n\n## CI using `psych` package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First install the psych package\n# install.packages(\"psych\")\nlibrary(psych)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'psych'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:ggplot2':\n\n    %+%, alpha\n```\n:::\n\n```{.r .cell-code}\n# Fisher transformed values\nfisherz(0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5493061\n```\n:::\n\n```{.r .cell-code}\nfisherz(r)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.759943\n```\n:::\n\n```{.r .cell-code}\n# compare with values from computations above\nfisher_rho0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5493061\n```\n:::\n\n```{.r .cell-code}\nfisher_r\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.759943\n```\n:::\n\n```{.r .cell-code}\n#----\n# CI with back transformed values\nr.con(rho = r, n = 80, p=.95, twotailed=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4903981 0.7544916\n```\n:::\n\n```{.r .cell-code}\n# compare with values from computations above\nLB_r \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4903981\n```\n:::\n\n```{.r .cell-code}\nUB_r \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7544916\n```\n:::\n:::\n\n\n\n# $R^2$ = Coefficient of determination\n\nAnother way to assess model fit\n\n## $R^2$ = Coefficient of determination (1/2)\n\n-   Recall that the correlation coefficient $r$ measures the strength of\n    the linear relationship between two numerical variables\n-   $R^2$ is usually used to measure the strength of a *linear fit*\n    -   For a simple linear regression model (one numerical predictor),\n        $R^2$ is just the square of the correlation coefficient\n-   In general, $R^2$ is the proportion of the variability of the\n    dependent variable that is **explained** by the independent\n    variable(s)\n\n$$R^2 = \\frac{\\textrm{variance of predicted y-values}}\n{\\textrm{variance of observed y-values}} = \\frac{\\sum_{i=1}^n(\\widehat{y}_i-\\bar{y})^2}\n{\\sum_{i=1}^n(y_i-\\bar{y})^2} \n = \\frac{s_y^2 - s_{\\textrm{residuals}}^2}\n{s_y^2}$$ $$R^2 = 1- \\frac{s_{\\textrm{residuals}}^2}\n{s_y^2}$$ where $\\frac{s_{\\textrm{residuals}}^2}{s_y^2}$ is the\nproportion of \"unexplained\" variability in the $y$ values,\\\nand thus $R^2 = 1- \\frac{s_{\\textrm{residuls}}^2}{s_y^2}$ is the\nproportion of \"explained\" variability in the $y$ values\n\n## $R^2$ = Coefficient of determination (2/2)\n\n-   Recall, $-1<r<1$\n\n-   Thus, $0<R^2<1$\n\n-   In practice, we want \"high\" $R^2$ values, i.e. $R^2$ as close to 1\n    as possible.\n\nCalculating $R^2$ in R using `glance()` from the `broom` package:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.411         0.403  6.14      54.4 1.50e-10     1  -258.  521.  529.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n:::\n\n```{.r .cell-code}\nglance(model1)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4109366\n```\n:::\n:::\n\n\n\n::: callout-warning\n-   A model can have a high $R^2$ value when there is a curved pattern.\n-   Always first check whether a linear model is reasonable or not.\n:::\n\n## $R^2$ in `summary()` R output\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = life_expectancy_years_2011 ~ female_literacy_rate_2011, \n    data = gapm)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-22.299  -2.670   1.145   4.114   9.498 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               50.92790    2.66041  19.143  < 2e-16 ***\nfemale_literacy_rate_2011  0.23220    0.03148   7.377  1.5e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.142 on 78 degrees of freedom\n  (108 observations deleted due to missingness)\nMultiple R-squared:  0.4109,\tAdjusted R-squared:  0.4034 \nF-statistic: 54.41 on 1 and 78 DF,  p-value: 1.501e-10\n```\n:::\n:::\n\n\n\nCompare to the square of the correlation coefficient $r$:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- cor(x = gapm$life_expectancy_years_2011, \n    y = gapm$female_literacy_rate_2011,\n    use =  \"complete.obs\")\nr\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6410434\n```\n:::\n\n```{.r .cell-code}\nr^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4109366\n```\n:::\n:::\n",
    "supporting": [
      "05_SLR_Eval_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}