{
  "hash": "b10c7d4c8b6383d9b9b780acb78c4a41",
  "result": {
    "markdown": "---\ntitle: \"MLR: Inference\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#213c96\"\ndate: \"02/07/2024\"\ncategories: [\"Week 5\"]\nformat: \n  revealjs:\n    theme: [default, simple_NW.scss]\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: MLR 2\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n---\n\n\n\n\n# Learning Objectives\n\n1.  Interpret MLR (population) coefficient estimates with additional variable in model\n2.  Understand the use of the general F-test and interpret what it measures.\n3.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n4.  Understand the context of the **single covariate F-test**, conduct the needed hypothesis test, and interpret the results.\n5.  Understand the context of the **group of covariates F-test**, conduct the needed hypothesis test, and interpret the results.\n\n## Let's map that to our regression analysis process\n\n::: box\n![](images/arrow2.png){.absolute top=\"13.5%\" right=\"62.1%\" width=\"155\"} ![](images/arrow2.png){.absolute top=\"13.5%\" right=\"28.4%\" width=\"155\"}![](images/arrow_back4.png){.absolute top=\"7.5%\" right=\"30.5%\" width=\"820\"} ![](images/arrow_down.png){.absolute top=\"60.5%\" right=\"48%\" width=\"85\"}\n\n::: columns\n::: {.column width=\"30%\"}\n::: RAP1\n::: RAP1-title\nModel Selection\n:::\n\n::: RAP1-cont\n-   Building a model\n\n-   Selecting variables\n\n-   Prediction vs interpretation\n\n-   Comparing potential models\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP2\n::: RAP2-title\nModel Fitting\n:::\n\n::: RAP2-cont\n-   Find best fit line\n\n-   Using OLS in this class\n\n-   Parameter estimation\n\n-   Categorical covariates\n\n-   Interactions\n:::\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: RAP3\n::: RAP3-title\nModel Evaluation\n:::\n\n::: RAP3-cont\n-   Evaluation of model fit\n-   Testing model assumptions\n-   Residuals\n-   Transformations\n-   Influential points\n-   Multicollinearity\n:::\n:::\n:::\n:::\n:::\n\n::: RAP4\n::: RAP4-title\nModel Use (Inference)\n:::\n\n::: RAP4-cont\n::: columns\n::: {.column width=\"50%\"}\n-   Inference for coefficients\n-   Hypothesis testing for coefficients\n:::\n\n::: {.column width=\"50%\"}\n-   Inference for expected $Y$ given $X$\n:::\n:::\n:::\n:::\n\n# Learning Objectives\n\n::: lob\n1.  Interpret MLR (population) coefficient estimates with additional variable in model\n:::\n2.  Understand the use of the general F-test and interpret what it measures.\n3.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n4.  Understand the context of the **single covariate F-test**, conduct the needed hypothesis test, and interpret the results.\n5.  Understand the context of the **group of covariates F-test**, conduct the needed hypothesis test, and interpret the results.\n\n## Interpreting the estimated population coefficients\n\n-   For a population model: $$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2+ \\epsilon$$\n    -   Where $X_1$ and $X_2$ are continuous variables\n    -   No need to specify $Y$ because it required to be continuous in linear regression\n\n::: columns\n::: {.column width=\"33%\"}\n::: fact\n::: fact-title\nGeneral interpretation for $\\widehat{\\beta}_0$\n:::\n\n::: fact-cont\nThe expected $Y$-variable is ($\\widehat\\beta_0$ units) when the $X_1$-variable is 0 $X_1$-units and $X_2$-variable is 0 $X_1$-units (95% CI: LB, UB).\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nGeneral interpretation for $\\widehat{\\beta}_1$\n:::\n\n::: def-cont\nFor every increase of 1 $X_1$-unit in the $X_1$-variable, adjusting/controlling for $X_2$-variable, there is an expected increase/decrease of $|\\widehat\\beta_1|$ units in the $Y$-variable (95%: LB, UB).\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nGeneral interpretation for $\\widehat{\\beta}_2$\n:::\n\n::: proof-cont\nFor every increase of 1 $X_2$-unit in the $X_2$-variable, adjusting/controlling for $X_1$-variable, there is an expected increase/decrease of $|\\widehat\\beta_2|$ units in the $Y$-variable (95%: LB, UB).\n:::\n:::\n:::\n:::\n\n## Getting these interpretations from our regression table\n\nWe fit the regression model in R and printed the regression table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmr1 <- lm(LifeExpectancyYrs ~ FemaleLiteracyRate + FoodSupplykcPPD, \n          data = gapm_sub)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"lwprhrgdbj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lwprhrgdbj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lwprhrgdbj thead, #lwprhrgdbj tbody, #lwprhrgdbj tfoot, #lwprhrgdbj tr, #lwprhrgdbj td, #lwprhrgdbj th {\n  border-style: none;\n}\n\n#lwprhrgdbj p {\n  margin: 0;\n  padding: 0;\n}\n\n#lwprhrgdbj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 30px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lwprhrgdbj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lwprhrgdbj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lwprhrgdbj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lwprhrgdbj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lwprhrgdbj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lwprhrgdbj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lwprhrgdbj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lwprhrgdbj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lwprhrgdbj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lwprhrgdbj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lwprhrgdbj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lwprhrgdbj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lwprhrgdbj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lwprhrgdbj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwprhrgdbj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lwprhrgdbj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lwprhrgdbj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lwprhrgdbj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwprhrgdbj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lwprhrgdbj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwprhrgdbj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lwprhrgdbj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwprhrgdbj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lwprhrgdbj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwprhrgdbj .gt_left {\n  text-align: left;\n}\n\n#lwprhrgdbj .gt_center {\n  text-align: center;\n}\n\n#lwprhrgdbj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lwprhrgdbj .gt_font_normal {\n  font-weight: normal;\n}\n\n#lwprhrgdbj .gt_font_bold {\n  font-weight: bold;\n}\n\n#lwprhrgdbj .gt_font_italic {\n  font-style: italic;\n}\n\n#lwprhrgdbj .gt_super {\n  font-size: 65%;\n}\n\n#lwprhrgdbj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lwprhrgdbj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lwprhrgdbj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lwprhrgdbj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lwprhrgdbj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lwprhrgdbj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lwprhrgdbj .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">33.595</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">4.472</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.512</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">24.674</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">42.517</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">FemaleLiteracyRate</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.157</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.032</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.873</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.093</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.221</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">FoodSupplykcPPD</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.008</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.002</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.726</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.005</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.012</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nFitted multiple regression model: $\\widehat{\\text{LE}} = 33.595 + 0.157 \\text{ FLR} + 0.008 \\text{ FS}$\n\n::: columns\n::: {.column width=\"33%\"}\n::: fact\n::: fact-title\nInterpretation for $\\widehat{\\beta}_0$\n:::\n\n::: fact-cont\nThe expected life expectancy is 33.595 years when the female literacy rate is 0% and food supply is 0 0 kcal PPD (95% CI: 24.674, 41.517).\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nInterpretation for $\\widehat{\\beta}_1$\n:::\n\n::: def-cont\nFor every 1% increase in the female literacy rate, adjusting for food supply, there is an expected increase of 0.157 years in the life expectancy (95%: 0.093, 0.221).\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nInterpretation for $\\widehat{\\beta}_2$\n:::\n\n::: proof-cont\nFor every 1 kcal PPD increase in the food supply, adjusting for female literacy rate, there is an expected increase of 0.008 years in life expectancy (95%: 0.005, 0.012).\n:::\n:::\n:::\n:::\n\n## Let's just examine the general interpretation vs. the example {.smaller}\n\n::: columns\n::: {.column width=\"33%\"}\n::: fact\n::: fact-title\nGeneral interpretation for $\\widehat{\\beta}_0$\n:::\n\n::: fact-cont\nThe expected $Y$-variable is ($\\widehat\\beta_0$ units) when the $X_1$-variable is 0 $X_1$-units and $X_2$-variable is 0 $X_1$-units (95% CI: LB, UB).\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nGeneral interpretation for $\\widehat{\\beta}_1$\n:::\n\n::: def-cont\nFor every increase of 1 $X_1$-unit in the $X_1$-variable, adjusting/controlling for $X_2$-variable, there is an expected increase/decrease of $|\\widehat\\beta_1|$ units in the $Y$-variable (95%: LB, UB).\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nGeneral interpretation for $\\widehat{\\beta}_2$\n:::\n\n::: proof-cont\nFor every increase of 1 $X_2$-unit in the $X_2$-variable, adjusting/controlling for $X_1$-variable, there is an expected increase/decrease of $|\\widehat\\beta_2|$ units in the $Y$-variable (95%: LB, UB).\n:::\n:::\n:::\n:::\n\n::: columns\n::: {.column width=\"33%\"}\n::: fact\n::: fact-title\nInterpretation for $\\widehat{\\beta}_0$\n:::\n\n::: fact-cont\nThe expected life expectancy is 33.595 years when the female literacy rate is 0% and food supply is 0 0 kcal PPD (95% CI: 24.674, 41.517).\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nInterpretation for $\\widehat{\\beta}_1$\n:::\n\n::: def-cont\nFor every 1% increase in the female literacy rate, adjusting for food supply, there is an expected increase of 0.157 years in the life expectancy (95%: 0.093, 0.221).\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nInterpretation for $\\widehat{\\beta}_2$\n:::\n\n::: proof-cont\nFor every 1 kcal PPD increase in the food supply, adjusting for female literacy rate, there is an expected increase of 0.008 years in life expectancy (95%: 0.005, 0.012).\n:::\n:::\n:::\n:::\n\n## What we need in our interpretations of coefficients (reference)\n\n::: columns\n::: column\n-   Units of Y\n\n-   Units of X\n\n-   Discussing intercept: Mean or average or expected before Y\n\n-   Discussing coefficient for continuous covariate: Mean or average or expected before difference, increase, or decrease\n\n    -   OR: Mean or average or expected before Y\n    -   Only need before difference or Y!!\n\n-   Confidence interval\n:::\n\n::: column\n-   If other covariates in the model\n\n    -   Discussing intercept: Must state that variables are equal to 0\n\n        -   or at their centered value if centered!\n\n    -   Discussing coefficient for covariate: Must state \"adjusting for all other variables\", \"Controlling for all other variables\", or \"Holding all other variables constant\"\n\n        -   If only one other variable in the model, then replace \"all other variables\" with the single variable name\n:::\n:::\n\n# Learning Objectives\n\n1.  Interpret MLR (population) coefficient estimates with additional variable in model\n\n::: lob\n2.  Understand the use of the general F-test and interpret what it measures.\n:::\n3.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n4.  Understand the context of the **single covariate F-test**, conduct the needed hypothesis test, and interpret the results.\n5.  Understand the context of the **group of covariates F-test**, conduct the needed hypothesis test, and interpret the results.\n\n## We must revisit our dear friend, the F-test!\n\n![https://www.writerswrite.co.za/foreshadowing/](09_MLR_Inference/foreshadowing.jpg){fig-align=\"center\"}\n\n## *Remember from Lesson 5:* F-test vs. t-test for the population slope\n\nThe square of a $t$-distribution with $df = \\nu$ is an $F$-distribution with $df = 1, \\nu$\n\n$$T_{\\nu}^2 \\sim F_{1,\\nu}$$\n\n-   We can use **either F-test** or **t-test** to run the following hypothesis test:\n\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n```\n\n-   Note that the F-test does not support one-sided alternative tests, but the t-test does!\n\n## *Remember from Lesson 5:* Planting a seed about the F-test\n\nWe can think about the hypothesis test for the slope...\n\n::: columns\n::: {.column width=\"17%\"}\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_1=0$\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$\\beta_1\\neq0$\n:::\n:::\n:::\n:::\n\nin a slightly different way...\n\n::: columns\n::: {.column width=\"17%\"}\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nNull model ($\\beta_1=0$)\n:::\n\n::: proof-cont\n-   $Y = \\beta_0 + \\epsilon$\n-   Smaller (reduced) model\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nAlternative model ($\\beta_1\\neq0$)\n:::\n\n::: def-cont\n-   $Y = \\beta_0 + \\beta_1 X + \\epsilon$\n-   Larger (full) model\n:::\n:::\n:::\n:::\n\n-   In multiple linear regression, we can start using this framework to test multiple coefficient parameters at once\n\n    -   Decide whether or not to reject the smaller reduced model in favor of the larger full model\n\n    -   Cannot do this with the t-test!\n\n## We can extend this!!\n\nWe can create a hypothesis test for more than one coefficient at a time...\n\n::: columns\n::: {.column width=\"17%\"}\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_1=\\beta_2=0$\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$\\beta_1\\neq0$ and/or $\\beta_2\\neq0$\n:::\n:::\n:::\n:::\n\nin a slightly different way...\n\n::: columns\n::: {.column width=\"17%\"}\n:::\n\n::: {.column width=\"33%\"}\n::: proof1\n::: proof-title\nNull model\n:::\n\n::: proof-cont\n-   $Y = \\beta_0 + \\epsilon$\n-   Smaller (reduced) model\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: definition\n::: def-title\nAlternative\\* model\n:::\n\n::: def-cont\n-   $Y = \\beta_0 + \\beta_1 X + \\beta_2 X + \\epsilon$\n-   Larger (full) model\n:::\n:::\n:::\n:::\n\n\\*This is **not quite** the alternative, but if we reject the null, then this is the model we move forward with\n\n## Building a very important toolkit: three types of tests\n\n::: fact\n::: fact-title\nOverall test\n:::\n\n::: fact-cont\nDoes at least one of the covariates/predictors contribute significantly to the prediction of Y?\n:::\n:::\n\n::: example\n::: ex-title\nTest for addition of a single variable (covariate subset test)\n:::\n\n::: ex-cont\nDoes the addition of one particular covariate add significantly to the prediction of Y achieved by other covariates already present in the model?\n:::\n:::\n\n::: proposition\n::: prop-title\nTest for addition of group of variables (covariate subset test)\n:::\n\n::: prop-cont\nDoes the addition of some group of covariates add significantly to the prediction of Y achieved by other covariates already present in the model?\n:::\n:::\n\n## Variation: Explained vs. Unexplained\n\n$$\\begin{aligned}\n\\sum_{i=1}^n (Y_i - \\overline{Y})^2 &= \\sum_{i=1}^n (\\widehat{Y}_i- \\overline{Y})^2 + \\sum_{i=1}^n (Y_i - \\widehat{Y}_i)^2 \\\\\nSSY &= SSR + SSE\n\\end{aligned}$$\n\n-   $Y_i - \\overline{Y}$ = the deviation of $Y_i$ around the mean $\\overline{Y}$\n    -   (the **total** amount deviation unexplained at $X_{i1},\\ldots,X_{ik}$ ).\n-   $\\widehat{Y}_i- \\overline{Y}$ = the deviation of the fitted value $\\widehat{Y}_i$ around the mean $\\overline{Y}$\n    -   (the amount deviation **explained** by the regression at $X_{i1},\\ldots,X_{ik}$ ).\n-   $Y_i - \\widehat{Y}_i$ = the deviation of the observation $Y$ around the fitted regression line\n    -   (the amount deviation **unexplained** by the regression at $X_{i1},\\ldots,X_{ik}$ )\n\n## Another way to think of SSY, SSR, and SSE\n\n-   Let's create a data frame of each component within the SS's\n\n    -   Difference in SSY: $Y_i - \\overline{Y}$\n    -   Difference in SSR: $\\widehat{Y}_i- \\overline{Y}$\n    -   Difference in SSE: $Y_i - \\widehat{Y}_i$\n\n-   Using our simple linear regression model as an example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslr1 = lm(LifeExpectancyYrs ~ FemaleLiteracyRate, data = gapm_sub)\naug_slr1 = augment(slr1)\nSS_df = gapm_sub %>% select(LifeExpectancyYrs) %>%\n  mutate(SSY_diff = LifeExpectancyYrs - mean(LifeExpectancyYrs),\n         y_fit = aug_slr1$.fitted, \n         SSR_diff = y_fit - mean(LifeExpectancyYrs), \n         SSE_diff = aug_slr1$.resid)\n```\n:::\n\n\n## Plot the components of each sum of squares\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSSY_plot = ggplot(SS_df, aes(SSY_diff)) + geom_histogram() + xlim(-30, 30) + ylim(0, 35) \nSSR_plot = ggplot(SS_df, aes(SSR_diff)) + geom_histogram() + xlim(-30, 30) + ylim(0, 35) \nSSE_plot = ggplot(SS_df, aes(SSE_diff)) + geom_histogram() + xlim(-30, 30) + ylim(0, 35) \ngrid.arrange(SSY_plot, SSR_plot, SSE_plot, nrow = 3)\n```\n:::\n\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"right\"}\n::: {.cell-output-display}\n![](09_MLR_Inference_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='right' width=576}\n:::\n:::\n\n:::\n\n::: column\n$$SSY = \\sum_{i=1}^n (Y_i - \\overline{Y})^2 = 64.64$$ \n\n$$SSR = \\sum_{i=1}^n (\\widehat{Y}_i- \\overline{Y})^2 = 27.24$$\n\n$$SSE =\\sum_{i=1}^n (Y_i - \\widehat{Y}_i)^2 = 37.39$$\n:::\n:::\n\n## When running a F-test for linear models...\n\n-   We need to define a larger, full model (more parameters)\n-   We need to define a smaller, reduced model (fewer parameters)\n-   Use the F-statistic to decide whether or not we reject the smaller model\n    -   The F-statistic compares the SSE of each model to determine if the full model explains a significant amount of additional variance\n\n::: columns\n::: {.column width=\"30%\"}\n \n\n$$\nF = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}\n$$\n:::\n\n::: {.column width=\"70%\"}\n-   $SSE(R) \\geq SSE(F)$\n-   Numerator measures difference in **unexplained** variation between the models\n    -   Big difference = added parameters greatly reduce the unexplained variation (increase explained variation)\n    -   Smaller difference = added parameters don't reduce the unexplained variation\n-   Take ratio of difference to the unexplained variation in the full model\n:::\n:::\n\n## We will keep working with the MLR model from last class\n\nNew population model for example:\n\n$$\\text{Life expectancy} = \\beta_0 + \\beta_1 \\text{Female literacy rate} + \\beta_2 \\text{Food supply} + \\epsilon$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit regression model:\nmr1 <- lm(LifeExpectancyYrs ~ FemaleLiteracyRate + FoodSupplykcPPD, \n          data = gapm_sub)\ntidy(mr1, conf.int=T) %>% gt() %>% tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"izfubgbgpz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#izfubgbgpz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#izfubgbgpz thead, #izfubgbgpz tbody, #izfubgbgpz tfoot, #izfubgbgpz tr, #izfubgbgpz td, #izfubgbgpz th {\n  border-style: none;\n}\n\n#izfubgbgpz p {\n  margin: 0;\n  padding: 0;\n}\n\n#izfubgbgpz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#izfubgbgpz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#izfubgbgpz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#izfubgbgpz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#izfubgbgpz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#izfubgbgpz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#izfubgbgpz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#izfubgbgpz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#izfubgbgpz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#izfubgbgpz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#izfubgbgpz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#izfubgbgpz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#izfubgbgpz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#izfubgbgpz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#izfubgbgpz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izfubgbgpz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#izfubgbgpz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#izfubgbgpz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#izfubgbgpz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izfubgbgpz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#izfubgbgpz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izfubgbgpz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#izfubgbgpz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izfubgbgpz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#izfubgbgpz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izfubgbgpz .gt_left {\n  text-align: left;\n}\n\n#izfubgbgpz .gt_center {\n  text-align: center;\n}\n\n#izfubgbgpz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#izfubgbgpz .gt_font_normal {\n  font-weight: normal;\n}\n\n#izfubgbgpz .gt_font_bold {\n  font-weight: bold;\n}\n\n#izfubgbgpz .gt_font_italic {\n  font-style: italic;\n}\n\n#izfubgbgpz .gt_super {\n  font-size: 65%;\n}\n\n#izfubgbgpz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#izfubgbgpz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#izfubgbgpz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#izfubgbgpz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#izfubgbgpz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#izfubgbgpz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#izfubgbgpz .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">33.595</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">4.472</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.512</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">24.674</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">42.517</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">FemaleLiteracyRate</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.157</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.032</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.873</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.093</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.221</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">FoodSupplykcPPD</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.008</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.002</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.726</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.005</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.012</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nFitted multiple regression model:\n\n$$\\begin{aligned}\n\\widehat{\\text{Life expectancy}} &= \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\text{Female literacy rate} + \\widehat{\\beta}_2 \\text{Food supply} \\\\\n\\widehat{\\text{Life expectancy}} &= 33.595 + 0.157\\ \\text{Female literacy rate} \n+ 0.008\\ \\text{Food supply}\n\\end{aligned}$$\n\n# Learning Objectives\n\n1.  Interpret MLR (population) coefficient estimates with additional variable in model\n2.  Understand the use of the general F-test and interpret what it measures.\n\n::: lob\n3.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n:::\n4.  Understand the context of the **single covariate F-test**, conduct the needed hypothesis test, and interpret the results.\n5.  Understand the context of the **group of covariates F-test**, conduct the needed hypothesis test, and interpret the results.\n\n## Overall F-test\n\nDoes at least one of the covariates/predictors contribute significantly to the prediction of Y?\n\n-   For a general population MLR model, $$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2+ \\ldots + \\beta_k X_k + \\epsilon$$\n\nWe can create a hypothesis test for all the covariate coefficients...\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_1=\\beta_2= \\ldots=\\beta_k=0$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\nAt least one $\\beta_j\\neq0$ (for $j=1, 2, \\ldots, k$)\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$Y = \\beta_0 + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\ldots + \\beta_k X_k + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n## Overall F-test: general steps for hypothesis test\n\n::: columns\n::: {.column width=\"48%\"}\n::: highlight-container\n::: highlight\n1.  Met underlying LINE assumptions\n:::\n:::\n\n::: highlight-container\n::: highlight\n2.  State the null hypothesis\n:::\n:::\n\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1=\\beta_2= \\ldots=\\beta_k=0\\\\\n\\text{vs. } H_A&: \\text{At least one } \\beta_j\\neq0, \\text{for }j=1, 2, \\ldots, k\n\\end{align}\n```\n\n::: highlight-container\n::: highlight\n3.  Specify the significance level.\n:::\n:::\n\nOften we use $\\alpha = 0.05$\n\n::: highlight-container\n::: highlight\n4.  Specify the test statistic and its distribution under the null\n:::\n:::\n\nThe test statistic is $F$, and follows an F-distribution with numerator $df=k$ and denominator $df=n-k-1$. ($n$ = \\# obversation, $k$ = \\# covariates)\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n::: highlight-container\n::: highlight\n5.  Compute the value of the test statistic\n:::\n:::\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}} = \\frac{MSR_{full}}{MSE_{full}}$$\n\n::: highlight-container\n::: highlight\n6.  Calculate the p-value\n:::\n:::\n\nWe are generally calculating: $P(F_{k, n-k-1} > F)$\n\n::: highlight-container\n::: highlight\n7.  Write conclusion for hypothesis test\n:::\n:::\n\n-   Reject if: $P(F_{k, n-k-1} > F) < \\alpha$\n\nWe (reject/fail to reject) the null hypothesis at the $100\\alpha\\%$ significance level. There is (sufficient/insufficient) evidence that at least one predictor's coefficient is not 0 (p-value = $P(F_{1, n-2} > F)$).\n:::\n:::\n\n## Overall F-test: a word on the conclusion\n\n-   If $H_0$ is rejected, we conclude there is sufficient evidence that at least one predictor's coefficient is different from zero.\n-   Same as: at least one independent variable contributes significantly to the prediction of $Y$\n\n \n\n-   If $H_0$ is not rejected, we conclude there is insufficient evidence that at least one predictor's coefficient is different from zero.\n-   Same as: Not enough evidence that at least one independent variable contributes significantly to the prediction of $Y$\n\n## Let's think about our MLR example for life expectancy\n\nOur proposed population model\n\n$$\\text{LE} = \\beta_0 + \\beta_1 \\text{FLR} + \\beta_2 \\text{FS} + \\epsilon$$\n\nFitted multiple regression model:\n\n$$\\begin{aligned}\n\\widehat{\\text{LE}} &= \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\text{FLR} + \\widehat{\\beta}_2 \\text{FS} \\\\\n\\widehat{\\text{LE}} &= 33.595 + 0.157\\ \\text{FLR} \n+ 0.008\\ \\text{FS}\n\\end{aligned}$$\n\n**Our main question for the Overall F-test:** Is the regression model containing female literacy rate and food supply useful in estimating countries' life expectancy?\n\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$LE = \\beta_0 + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$LE = \\beta_0 + \\beta_1 FLR + \\beta_2 FS + \\epsilon$\n:::\n:::\n:::\n:::\n\n## Comparing the SSY, SSR, and SSE for reduced and full model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_red1 = lm(LifeExpectancyYrs ~ 1, data = gapm_sub)\naug_red1  = augment(mod_red1)\n\nmod_full1 = lm(LifeExpectancyYrs ~ FemaleLiteracyRate + FoodSupplykcPPD,\n               data = gapm_sub)\naug_full1  = augment(mod_full1)\n\nSS_df2 = gapm_sub %>% select(LifeExpectancyYrs) %>%\n  mutate(SSY_diff_r1 = LifeExpectancyYrs - mean(LifeExpectancyYrs),\n         SSR_diff_r1 = aug_red1$.fitted - mean(LifeExpectancyYrs), \n         SSE_diff_r1 = aug_red1$.resid, \n         SSY_diff_f1 = LifeExpectancyYrs - mean(LifeExpectancyYrs),\n         SSR_diff_f1 = aug_full1$.fitted - mean(LifeExpectancyYrs), \n         SSE_diff_f1 = aug_full1$.resid)\n```\n:::\n\n\n## Comparing the SSY, SSR, and SSE for reduced and full model\n\n::: columns\n::: column\n**Reduced / null model** $$LE = \\beta_0 + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_MLR_Inference_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 64.64$$ \n\n \n\n$$SSR = 0$$\n\n \n\n$$SSE = 64.64$$\n:::\n\n:::\n\n:::\n\n::: column\n**Full / Alternative model** $$LE = \\beta_0 + \\beta_1 FLR + \\beta_2 FS + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_MLR_Inference_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 64.64$$ \n\n \n\n$$SSR = 36.39$$\n\n \n\n$$SSE = 28.25$$\n:::\n\n:::\n\n:::\n:::\n\n## Poll Everywhere Question\n\n\n\n## So let's step through our hypothesis test (1/3)\n\n::: highlight-container\n::: highlight\n1.  Met underlying LINE assumptions\n:::\n:::\n\n \n\n::: highlight-container\n::: highlight\n2.  State the null hypothesis\n:::\n:::\n\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1=\\beta_2=0\\\\\n\\text{vs. } H_A&: \\text{At least one } \\beta_1\\neq0 \\text{ or } \\beta_2\\neq0\n\\end{align}\n```\n\n::: highlight-container\n::: highlight\n3.  Specify the significance level\n:::\n:::\n\nOften we use $\\alpha = 0.05$\n\n::: highlight-container\n::: highlight\n4.  Specify the test statistic and its distribution under the null\n:::\n:::\n\nThe test statistic is $F$, and follows an F-distribution with numerator $df=k =2$ and denominator $df=n-k-1 = 72 - 2-1=69$. ($n$ = \\# obversation, $k$ = \\# covariates)\n\n## So let's step through our hypothesis test (2/3)\n\n::: highlight-container\n::: highlight\n5.  Compute the value of the test statistic / 6.  Calculate the p-value\n:::\n:::\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}=44.443$$\nOR use ANOVA table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_red1, mod_full1) %>% tidy() %>% gt() %>% tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"fsfconxpgp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fsfconxpgp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fsfconxpgp thead, #fsfconxpgp tbody, #fsfconxpgp tfoot, #fsfconxpgp tr, #fsfconxpgp td, #fsfconxpgp th {\n  border-style: none;\n}\n\n#fsfconxpgp p {\n  margin: 0;\n  padding: 0;\n}\n\n#fsfconxpgp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fsfconxpgp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fsfconxpgp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fsfconxpgp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fsfconxpgp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fsfconxpgp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fsfconxpgp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fsfconxpgp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fsfconxpgp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fsfconxpgp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fsfconxpgp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fsfconxpgp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fsfconxpgp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fsfconxpgp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fsfconxpgp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsfconxpgp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fsfconxpgp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fsfconxpgp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fsfconxpgp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsfconxpgp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fsfconxpgp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsfconxpgp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fsfconxpgp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsfconxpgp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fsfconxpgp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsfconxpgp .gt_left {\n  text-align: left;\n}\n\n#fsfconxpgp .gt_center {\n  text-align: center;\n}\n\n#fsfconxpgp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fsfconxpgp .gt_font_normal {\n  font-weight: normal;\n}\n\n#fsfconxpgp .gt_font_bold {\n  font-weight: bold;\n}\n\n#fsfconxpgp .gt_font_italic {\n  font-style: italic;\n}\n\n#fsfconxpgp .gt_super {\n  font-size: 65%;\n}\n\n#fsfconxpgp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fsfconxpgp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fsfconxpgp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fsfconxpgp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fsfconxpgp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fsfconxpgp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fsfconxpgp .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ 1</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">71.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">4,589.119</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ FemaleLiteracyRate + FoodSupplykcPPD</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">69.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">2,005.556</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">2,583.563</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">44.443</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## So let's step through our hypothesis test (3/3)\n\n::: highlight-container\n::: highlight\n7.  Write conclusion for hypothesis test\n:::\n:::\n\n \n\nWe reject the null hypothesis at the 5% significance level. There is sufficient evidence that either countries' female literacy rate or the food supply (or both) contributes significantly to the prediction of life expectancy (p-value < 0.001).\n\n# Learning Objectives\n\n1.  Interpret MLR (population) coefficient estimates with additional variable in model\n2.  Understand the use of the general F-test and interpret what it measures.\n3.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n\n::: lob\n4.  Understand the context of the **single covariate F-test**, conduct the needed hypothesis test, and interpret the results.\n:::\n5.  Understand the context of the **group of covariates F-test**, conduct the needed hypothesis test, and interpret the results.\n\n## Covariate subset test: Single variable\n\nDoes the addition of one particular covariate of interest add significantly to the prediction of Y achieved by other covariates already present in the model?\n\n-   For a general population MLR model, $$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2+ \\beta_j X_j +\\ldots + \\beta_k X_k + \\epsilon$$\n\nWe can create a hypothesis test for a single $j$ covariate coefficient (where $j$ can be any value $1, 2, \\ldots, k$)...\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_j=0$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$\\beta_j\\neq0$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\ldots + \\beta_k X_k + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$\\begin{aligned}Y = &\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_j X_j +\\\\ &\\ldots + \\beta_k X_k + \\epsilon \\end{aligned}$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n## Single covariate F-test: general steps for hypothesis test (reference)\n\n::: columns\n::: {.column width=\"48%\"}\n::: highlight-container\n::: highlight\n1.  Met underlying LINE assumptions\n:::\n:::\n\n::: highlight-container\n::: highlight\n2.  State the null hypothesis\n:::\n:::\n\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_j=0\\\\\n\\text{vs. } H_A&: \\beta_j\\neq 0\n\\end{align}\n```\n\n::: highlight-container\n::: highlight\n3.  Specify the significance level\n:::\n:::\n\nOften we use $\\alpha = 0.05$\n\n::: highlight-container\n::: highlight\n4.  Specify the test statistic and its distribution under the null\n:::\n:::\n\nThe test statistic is $F$, and follows an F-distribution with numerator $df=k$ and denominator $df=n-k-1$. ($n$ = \\# obversation, $k$ = \\# covariates)\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n::: highlight-container\n::: highlight\n5.  Compute the value of the test statistic\n:::\n:::\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}$$\n\n::: highlight-container\n::: highlight\n6.  Calculate the p-value\n:::\n:::\n\nWe are generally calculating: $P(F_{k, n-k-1} > F)$\n\n::: highlight-container\n::: highlight\n7.  Write conclusion for hypothesis test\n:::\n:::\n\nWe (reject/fail to reject) the null hypothesis at the $100\\alpha\\%$ significance level. There is (sufficient/insufficient) evidence that predictor/covariate $j$ significantly improves the prediction of Y, given all the other covariates are in the model (p-value = $P(F_{1, n-2} > F)$).\n:::\n:::\n\n## Let's think about our MLR example for life expectancy\n\nOur proposed population model\n\n$$\\text{LE} = \\beta_0 + \\beta_1 \\text{FLR} + \\beta_2 \\text{FS} + \\epsilon$$\n\nFitted multiple regression model:\n\n$$\\begin{aligned}\n\\widehat{\\text{LE}} &= \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\text{FLR} + \\widehat{\\beta}_2 \\text{FS} \\\\\n\\widehat{\\text{LE}} &= 33.595 + 0.157\\ \\text{FLR} \n+ 0.008\\ \\text{FS}\n\\end{aligned}$$\n\n**Our main question for the single covariate subset F-test:** Is the regression model containing food supply improve the estimation of countries' life expectancy, given female literacy rate is already in the model?\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$LE = \\beta_0 + \\beta_1 FLR + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$LE = \\beta_0 + \\beta_1 FLR + \\beta_2 FS + \\epsilon$\n:::\n:::\n:::\n:::\n\n## Comparing the SSY, SSR, and SSE for reduced and full model\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: column\n**Reduced / null model** $$LE = \\beta_0 + \\beta_1 FLR + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_MLR_Inference_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 64.64$$ \n\n \n\n$$SSR = 27.24$$\n\n \n\n$$SSE = 37.39$$\n:::\n\n:::\n\n:::\n\n::: column\n**Full / Alternative model** $$LE = \\beta_0 + \\beta_1 FLR + \\beta_2 FS + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_MLR_Inference_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 64.64$$ \n\n \n\n$$SSR = 36.39$$\n\n \n\n$$SSE = 28.25$$\n:::\n\n:::\n\n:::\n:::\n\n## So let's step through our hypothesis test (1/3)\n\n::: highlight-container\n::: highlight\n1.  Met underlying LINE assumptions\n:::\n:::\n\n \n\n::: highlight-container\n::: highlight\n2.  State the null hypothesis\n:::\n:::\n\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_2=0\\\\\n\\text{vs. } H_A&: \\beta_2\\neq0 \n\\end{align}\n```\n\n::: highlight-container\n::: highlight\n3.  Specify the significance level\n:::\n:::\n\nOften we use $\\alpha = 0.05$\n\n::: highlight-container\n::: highlight\n4.  Specify the test statistic and its distribution under the null\n:::\n:::\n\nThe test statistic is $F$, and follows an F-distribution with numerator $df=k =2$ and denominator $df=n-k-1 = 72 - 2-1=69$. ($n$ = \\# obversation, $k$ = \\# covariates)\n\n## So let's step through our hypothesis test (2/3)\n\n::: highlight-container\n::: highlight\n5.  Compute the value of the test statistic / 6.  Calculate the p-value\n:::\n:::\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}$$\nANOVA table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_red2, mod_full2) %>% tidy() %>% gt() %>% tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ysqcvjdkqi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ysqcvjdkqi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ysqcvjdkqi thead, #ysqcvjdkqi tbody, #ysqcvjdkqi tfoot, #ysqcvjdkqi tr, #ysqcvjdkqi td, #ysqcvjdkqi th {\n  border-style: none;\n}\n\n#ysqcvjdkqi p {\n  margin: 0;\n  padding: 0;\n}\n\n#ysqcvjdkqi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ysqcvjdkqi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ysqcvjdkqi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ysqcvjdkqi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ysqcvjdkqi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ysqcvjdkqi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ysqcvjdkqi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ysqcvjdkqi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ysqcvjdkqi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ysqcvjdkqi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ysqcvjdkqi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ysqcvjdkqi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ysqcvjdkqi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ysqcvjdkqi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ysqcvjdkqi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ysqcvjdkqi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ysqcvjdkqi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ysqcvjdkqi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ysqcvjdkqi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ysqcvjdkqi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ysqcvjdkqi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ysqcvjdkqi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ysqcvjdkqi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ysqcvjdkqi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ysqcvjdkqi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ysqcvjdkqi .gt_left {\n  text-align: left;\n}\n\n#ysqcvjdkqi .gt_center {\n  text-align: center;\n}\n\n#ysqcvjdkqi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ysqcvjdkqi .gt_font_normal {\n  font-weight: normal;\n}\n\n#ysqcvjdkqi .gt_font_bold {\n  font-weight: bold;\n}\n\n#ysqcvjdkqi .gt_font_italic {\n  font-style: italic;\n}\n\n#ysqcvjdkqi .gt_super {\n  font-size: 65%;\n}\n\n#ysqcvjdkqi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ysqcvjdkqi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ysqcvjdkqi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ysqcvjdkqi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ysqcvjdkqi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ysqcvjdkqi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ysqcvjdkqi .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ FemaleLiteracyRate</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">70.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">2,654.875</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ FemaleLiteracyRate + FoodSupplykcPPD</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">69.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">2,005.556</td>\n<td headers=\"df\" class=\"gt_row gt_right\">1.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">649.319</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">22.339</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## So let's step through our hypothesis test (3/3)\n\n::: highlight-container\n::: highlight\n7.  Write conclusion for hypothesis test\n:::\n:::\n\n \n\nWe reject the null hypothesis at the 5% significance level. There is sufficient evidence that countries' food supply contributes significantly to the prediction of life expectancy, given that female literacy rate is already in the model (p-value < 0.001).\n\n# Learning Objectives\n\n1.  Interpret MLR (population) coefficient estimates with additional variable in model\n2.  Understand the use of the general F-test and interpret what it measures.\n3.  Understand the context of the **Overall F-test**, conduct the needed hypothesis test, and interpret the results.\n4.  Understand the context of the **single covariate F-test**, conduct the needed hypothesis test, and interpret the results.\n\n::: lob\n5.  Understand the context of the **group of covariates F-test**, conduct the needed hypothesis test, and interpret the results.\n:::\n\n## Covariate subset test: group of variables\n\nDoes the addition of some group of covariates of interest add significantly to the prediction of Y obtained through other independent variables already present in the model?\n\n-   For a general population MLR model, $$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2+ \\ldots + \\beta_k X_k + \\epsilon$$\n\nWe can create a hypothesis test for a group of covariate coefficients (subset of many)... **For example...**\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_1=\\beta_3 =0$ (this can be any coefficients)\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\nAt least one $\\beta_j\\neq0$ (for $j=2,3$)\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$Y = \\beta_0 + \\beta_2 X_2 + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$Y = \\beta_0 + \\beta_1 X + \\beta_2 X + \\beta_3 X_3+\\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n:::\n\n## Covariate subset F-test: general steps for hypothesis test (reference)\n\n::: columns\n::: {.column width=\"48%\"}\n::: highlight-container\n::: highlight\n1.  Met underlying LINE assumptions\n:::\n:::\n\n::: highlight-container\n::: highlight\n2.  State the null hypothesis\n:::\n:::\n\nFor example: \n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_1 = \\beta_3 = 0\\\\\n\\text{vs. } H_A&: \\text{At least one } \\beta_j\\neq0, \\text{for }j=1,3\n\\end{align}\n```\n\n::: highlight-container\n::: highlight\n3.  Specify the significance level\n:::\n:::\n\nOften we use $\\alpha = 0.05$\n\n::: highlight-container\n::: highlight\n4.  Specify the test statistic and its distribution under the null\n:::\n:::\n\nThe test statistic is $F$, and follows an F-distribution with numerator $df=k$ and denominator $df=n-k-1$. ($n$ = \\# obversation, $k$ = \\# covariates)\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n::: highlight-container\n::: highlight\n5.  Compute the value of the test statistic\n:::\n:::\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}$$\n\n::: highlight-container\n::: highlight\n6.  Calculate the p-value\n:::\n:::\n\nWe are generally calculating: $P(F_{k, n-k-1} > F)$\n\n::: highlight-container\n::: highlight\n7.  Write conclusion for hypothesis test\n:::\n:::\n\nWe (reject/fail to reject) the null hypothesis at the $100\\alpha\\%$ significance level. There is (sufficient/insufficient) evidence that predictors/covariates $2,3$ significantly improve the prediction of Y, given all the other covariates are in the model (p-value = $P(F_{1, n-2} > F)$).\n:::\n:::\n\n## We need to slightly alter our MLR example for life expectancy\n\nOur proposed population model to include water source percent (WS):\n\n$$\\text{LE} = \\beta_0 + \\beta_1 \\text{FLR} + \\beta_2 \\text{FS} + \\beta_3 WS + \\epsilon$$\n\n-   We don't have a fitted multiple regression model for this yet!\n\n**Our main question for the group covariate subset F-test:** Is the regression model containing food supply and water source percent improve the estimation of countries' life expectancy, given percent female literacy rate is already in the model?\n\n::: columns\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$LE = \\beta_0 + \\beta_1 FLR + \\epsilon$\n:::\n:::\n:::\n\n::: {.column width=\"45%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$LE = \\beta_0 + \\beta_1 FLR + \\beta_2 FS + \\beta_3 WS + \\epsilon$\n:::\n:::\n:::\n:::\n\n## Comparing the SSY, SSR, and SSE for reduced and full model\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: column\n**Reduced / null model** $$LE = \\beta_0 + \\beta_1 FLR + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_MLR_Inference_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 64.64$$ \n\n \n\n$$SSR = 27.24$$\n\n \n\n$$SSE = 37.39$$\n:::\n\n:::\n\n:::\n\n::: column\n**Full / Alternative model** $$LE = \\beta_0 + \\beta_1 FLR + \\beta_2 FS + \\beta_3 WS + \\epsilon$$\n\n::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_MLR_Inference_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n$$SSY = 64.64$$ \n\n \n\n$$SSR = 43.26$$\n\n \n\n$$SSE = 21.38$$\n:::\n\n:::\n\n:::\n:::\n\n## So let's step through our hypothesis test (1/3)\n\n::: highlight-container\n::: highlight\n1.  Met underlying LINE assumptions\n:::\n:::\n\n \n\n::: highlight-container\n::: highlight\n2.  State the null hypothesis\n:::\n:::\n\n\n```{=tex}\n\\begin{align}\nH_0 &: \\beta_2=\\beta_3=0\\\\\n\\text{vs. } H_A&: \\beta_2\\neq0 \\text{ and/or } \\beta_3\\neq0\n\\end{align}\n```\n\n::: highlight-container\n::: highlight\n3.  Specify the significance level\n:::\n:::\n\nOften we use $\\alpha = 0.05$\n\n::: highlight-container\n::: highlight\n4.  Specify the test statistic and its distribution under the null\n:::\n:::\n\nThe test statistic is $F$, and follows an F-distribution with numerator $df=k =2$ and denominator $df=n-k-1 = 72 - 2-1=69$. ($n$ = \\# obversation, $k$ = \\# covariates)\n\n## So let's step through our hypothesis test (2/3)\n\n::: highlight-container\n::: highlight\n5.  Compute the value of the test statistic / 6.  Calculate the p-value\n:::\n:::\n\nThe calculated **test statistic** is\n\n$$F^ = \\dfrac{\\frac{SSE(R) - SSE(F)}{df_R - df_F}}{\\frac{SSE(F)}{df_F}}$$\nANOVA table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_red3, mod_full3) %>% tidy() %>% gt() %>% tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"boflrlwavd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#boflrlwavd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#boflrlwavd thead, #boflrlwavd tbody, #boflrlwavd tfoot, #boflrlwavd tr, #boflrlwavd td, #boflrlwavd th {\n  border-style: none;\n}\n\n#boflrlwavd p {\n  margin: 0;\n  padding: 0;\n}\n\n#boflrlwavd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#boflrlwavd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#boflrlwavd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#boflrlwavd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#boflrlwavd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#boflrlwavd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#boflrlwavd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#boflrlwavd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#boflrlwavd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#boflrlwavd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#boflrlwavd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#boflrlwavd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#boflrlwavd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#boflrlwavd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#boflrlwavd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boflrlwavd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#boflrlwavd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#boflrlwavd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#boflrlwavd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boflrlwavd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#boflrlwavd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boflrlwavd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#boflrlwavd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boflrlwavd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#boflrlwavd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boflrlwavd .gt_left {\n  text-align: left;\n}\n\n#boflrlwavd .gt_center {\n  text-align: center;\n}\n\n#boflrlwavd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#boflrlwavd .gt_font_normal {\n  font-weight: normal;\n}\n\n#boflrlwavd .gt_font_bold {\n  font-weight: bold;\n}\n\n#boflrlwavd .gt_font_italic {\n  font-style: italic;\n}\n\n#boflrlwavd .gt_super {\n  font-size: 65%;\n}\n\n#boflrlwavd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#boflrlwavd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#boflrlwavd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#boflrlwavd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#boflrlwavd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#boflrlwavd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#boflrlwavd .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ FemaleLiteracyRate</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">70.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">2,654.875</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ FemaleLiteracyRate + FoodSupplykcPPD + WaterSourcePrct</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">68.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">1,517.916</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">1,136.959</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">25.467</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## So let's step through our hypothesis test (3/3)\n\n::: highlight-container\n::: highlight\n7.  Write conclusion for hypothesis test\n:::\n:::\n\n \n\nWe reject the null hypothesis at the 5% significance level. There is sufficient evidence that countries' food supply or water source (or both) contribute significantly to the prediction of life expectancy, given that female literacy rate is already in the model (p-value < 0.001).\n\n## Other ways to word the hypothesis tests (reference)\n\n-   Single covariate subset F-test\n\n    -   $H_0:$ $X^*$ does not significantly improve the prediction of $Y$, given that $X_1, X_2, \\ldots, X_p$ are already in the model\n    -   $H_A:$ $X^*$ significantly improves the prediction of $Y$, given that $X_1, X_2, \\ldots, X_p$ are already in the model\n    \n-   Group covariate subset F-test\n\n    -   $H_0:$ The addition of the $s$ variables $X_1^*, X_2^*, \\ldots, X_s^*$ does not significantly improve the prediction of $Y$, given that $X_1, X_2, \\ldots, X_q$ are already in the model\n    -   $H_A:$ The addition of the $s$ variables $X_1^*, X_2^*, \\ldots, X_s^*$ significantly improves the prediction of $Y$, given that $X_1, X_2, \\ldots, X_q$ are already in the model",
    "supporting": [
      "09_MLR_Inference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}