---
title: "Coefficient interpretations"
date: "1/29/2024"
date-modified: "1/17/2024"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

-   Keep in mind that words expected, average, and mean are interchangeable.

-   The following are required parts of the interpretation

    -   Units of Y

    -   Units of X

    -   Discussing intercept: Mean or average or expected before Y

    -   Discussing coefficient for continuous covariate: Mean or average or expected before difference, increase, or decrease

        -   OR: Mean or average or expected before Y
        -   Only need before difference or Y!!

    -   Confidence interval

    -   If other covariates in the model

        -   Discussing intercept: Must state that variables are equal to 0

            -   or at their centered value if centered!

        -   Discussing coefficient for covariate: Must state "adjusting for all other variables", "Controlling for all other variables", or "Holding all other variables constant"

            -   If only one other variable in the model, then replace "all other variables" with the single variable name

-   When the estimate of the population coefficient is...

    -   Positive: using the word "increase" in the place of "difference" helps with understanding the relationship

    -   Negative: using the word "decrease" in the place of "difference" helps with understanding the relationship

+--------------------------------------------+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Population Model                           | Variable information                                                       | Coefficient estimate interpretations                                                                                                          |
+============================================+============================================================================+===============================================================================================================================================+
| $Y=\beta_0+\beta_1X_1+\epsilon$            | $X_1$: continuous covariate                                                | -   $\widehat\beta_0$: Mean $Y$ when $X_1$ is 0                                                                                               |
|                                            |                                                                            |                                                                                                                                               |
|                                            |                                                                            |     -   Example: For someone who is 0 years old, the expected peak exercise heart rate is 214.233 beats per minute (95% CI: 204.918, 223.548) |
|                                            |                                                                            |                                                                                                                                               |
|                                            |                                                                            | -   $\widehat\beta_1$: Mean difference in $Y$ per 1 unit increase in $X_1$                                                                    |
|                                            |                                                                            |                                                                                                                                               |
|                                            |                                                                            |     -   Example: For every one year increase in age, the expected peak exercise heart rate decreases 0.834 bpm (95% CI: ....)                 |
+--------------------------------------------+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| $Y=\beta_0+\beta_1X^c_1+\epsilon$          | $X^c_1$: continuous covariate *that is centered around its mean or median* | -   $\widehat\beta_0$: Mean $Y$ when $X^c_1$ is at its mean or median                                                                         |
|                                            |                                                                            |                                                                                                                                               |
|                                            |                                                                            | -   $\widehat\beta_1$: Mean difference in $Y$ per 1 unit increase in $X^c_1$                                                                  |
+--------------------------------------------+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| $Y=\beta_0+\beta_1X_1+\beta_2X_2+\epsilon$ | $X_1$: continuous covariate                                                |                                                                                                                                               |
|                                            |                                                                            |                                                                                                                                               |
|                                            | $X_2$: continuous covariate                                                |                                                                                                                                               |
+--------------------------------------------+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
